// <auto-generated />
// Source: HarfBuzz hb-ot-shaper-indic-table.cc, Unicode 17.0.0.
// Regenerate with eng/generate-indic-shaping-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class IndicShapingData
{
    private static readonly ushort[] s_values =
    [
        3337, 3616, 1025, 1040, 1042, 1035, 1034, 2052, 1540, 3588, 1287, 3079, 2311, 2055,
        1799, 519, 3619, 3625, 3085, 3620, 3621, 3622, 3587, 3623, 1039, 3598, 3609, 3345,
        1800, 3336, 3385, 1026, 1556, 2069, 790, 2839, 3624, 3584, 3610, 3611, 3590, 3589,
    ];

    private static readonly byte[] s_u8 =
    [
        1, 0, 50, 4, 5, 96, 0, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 186, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 208, 224, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 7, 8, 9,
        10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 0, 0, 22, 23, 24, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 25, 26, 0, 0, 0, 27, 0, 0, 0, 0, 28, 29, 30, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 31, 0, 0, 0, 32, 0, 0, 0, 33, 0, 34, 0, 0, 0, 0, 0, 0, 35, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 25, 2, 10, 0, 0, 0, 0, 26, 0, 27, 0, 0, 0, 28, 0, 0, 0,
        0, 0, 29, 11, 30, 1, 1, 1, 4, 31, 32, 33, 34, 1, 6, 2, 35, 1, 12, 13, 7, 1, 1, 3,
        36, 14, 15, 37, 16, 17, 6, 2, 38, 39, 18, 40, 7, 1, 1, 3, 41, 42, 43, 44, 45, 46, 19, 2,
        47, 0, 18, 48, 49, 1, 1, 3, 20, 14, 50, 51, 0, 0, 21, 2, 0, 52, 53, 13, 7, 1, 1, 3,
        20, 54, 15, 55, 56, 17, 6, 2, 57, 0, 58, 59, 60, 61, 62, 63, 4, 64, 65, 66, 16, 0, 19, 2,
        0, 0, 67, 8, 9, 1, 1, 3, 4, 22, 68, 69, 70, 71, 23, 2, 0, 0, 12, 8, 9, 1, 1, 3,
        72, 22, 73, 74, 75, 76, 23, 2, 77, 0, 78, 8, 9, 1, 1, 1, 4, 79, 80, 81, 82, 83, 21, 2,
        0, 84, 85, 1, 1, 86, 87, 88, 89, 90, 2, 91, 92, 93, 94, 95, 96, 1, 97, 98, 2, 99, 0, 0,
        0, 0, 1, 1, 1, 100, 101, 11, 102, 103, 104, 105, 106, 107, 2, 10, 0, 0, 0, 0, 108, 5, 5, 109,
        110, 111, 0, 112, 113, 0, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 115, 0, 116, 0, 0, 0, 0, 0,
        0, 0, 0, 117, 0, 0, 0, 0, 0, 118, 0, 0, 0, 0, 5, 5, 119, 120, 0, 0, 0, 0, 121, 1,
        2, 122, 0, 0, 0, 0, 1, 1, 123, 124, 24, 24, 0, 0, 0, 0, 0, 0, 125, 0, 0, 0, 0, 0,
        0, 126, 0, 0, 2, 2, 2, 10, 0, 0, 0, 0, 2, 2, 2, 2, 4, 4, 4, 4, 10, 2, 2, 2,
        26, 2, 2, 2, 8, 8, 8, 8, 6, 18, 0, 4, 20, 14, 24, 2, 6, 6, 20, 6, 20, 6, 24, 2,
        4, 0, 0, 0, 6, 6, 6, 6, 66, 12, 14, 6, 6, 6, 20, 14, 2, 0, 36, 50, 52, 18, 38, 68,
        0, 0, 0, 32, 0, 0, 2, 16, 56, 12, 14, 6, 0, 0, 0, 4, 44, 2, 16, 2, 6, 22, 0, 4,
        2, 0, 36, 28, 6, 28, 0, 4, 30, 30, 30, 30, 0, 0, 42, 0, 34, 0, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 42, 12, 12, 6, 6, 6, 6, 24, 2, 2, 18, 36, 112, 18, 18, 18, 18, 18, 18, 114, 116,
        118, 120, 122, 18, 0, 6, 6, 6, 44, 10, 0, 2, 54, 32, 46, 10, 26, 0, 0, 0, 0, 0, 34, 70,
        6, 20, 0, 14, 44, 2, 16, 10, 2, 0, 72, 50, 124, 48, 0, 32, 48, 32, 46, 0, 126, 0, 0, 0,
        16, 2, 10, 10, 12, 2, 128, 0, 6, 6, 6, 14, 6, 14, 24, 2, 22, 22, 52, 74, 76, 32, 46, 0,
        16, 58, 58, 78, 130, 12, 14, 6, 2, 0, 36, 132, 134, 32, 46, 0, 0, 0, 80, 136, 16, 0, 0, 0,
        0, 70, 14, 6, 6, 20, 0, 6, 20, 6, 24, 0, 16, 10, 10, 2, 0, 16, 10, 0, 2, 10, 0, 2,
        2, 0, 0, 22, 76, 48, 0, 82, 54, 22, 84, 0, 12, 12, 138, 6, 28, 60, 38, 28, 86, 28, 88, 0,
        0, 0, 140, 86, 2, 10, 16, 0, 26, 2, 16, 2, 28, 60, 38, 60, 38, 18, 88, 0, 0, 0, 74, 38,
        0, 0, 16, 10, 142, 144, 0, 0, 12, 12, 146, 6, 2, 148, 150, 22, 22, 22, 48, 82, 54, 22, 84, 152,
        0, 0, 2, 154, 0, 0, 0, 14, 0, 2, 2, 2, 2, 2, 26, 2, 2, 156, 2, 2, 90, 6, 6, 6,
        6, 158, 92, 94, 160, 162, 62, 58, 164, 166, 168, 170, 4, 4, 0, 10, 2, 6, 6, 96, 98, 26, 2, 172,
        174, 100, 176, 178, 100, 102, 102, 2, 104, 62, 180, 2, 2, 182, 184, 186, 12, 12, 12, 188, 4, 12, 190, 0,
        2, 26, 2, 2, 2, 90, 6, 6, 6, 6, 0, 92, 62, 94, 98, 192, 194, 196, 96, 198, 200, 106, 106, 108,
        108, 202, 0, 0, 42, 0, 204, 0, 8, 206, 8, 8, 208, 40, 210, 40, 40, 2, 212, 214, 8, 34, 0, 0,
        0, 0, 216, 0, 4, 4, 4, 0, 0, 34, 0, 0, 0, 0, 110, 0, 0, 64, 110, 0, 0, 0, 218, 0,
        0, 42, 4, 34, 8, 40, 40, 40, 0, 0, 0, 220, 2, 2, 104, 16, 4, 2, 2, 10, 16, 2, 4, 34,
        0, 222, 78, 2, 56, 12, 0, 0, 0, 80, 72, 0, 37, 37, 2, 2, 6, 6, 31, 31, 0, 0, 2, 37,
        29, 29, 37, 31, 37, 2, 12, 12, 31, 37, 11, 11, 31, 2, 24, 2, 14, 14, 36, 36, 37, 11, 6, 37,
        22, 27, 12, 37, 27, 27, 37, 6, 24, 37, 11, 7, 11, 37, 11, 15, 11, 12, 15, 37, 37, 29, 0, 22,
        14, 12, 32, 32, 30, 30, 6, 29, 37, 15, 29, 37, 22, 37, 37, 12, 12, 11, 22, 22, 37, 22, 15, 15,
        11, 8, 14, 37, 14, 8, 2, 31, 35, 32, 32, 33, 35, 35, 33, 33, 35, 23, 23, 23, 2, 32, 26, 38,
        38, 38, 30, 37, 12, 15, 12, 7, 15, 12, 37, 0, 0, 29, 29, 12, 18, 11, 37, 13, 37, 3, 37, 28,
        11, 10, 10, 37, 10, 11, 29, 31, 37, 14, 37, 4, 4, 29, 6, 31, 2, 12, 12, 27, 25, 37, 2, 11,
        2, 24, 31, 35, 33, 34, 0, 32, 29, 9, 1, 21, 19, 20, 16, 2, 21, 21, 17, 2, 23, 2, 2, 35,
        32, 2, 20, 35, 34, 32, 32, 29, 2, 29, 29, 32, 32, 35, 35, 34, 34, 34, 38, 39, 39, 26, 9, 39,
        27, 39, 0, 37, 0, 27, 27, 0, 0, 4, 4, 0, 41, 40, 5, 37, 31, 12, 2, 23,
    ];

    public static ushort GetProperties(uint codePoint)
    {
        int valueIndex;
        if (codePoint >= 71_396u)
        {
            valueIndex = 37;
        }
        else
        {
            int level0 = GetNibble(s_u8, (int)(codePoint >> 9));
            int level1 = s_u8[70 + (level0 << 3) + (int)((codePoint >> 6) & 7)];
            int level2 = s_u8[186 + (level1 << 3) + (int)((codePoint >> 3) & 7)];
            int level3 = s_u8[488 + (level2 << 2) + (int)((codePoint >> 1) & 3)];
            valueIndex = s_u8[996 + level3 + (int)(codePoint & 1)];
        }
        return s_values[valueIndex];
    }

    private static int GetNibble(byte[] values, int index) =>
        values[index >> 1] >> ((index & 1) << 2) & 15;

    public static byte GetCategory(ushort properties) => (byte)properties;
    public static byte GetPosition(ushort properties) => (byte)(properties >> 8);

    public const byte Other = 0;
    public const byte Consonant = 1;
    public const byte Vowel = 2;
    public const byte Nukta = 3;
    public const byte Halant = 4;
    public const byte Zwnj = 5;
    public const byte Zwj = 6;
    public const byte Matra = 7;
    public const byte SyllableModifier = 8;
    public const byte VedicSign = 9;
    public const byte Placeholder = 10;
    public const byte DottedCircle = 11;
    public const byte RegisterShifter = 12;
    public const byte MatraPost = 13;
    public const byte Repha = 14;
    public const byte Ra = 15;
    public const byte ConsonantMedial = 16;
    public const byte Symbol = 17;
    public const byte ConsonantWithStacker = 18;
    public const byte SyllableModifierPost = 57;
    public const byte VowelAbove = 20;
    public const byte VowelBelow = 21;
    public const byte VowelPre = 22;
    public const byte VowelPost = 23;
    public const byte Robatic = 25;
    public const byte XGroup = 26;
    public const byte YGroup = 27;
    public const byte Asat = 32;
    public const byte MedialHa = 35;
    public const byte MedialRa = 36;
    public const byte MedialWa = 37;
    public const byte MedialYa = 38;
    public const byte PwoTone = 39;
    public const byte VariationSelector = 40;
    public const byte MedialLa = 41;

    public const byte PositionStart = 0;
    public const byte PositionRaToBecomeReph = 1;
    public const byte PositionPreMatra = 2;
    public const byte PositionPreConsonant = 3;
    public const byte PositionBaseConsonant = 4;
    public const byte PositionAfterMain = 5;
    public const byte PositionAboveConsonant = 6;
    public const byte PositionBeforeSub = 7;
    public const byte PositionBelowConsonant = 8;
    public const byte PositionAfterSub = 9;
    public const byte PositionBeforePost = 10;
    public const byte PositionPostConsonant = 11;
    public const byte PositionAfterPost = 12;
    public const byte PositionSyllableModifierVedic = 13;
    public const byte PositionEnd = 14;
}
