<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.Input.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProGPU.Backend\ProGPU.Backend.csproj" />
    <ProjectReference Include="..\ProGPU.Vector\ProGPU.Vector.csproj" />
    <ProjectReference Include="..\ProGPU.Scene\ProGPU.Scene.csproj" />
    <ProjectReference Include="..\ProGPU.WinUI\ProGPU.WinUI.csproj" />
    <ProjectReference Include="..\ProGPU.Voxel\ProGPU.Voxel.csproj" />
  </ItemGroup>
</Project>
