<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <SvgSourceRoot Condition="'$(SvgSourceRoot)' == ''">$(MSBuildThisFileDirectory)..\..\external\Svg.Skia\externals\SVG</SvgSourceRoot>
    <ProGpuSourceRoot Condition="'$(ProGpuSourceRoot)' == ''">$(MSBuildThisFileDirectory)..\..</ProGpuSourceRoot>
    <UseProGpuSystemDrawing>true</UseProGpuSystemDrawing>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SvgSourceRoot)\Source\Svg.csproj"
                      AdditionalProperties="ManagePackageVersionsCentrally=false" />
    <ProjectReference Include="..\..\src\System.Drawing.Common\System.Drawing.Common.csproj" />
    <PackageReference Include="StbImageSharp" />
  </ItemGroup>
</Project>
