#ifndef PROGPU_NATIVE_SCENE_BUILDER_TESTS_HPP
#define PROGPU_NATIVE_SCENE_BUILDER_TESTS_HPP

namespace progpu::native::tests {

bool semantic_scene_builder_is_deterministic_and_valid();
bool semantic_scene_builder_bounds_composite_only_guidelines();
bool semantic_scene_builder_preserves_shared_path_segments();
bool semantic_scene_builder_records_general_brushes();
bool semantic_scene_builder_records_native_svg_layers();
bool semantic_scene_builder_rejects_invalid_state();
bool semantic_scene_builder_reuses_retained_images();
bool semantic_scene_builder_records_image_patch_batches();
bool semantic_scene_builder_batches_compatible_image_draws();
bool semantic_scene_builder_serializes_external_images_pointer_free();
bool semantic_scene_builder_updates_retained_images_transactionally();
bool semantic_scene_builder_records_styled_glyph_runs();
bool semantic_scene_content_hashes_normalize_resource_ordinals();
bool semantic_scene_builder_shares_glyph_segments_across_raster_sizes();
bool semantic_scene_builder_records_native_shaped_runs();
bool semantic_scene_builder_records_color_bitmap_glyphs();
bool semantic_scene_builder_records_layers_masks_and_effects();
bool semantic_scene_builder_preserves_stable_resource_identities();
bool semantic_scene_builder_records_retained_3d_families();
bool semantic_scene_builder_records_retained_hit_test_index();
bool semantic_scene_content_hashes_isolate_image_updates();

} // namespace progpu::native::tests

#endif
