#include "progpu_native_edit_word_boundaries.hpp"
#include "progpu_native_text.hpp"

#include <algorithm>
#include <array>
#include <iostream>
#include <stdexcept>
#include <string_view>
#include <thread>
#include <vector>

namespace {
using namespace progpu::native::text;

void require(bool condition, const char* message)
{
    if (!condition) throw std::runtime_error(message);
}

std::vector<std::uint16_t> units(std::u16string_view text)
{
    return {text.begin(), text.end()};
}

void check(std::u16string_view text, std::initializer_list<std::uint32_t> expected,
    std::uint32_t leading = 0U)
{
    const auto original = units(text);
    edit_word_boundary_snapshot actual{{73U, 91U}, 73U};
    edit_word_boundary_error error{};
    if (!try_create_edit_word_boundary_snapshot(original, actual, error)) {
        std::cerr << "source length " << text.size() << "; error " <<
            static_cast<std::uint32_t>(error) << '\n';
        throw std::runtime_error("EDIT profile unexpectedly failed");
    }
    if (actual.positions != std::vector<std::uint32_t>(expected)) {
        std::cerr << "source length " << text.size() << "; actual boundaries:";
        for (const auto position : actual.positions) std::cerr << ' ' << position;
        std::cerr << '\n';
        throw std::runtime_error("Independent EDIT boundary inventory differs");
    }
    require(actual.leading_content_start == leading, "Original leading-content seam differs");
    require(error == edit_word_boundary_error::none, "Success left an error");
    require(original == units(text), "Classifier rewrote original UTF-16");
}

void original_reference_inventories()
{
    // Literal original UTF-16 inventories, independently observed from Microsoft
    // EDIT, not generated by this worker, ICU, modern UAX29 or source shaping.
    // The original20 + four dictionary-script requests remain separately named.
    check(u"  alpha  beta  ", {0, 2, 9, 15}, 2); // spaces
    check(u"alpha,beta.gamma! (tail) - end ", {0, 18, 25, 27, 31});
    check(u"one\t\ttwo \tthree ", {0, 5, 9, 10, 16}); // tabs single
    check(u"one\t\ttwo \tthree ", {0, 5, 9, 10, 16}); // tabs multiline
    check(u"alpha\r\nbeta\r\n\r\ngamma ", {0, 5, 7, 11, 13, 15, 21});
    check(u"alpha\r\nbeta\r\n\r\ngamma ", {0, 5, 7, 11, 13, 15, 21});
    check(u"go A\U0001F600 e\u0301 fin ", {0, 3, 4, 7, 10, 14});
    check(u"abc \u05D0\u05D1\u05D2, \u0639\u0631\u0628\u0649 end ", {0, 4, 9, 14, 18});
    check(u"abc \u05D0\u05D1\u05D2, \u0639\u0631\u0628\u0649 end ", {0, 4, 9, 14, 18});
    // Oracle text only: a password source must NEVER call this worker with its
    // source content. Forms already takes SelectAll before provider admission.
    check(u"alpha, beta\tend ", {0, 7, 12, 16});
    check(u"  alpha,beta \ttail ", {0, 2, 13, 14, 19}, 2);
    check(u"alpha beta gamma delta end ", {0, 6, 11, 17, 23, 27});
    check(u"a\u00A0b\u2003c\u202Fd\u3000e ", {0, 4, 6, 8, 10});
    // Original symbols case and emoji-context case remain explicit missing
    // contracts below; there is no guessed whole-provider admission.
    check(u"ab\rcd\nef ", {0, 2, 3, 6, 9});
    check(u"ab\rcd\nef ", {0, 2, 3, 6, 9});
    // CRCRLF has no available interior EDIT coordinates in the receipt. The
    // atomic group follows the documented EditWordBreakProc CRCRLF contract;
    // this is NOT a newly claimed observed interior coordinate at index3.
    check(u"ab\r\r\ncd ", {0, 2, 5, 8});
    check(u"abcdefghijklmnopqrstuvwxyz0123456789 ", {0, 37});
    check(u"a\U00010400b\U0001D11Ec\U00020000d ", {0, 7, 9, 11});
#if defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    check(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        {0, 4, 7, 11, 15});
    check(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 \u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        {0, 4, 8, 12, 16});
#endif
    check(u"\u0EAA\u0EB0\u0E9A\u0EB2\u0E8D\u0E94\u0EB5\u0EAA\u0EB0\u0E9A\u0EB2\u0E8D\u0E94\u0EB5 ", {0, 15});
    check(u"\u1797\u17B6\u179F\u17B6\u1781\u17D2\u1798\u17C2\u179A\u1797\u17B6\u179F\u17B6\u1781\u17D2\u1798\u17C2\u179A ",
        {0, 18, 19});
}

void missing_contracts_are_atomic()
{
    const auto check_failure = [](std::u16string_view text, edit_word_boundary_error expected) {
        edit_word_boundary_snapshot snapshot{{17U, 23U, 29U}, 23U};
        const auto original_positions = snapshot.positions;
        edit_word_boundary_error error{};
        require(!try_create_edit_word_boundary_snapshot(units(text), snapshot, error),
            "Unknown EDIT policy was silently admitted");
        require(error == expected, "Unknown policy did not preserve its precise diagnostic");
        require(snapshot.positions == original_positions && snapshot.leading_content_start == 23U,
            "Failed classifier published a partial generation");
    };
    check_failure(u"a\u00A9b\u2603c\U0001F600d ",
        edit_word_boundary_error::unqualified_bmp_symbol_policy);
    check_failure(u"a\u2603\uFE0Fb\U0001F469\u200D\U0001F4BBc ",
        edit_word_boundary_error::unqualified_bmp_symbol_policy);
    check_failure(u"x\u2764\uFE0F\u200D\U0001F4BBy ",
        edit_word_boundary_error::unqualified_bmp_symbol_policy);
    // Canonical itemization, not a fixture-word lookup, identifies the precise
    // as-yet unqualified Arabic-run entry with no existing profile boundary.
    check_failure(u"x\u0628\u062Ay ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"x\u0628\u200D\u062Ay ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"x\u0628\u200C\u062Ay ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    const std::array<char16_t, 1> isolated_surrogate{0xD800U};
    check_failure({isolated_surrogate.data(), isolated_surrogate.size()},
        edit_word_boundary_error::invalid_encoding);
    check_failure(u"\u1000\u1001", edit_word_boundary_error::unqualified_complex_script_policy);
#if !defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    check_failure(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        edit_word_boundary_error::dependency_unavailable);
    check_failure(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 \u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        edit_word_boundary_error::dependency_unavailable);
#endif
}

void independently_observed_joiner_contexts()
{
    // Literal ScriptStringAnalyse opportunities AND actual EDIT gestures from
    // Server2025 Build36862800693. This is separate from the Win11 original24
    // receipt; no modern grapheme boundary is substituted for its UTF-16 seam.
    check(u"xaby ", {0, 5});
    check(u"xa\u200Dby ", {0, 6});
    check(u"xa\u200Cby ", {0, 6});
    check(u"x\u0915\u094D\u0937y ", {0, 6});
    check(u"x\u0915\u094D\u200D\u0937y ", {0, 7});
    check(u"x\u0915\u094D\u200C\u0937y ", {0, 7});
    check(u"x\U0001F469\U0001F4BBy ", {0, 1, 3, 5, 7});
    check(u"x\U0001F469\u200D\U0001F4BBy ", {0, 1, 4, 6, 8});
    check(u"x\U0001F469\u200C\U0001F4BBy ", {0, 1, 4, 6, 8});
    check(u"x\U00010400\U00010401y ", {0, 7});
    check(u"x\U00010400\u200D\U00010401y ", {0, 8});
    check(u"x\U00010400\u200C\U00010401y ", {0, 8});
    check(u"x\U00020000\U00020001y ", {0, 1, 3, 5, 7});
    check(u"x\U00020000\u200D\U00020001y ", {0, 1, 4, 6, 8});
    check(u"x\U00020000\u200C\U00020001y ", {0, 1, 4, 6, 8});
    check(u"\u200Da\U0001F600b ", {0, 2, 4, 6});
    check(u"a\U0001F600\u200D ", {0, 1, 5});
    check(u"a \u200Db ", {0, 2, 5});
    check(u"a\U0001F469\u200D\u200D\U0001F4BBb ", {0, 1, 5, 7, 9});

    // A non-BMP emoji profile boundary remains INSIDE the original modern
    // emoji grapheme. Default UAX14 must continue prohibiting that same seam.
    const auto original = units(u"x\U0001F469\u200D\U0001F4BBy ");
    std::vector<unicode_scalar> scalars(6U);
    std::uint32_t written = 0U;
    require(try_decode_utf16(original, scalars, written) && written == scalars.size(),
        "Joiner source decode failed");
    std::vector<unicode_line_break_class> classes(scalars.size());
    std::vector<text_line_break_kind> breaks(scalars.size());
    require(try_resolve_unicode_line_breaks(scalars, classes, breaks),
        "Default joiner UAX14 failed");
    require(breaks[2] == text_line_break_kind::prohibited,
        "EDIT joiner profile changed the original UAX14 LB8a contract");
    require(get_unicode_line_break_class(0x200DU) ==
        unicode_line_break_class::zero_width_joiner,
        "EDIT joiner profile rewrote the original Unicode property");
}

void concurrent_snapshots_own_independent_outputs()
{
#if defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    constexpr std::u16string_view text =
        u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ";
    const std::vector<std::uint32_t> expected{0U, 4U, 7U, 11U, 15U};
#else
    constexpr std::u16string_view text = u"  alpha  beta  ";
    const std::vector<std::uint32_t> expected{0U, 2U, 9U, 15U};
#endif
    std::array<edit_word_boundary_snapshot, 8> snapshots{};
    std::array<bool, 8> success{};
    std::array<std::thread, 8> workers;
    for (std::size_t index = 0U; index < workers.size(); ++index)
        workers[index] = std::thread([&, index] {
            auto original = units(text);
            edit_word_boundary_error error{};
            success[index] = try_create_edit_word_boundary_snapshot(original, snapshots[index], error);
            std::fill(original.begin(), original.end(), static_cast<std::uint16_t>('X'));
        });
    for (auto& worker : workers) worker.join();
    for (std::size_t index = 0U; index < snapshots.size(); ++index) {
        require(success[index] && snapshots[index].positions == expected,
            "Concurrent original-source snapshot lost its owned generation");
        for (std::size_t other = 0U; other < index; ++other)
            require(snapshots[index].positions.data() != snapshots[other].positions.data(),
                "Independent snapshots borrow a mutable cached output");
    }
    snapshots[0].positions.clear();
    require(snapshots[1].positions == expected, "Retiring one output mutated another");
}

void original_units_and_default_worker_are_independent()
{
    check(u"", {0});
    check(u"   ", {0, 3}, 3);
    check(u"\talpha ", {0, 1, 7}); // TAB is not fWhiteSpace / leading skipped content.
    check(u"\u202Falpha ", {0, 1, 7}, 1);
    check(u"\u00A0alpha ", {0, 7});
    // The UAX14 worker still prohibits a break through GL / NNBSP; EDIT's
    // explicit whitespace seam must not mutate its Unicode17 property table.
    const auto original = units(u"a\u202Fb");
    std::array<unicode_scalar, 3> scalars{};
    std::uint32_t written = 0U;
    require(try_decode_utf16(original, scalars, written) && written == 3U, "Decode failed");
    std::array<unicode_line_break_class, 3> classes{};
    std::array<text_line_break_kind, 3> breaks{};
    require(try_resolve_unicode_line_breaks(scalars, classes, breaks), "UAX14 failed");
    require(breaks[0] == text_line_break_kind::prohibited &&
        breaks[1] == text_line_break_kind::prohibited, "EDIT changed default UAX14");
}
} // namespace

int main()
{
    try {
        concurrent_snapshots_own_independent_outputs();
        original_reference_inventories();
        missing_contracts_are_atomic();
        independently_observed_joiner_contexts();
        original_units_and_default_worker_are_independent();
        std::cout << "EDIT boundary profile controls passed; ordinary provider admission remains closed\n";
        return 0;
    } catch (const std::exception& failure) {
        std::cerr << failure.what() << '\n';
        return 1;
    }
}
