#pragma once

#include "progpu_native_direct2d_compat.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <limits>

namespace progpu::native::direct2d::tests {

// The nonuniform case is the original system-Direct2D receipt retained by
// compat_tests (afd3cf9a9 / 305bcf051). Identity and translation retain the
// same positive-axis source family. No nested/reflected/sheared admission is
// inferred. Literal points below are not generated by the widening helper.
inline constexpr compat::rectangle_f default_stroke_rectangle{1, 2, 5, 8};
inline constexpr compat::matrix_3x2_f default_stroke_world{2, 0, 0, 3, 10, -4};
inline constexpr std::array<compat::matrix_3x2_f, 3U> default_stroke_intrinsics{{
    {1, 0, 0, 1, 0, 0}, {1, 0, 0, 1, 5, 7}, {2, 0, 0, 0.5F, 5, 7}}};
inline constexpr std::array<compat::rectangle_f, 3U> default_stroke_bounds{{
    {10, -1, 22, 23}, {20, 20, 32, 44}, {22, 17, 42, 32}}};
inline constexpr std::array<compat::rectangle_f, 3U> default_stroke_zero_bounds{{
    {12, 2, 20, 20}, {22, 23, 30, 41}, {24, 20, 40, 29}}};
inline constexpr std::array<std::array<compat::point_2f, 2U>, 3U> default_stroke_probes{{
    {{{11, 10}, {16, 10}}}, {{{21, 30}, {26, 30}}}, {{{23, 24}, {30, 24}}}}};
inline constexpr std::array<std::array<compat::point_2f, 27U>, 3U> default_stroke_points{{
    {{{12, 5}, {12, -1}, {20, -1}, {22, -1}, {22, 2}, {22, 20}, {22, 23},
      {20, 23}, {12, 23}, {10, 23}, {10, 20}, {10, 2}, {10, -1}, {12, -1},
      {12, 5}, {12, 2}, {14, 2}, {14, 20}, {12, 20}, {12, 17}, {20, 17},
      {20, 20}, {18, 20}, {18, 2}, {20, 2}, {20, 5}, {12, 5}}},
    {{{22, 26}, {22, 20}, {30, 20}, {32, 20}, {32, 23}, {32, 41}, {32, 44},
      {30, 44}, {22, 44}, {20, 44}, {20, 41}, {20, 23}, {20, 20}, {22, 20},
      {22, 26}, {22, 23}, {24, 23}, {24, 41}, {22, 41}, {22, 38}, {30, 38},
      {30, 41}, {28, 41}, {28, 23}, {30, 23}, {30, 26}, {22, 26}}},
    {{{24, 23}, {24, 17}, {40, 17}, {42, 17}, {42, 20}, {42, 29}, {42, 32},
      {40, 32}, {24, 32}, {22, 32}, {22, 29}, {22, 20}, {22, 17}, {24, 17},
      {24, 23}, {24, 20}, {26, 20}, {26, 29}, {24, 29}, {24, 26}, {40, 26},
      {40, 29}, {38, 29}, {38, 20}, {40, 20}, {40, 23}, {24, 23}}}}};

enum class default_stroke_sink_event_kind : std::uint32_t {
    fill, flags, begin, line, bezier, end, close
};

struct default_stroke_sink_event final {
    default_stroke_sink_event_kind kind{};
    std::uint32_t value = 0U;
    compat::point_2f point{};
};

struct default_stroke_sink_transcript final {
    std::array<default_stroke_sink_event, 32U> events{};
    std::size_t count = 0U;
    bool overflow = false;
    compat::fill_mode fill = compat::fill_mode::alternate;
    // A retained caller state is not a SetSegmentFlags callback. The existing
    // original receipt requires this state to survive untouched.
    compat::path_segment flags = compat::path_segment::force_unstroked;
};

class default_stroke_sink final : public compat::simplified_geometry_sink {
public:
    com::result PROGPU_NATIVE_COM_CALL QueryInterface(com::guid_ref id, void** value) noexcept override
    {
        if (value == nullptr) return com::pointer_error;
        *value = nullptr;
        if (!com::guid_equal(id, com::unknown_interface_id()) &&
            !com::guid_equal(id, compat::simplified_geometry_sink_interface_id)) return com::no_interface;
        *value = static_cast<compat::simplified_geometry_sink*>(this);
        AddRef();
        return com::ok;
    }
    com::reference_count_value PROGPU_NATIVE_COM_CALL AddRef() noexcept override { return references_.add_ref(); }
    com::reference_count_value PROGPU_NATIVE_COM_CALL Release() noexcept override { return references_.release(this); }
    void PROGPU_NATIVE_COM_CALL SetFillMode(compat::fill_mode value) noexcept override
    {
        transcript.fill = value;
        append(default_stroke_sink_event_kind::fill, static_cast<std::uint32_t>(value));
    }
    void PROGPU_NATIVE_COM_CALL SetSegmentFlags(compat::path_segment value) noexcept override
    {
        transcript.flags = value;
        append(default_stroke_sink_event_kind::flags, static_cast<std::uint32_t>(value));
    }
    void PROGPU_NATIVE_COM_CALL BeginFigure(compat::point_2f point, compat::figure_begin value) noexcept override
    {
        append(default_stroke_sink_event_kind::begin, static_cast<std::uint32_t>(value), point);
    }
    void PROGPU_NATIVE_COM_CALL AddLines(const compat::point_2f* points, std::uint32_t count) noexcept override
    {
        // Normalize only batching: old receipts compare every ordered point,
        // not how the original implementation partitions AddLines calls.
        if (points == nullptr && count != 0U) { transcript.overflow = true; return; }
        for (std::uint32_t i = 0U; i < count; ++i)
            append(default_stroke_sink_event_kind::line, 0U, points[i]);
    }
    void PROGPU_NATIVE_COM_CALL AddBeziers(const compat::bezier_segment*, std::uint32_t count) noexcept override
    {
        // This receipt has no curves. Recording even one callback is enough
        // to reject a different primitive transcript without dropping it.
        append(default_stroke_sink_event_kind::bezier, count);
    }
    void PROGPU_NATIVE_COM_CALL EndFigure(compat::figure_end value) noexcept override
    {
        append(default_stroke_sink_event_kind::end, static_cast<std::uint32_t>(value));
    }
    com::result PROGPU_NATIVE_COM_CALL Close() noexcept override
    {
        append(default_stroke_sink_event_kind::close);
        return com::ok;
    }
    default_stroke_sink_transcript transcript{};
private:
    void append(default_stroke_sink_event_kind kind, std::uint32_t value = 0U,
        compat::point_2f point = {}) noexcept
    {
        if (transcript.count == transcript.events.size()) { transcript.overflow = true; return; }
        transcript.events[transcript.count++] = {kind, value, point};
    }
    friend class com::atomic_reference_count<default_stroke_sink>;
    ~default_stroke_sink() = default;
    com::atomic_reference_count<default_stroke_sink> references_;
};

inline bool same_default_stroke_bounds(const compat::rectangle_f& a, const compat::rectangle_f& b) noexcept
{
    return a.left == b.left && a.top == b.top && a.right == b.right && a.bottom == b.bottom;
}

inline bool same_default_stroke_event(const default_stroke_sink_event& a,
    const default_stroke_sink_event& b) noexcept
{
    return a.kind == b.kind && a.value == b.value && a.point.x == b.point.x && a.point.y == b.point.y;
}

struct default_transformed_stroke_observation final {
    compat::rectangle_f bounds{};
    std::array<std::int32_t, 2U> contains{};
    default_stroke_sink_transcript sink{};
};

using default_transformed_stroke_observations = std::array<default_transformed_stroke_observation, 6U>;

inline bool same_default_transformed_stroke_observations(const default_transformed_stroke_observations& a,
    const default_transformed_stroke_observations& b) noexcept
{
    for (std::size_t i = 0U; i < a.size(); ++i) {
        const auto& x = a[i];
        const auto& y = b[i];
        if (!same_default_stroke_bounds(x.bounds, y.bounds) || x.contains != y.contains ||
            x.sink.overflow || y.sink.overflow || x.sink.count != y.sink.count ||
            x.sink.fill != y.sink.fill || x.sink.flags != y.sink.flags) return false;
        for (std::size_t event = 0U; event < x.sink.count; ++event)
            if (!same_default_stroke_event(x.sink.events[event], y.sink.events[event])) return false;
    }
    return true;
}

template<class Require>
default_transformed_stroke_observations verify_default_transformed_strokes(compat::factory* factory, Require require)
{
    com::pointer<compat::rectangle_geometry> rectangle;
    require(factory->CreateRectangleGeometry(&default_stroke_rectangle, rectangle.put()) == com::ok && rectangle,
        "default transformed source rectangle creation failed");
    default_transformed_stroke_observations observations{};
    for (std::size_t frame = 0U; frame < default_stroke_intrinsics.size(); ++frame) {
        com::pointer<compat::transformed_geometry> transformed;
        require(factory->CreateTransformedGeometry(rectangle.get(), &default_stroke_intrinsics[frame],
            transformed.put()) == com::ok && transformed, "default transformed geometry creation failed");
        com::pointer<compat::geometry> retained_source;
        transformed->GetSourceGeometry(retained_source.put());
        require(retained_source.get() == rectangle.get(), "default transformed geometry lost its actual source identity");
        for (std::size_t zero = 0U; zero < 2U; ++zero) {
            const float width = zero == 0U ? 2.0F : 0.0F;
            auto& output = observations[frame * 2U + zero];
            require(transformed->GetWidenedBounds(width, nullptr, &default_stroke_world,
                core::default_flattening_tolerance, &output.bounds) == com::ok &&
                same_default_stroke_bounds(output.bounds, zero == 0U
                    ? default_stroke_bounds[frame] : default_stroke_zero_bounds[frame]),
                "default transformed stroke bounds applied intrinsic scaling after widening");
            for (std::size_t point = 0U; point < output.contains.size(); ++point) {
                require(transformed->StrokeContainsPoint(default_stroke_probes[frame][point], width, nullptr,
                    &default_stroke_world, core::default_flattening_tolerance, &output.contains[point]) == com::ok &&
                    output.contains[point] == (zero == 0U && point == 0U ? 1 : 0),
                    "default transformed stroke hit differs from literal edge/interior probes");
            }
            com::pointer<default_stroke_sink> sink;
            sink.attach(new default_stroke_sink());
            require(transformed->Widen(width, nullptr, &default_stroke_world,
                core::default_flattening_tolerance, sink.get()) == com::ok,
                "default transformed rectangle widening failed");
            output.sink = sink->transcript;
            default_stroke_sink_transcript expected{};
            expected.fill = compat::fill_mode::winding;
            expected.events[expected.count++] = {default_stroke_sink_event_kind::fill,
                static_cast<std::uint32_t>(compat::fill_mode::winding), {}};
            if (zero == 0U) {
                expected.events[expected.count++] = {default_stroke_sink_event_kind::begin,
                    static_cast<std::uint32_t>(compat::figure_begin::filled), default_stroke_points[frame][0U]};
                for (std::size_t point = 1U; point < default_stroke_points[frame].size(); ++point)
                    expected.events[expected.count++] = {default_stroke_sink_event_kind::line, 0U,
                        default_stroke_points[frame][point]};
                expected.events[expected.count++] = {default_stroke_sink_event_kind::end,
                    static_cast<std::uint32_t>(compat::figure_end::open), {}};
            }
            require(!output.sink.overflow && output.sink.count == expected.count &&
                output.sink.fill == expected.fill && output.sink.flags == expected.flags,
                "default transformed Widen changed callbacks or the caller segment state");
            for (std::size_t event = 0U; event < expected.count; ++event)
                require(same_default_stroke_event(output.sink.events[event], expected.events[event]),
                    "default transformed Widen changed its original ordered sink transcript");
        }
    }
    return observations;
}

// Product-only failures: do not demand that the original system rejects the
// portable implementation's intentionally unadmitted geometry families. The
// singular intrinsic control is portable-only: the Windows wrapper's unchanged
// fallback is outside this positive-axis selector and has a separate contract.
template<class Require>
void verify_default_transformed_stroke_rejections(compat::factory* factory, Require require,
    bool check_portable_singular = false)
{
    com::pointer<compat::rectangle_geometry> rectangle;
    com::pointer<compat::transformed_geometry> transformed;
    require(factory->CreateRectangleGeometry(&default_stroke_rectangle, rectangle.put()) == com::ok &&
        factory->CreateTransformedGeometry(rectangle.get(), &default_stroke_intrinsics[2U],
            transformed.put()) == com::ok, "default transformed rejection setup failed");
    com::pointer<default_stroke_sink> sink;
    sink.attach(new default_stroke_sink());
    const auto rejects = [&](compat::geometry* geometry, float width, const compat::matrix_3x2_f* world,
        float tolerance, com::result expected) {
        compat::rectangle_f bounds{99, 98, 97, 96};
        std::int32_t contains = 77;
        require(geometry->GetWidenedBounds(width, nullptr, world, tolerance, &bounds) == expected &&
            same_default_stroke_bounds(bounds, {}), "rejected default transformed bounds changed output");
        require(geometry->StrokeContainsPoint({23, 24}, width, nullptr, world, tolerance, &contains) == expected &&
            contains == 0, "rejected default transformed hit changed output");
        require(geometry->Widen(width, nullptr, world, tolerance, sink.get()) == expected &&
            sink->transcript.count == 0U && !sink->transcript.overflow &&
            sink->transcript.fill == compat::fill_mode::alternate &&
            sink->transcript.flags == compat::path_segment::force_unstroked,
            "rejected default transformed Widen touched caller sink state");
    };
    for (const float width : {-1.0F, std::numeric_limits<float>::infinity(),
            std::numeric_limits<float>::quiet_NaN()})
        rejects(transformed.get(), width, &default_stroke_world, core::default_flattening_tolerance,
            com::invalid_argument);
    for (const float tolerance : {0.0F, std::numeric_limits<float>::infinity(),
            std::numeric_limits<float>::quiet_NaN()})
        rejects(transformed.get(), 2.0F, &default_stroke_world, tolerance, com::invalid_argument);
    for (const float value : {std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN()}) {
        auto world = default_stroke_world;
        world.m31 = value;
        rejects(transformed.get(), 2.0F, &world, core::default_flattening_tolerance, com::invalid_argument);
        std::int32_t contains = 77;
        require(transformed->StrokeContainsPoint({value, 24}, 2.0F, nullptr, &default_stroke_world,
            core::default_flattening_tolerance, &contains) == com::invalid_argument && contains == 0,
            "invalid default transformed query point published a hit");
    }
    require(transformed->GetWidenedBounds(2, nullptr, &default_stroke_world,
        core::default_flattening_tolerance, nullptr) == com::pointer_error &&
        transformed->StrokeContainsPoint({23, 24}, 2, nullptr, &default_stroke_world,
            core::default_flattening_tolerance, nullptr) == com::pointer_error &&
        transformed->Widen(2, nullptr, &default_stroke_world,
            core::default_flattening_tolerance, nullptr) == com::pointer_error,
        "default transformed null-output error contract changed");
    const compat::rectangle_f flat{1, 2, 1, 8};
    com::pointer<compat::rectangle_geometry> degenerate;
    com::pointer<compat::transformed_geometry> flat_transformed, singular;
    const compat::matrix_3x2_f singular_intrinsic{0, 0, 0, 1, 5, 7};
    require(factory->CreateRectangleGeometry(&flat, degenerate.put()) == com::ok &&
        factory->CreateTransformedGeometry(degenerate.get(), &default_stroke_intrinsics[2U],
            flat_transformed.put()) == com::ok &&
        factory->CreateTransformedGeometry(rectangle.get(), &singular_intrinsic, singular.put()) == com::ok,
        "default transformed unsupported geometry setup failed");
    rejects(flat_transformed.get(), 2, &default_stroke_world, core::default_flattening_tolerance,
        compat::not_implemented);
    if (check_portable_singular)
        rejects(singular.get(), 2, &default_stroke_world, core::default_flattening_tolerance,
            compat::not_implemented);
    require(transformed->Widen(4, nullptr, &default_stroke_world, core::default_flattening_tolerance,
        sink.get()) == compat::not_implemented && sink->transcript.count == 0U,
        "collapsed inner default transformed stroke emitted a partial sink");
}

} // namespace progpu::native::direct2d::tests
