#ifndef PROGPU_NATIVE_SCENE_BUILDER_TESTS_HPP
#define PROGPU_NATIVE_SCENE_BUILDER_TESTS_HPP

namespace progpu::native::tests {

bool semantic_scene_builder_is_deterministic_and_valid();
bool semantic_scene_builder_rgb_transport_is_owned_and_atomic();
bool semantic_scene_builder_append_capacity_is_amortized_and_atomic();
bool semantic_scene_builder_isolation_rejects_missing_layer_atomically();
bool semantic_scene_builder_isolation_promotes_nearest_layer();
bool semantic_scene_builder_isolation_preserves_materialized_layers();
bool semantic_scene_builder_isolation_preserves_ordinary_elision();
bool semantic_scene_builder_isolation_tracks_depth_across_pop_and_reset();
bool semantic_scene_builder_isolation_rejects_historical_depth_atomically();
bool semantic_scene_builder_copies_outside_clips_atomically();
bool semantic_scene_builder_moves_sources_outside_clips_atomically();
bool semantic_scene_builder_bounds_composite_only_guidelines();
bool semantic_scene_builder_records_final_composite_clip();
bool semantic_scene_builder_preserves_shared_path_segments();
bool semantic_scene_builder_records_general_brushes();
bool semantic_scene_builder_records_native_svg_layers();
bool semantic_scene_builder_rejects_invalid_state();
bool semantic_scene_builder_reuses_retained_images();
bool semantic_scene_builder_records_image_patch_batches();
bool semantic_scene_builder_batches_compatible_image_draws();
bool semantic_scene_builder_serializes_external_images_pointer_free();
bool semantic_scene_builder_updates_retained_images_transactionally();
bool semantic_scene_builder_records_styled_glyph_runs();
bool semantic_scene_content_hashes_normalize_resource_ordinals();
bool semantic_scene_content_hashes_preserve_scene_ownership();
bool semantic_mapped_layers_preserve_bounded_copy_contract();
bool semantic_aliased_composite_bounds_preserve_pixel_centers();
bool semantic_scene_builder_shares_glyph_segments_across_raster_sizes();
bool semantic_scene_builder_records_native_shaped_runs();
bool semantic_scene_builder_records_color_bitmap_glyphs();
bool semantic_scene_builder_records_layers_masks_and_effects();
bool semantic_scene_builder_preserves_stable_resource_identities();
bool semantic_scene_builder_records_retained_3d_families();
bool semantic_scene_builder_records_retained_hit_test_index();
bool semantic_scene_content_hashes_isolate_image_updates();

} // namespace progpu::native::tests

#endif
