#include "progpu_native_edit_word_boundaries.hpp"
#include "progpu_native_text.hpp"
#include "progpu_native_edit_item_policy.hpp"
#include "progpu_native_edit_item_data.generated.hpp"

#include <algorithm>
#include <array>
#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

namespace {
using namespace progpu::native::text;

void require(bool condition, const char* message)
{
    if (!condition) throw std::runtime_error(message);
}

std::vector<std::uint16_t> units(std::u16string_view text)
{
    return {text.begin(), text.end()};
}

void check(std::u16string_view text, std::initializer_list<std::uint32_t> expected,
    std::uint32_t leading = 0U, std::int8_t paragraph_level = 0)
{
    const auto original = units(text);
    edit_word_boundary_snapshot actual{{73U, 91U}, 73U};
    edit_word_boundary_error error{};
    if (!try_create_edit_word_boundary_snapshot(original, actual, error, paragraph_level)) {
        std::cerr << "source length " << text.size() << "; error " <<
            static_cast<std::uint32_t>(error) << '\n';
        throw std::runtime_error("EDIT profile unexpectedly failed");
    }
    if (actual.positions != std::vector<std::uint32_t>(expected)) {
        std::cerr << "source length " << text.size() << "; actual boundaries:";
        for (const auto position : actual.positions) std::cerr << ' ' << position;
        std::cerr << "; source UTF16:";
        for (const auto unit : original) std::cerr << ' ' << unit;
        std::cerr << '\n';
        throw std::runtime_error("Original EDIT boundary inventory differs");
    }
    require(actual.leading_content_start == leading, "Original leading-content seam differs");
    require(error == edit_word_boundary_error::none, "Success left an error");
    require(original == units(text), "Classifier rewrote original UTF-16");
}

void original_reference_inventories()
{
    // Literal original UTF-16 inventories, originally observed from Microsoft
    // EDIT, not generated by this worker, ICU, modern UAX29 or source shaping.
    // The original20 + four dictionary-script requests remain separately named.
    check(u"  alpha  beta  ", {0, 2, 9, 15}, 2); // spaces
    check(u"alpha,beta.gamma! (tail) - end ", {0, 18, 25, 27, 31});
    check(u"one\t\ttwo \tthree ", {0, 5, 9, 10, 16}); // tabs single
    check(u"one\t\ttwo \tthree ", {0, 5, 9, 10, 16}); // tabs multiline
    check(u"alpha\r\nbeta\r\n\r\ngamma ", {0, 5, 7, 11, 13, 15, 21});
    check(u"alpha\r\nbeta\r\n\r\ngamma ", {0, 5, 7, 11, 13, 15, 21});
    check(u"go A\U0001F600 e\u0301 fin ", {0, 3, 4, 7, 10, 14});
    check(u"abc \u05D0\u05D1\u05D2, \u0639\u0631\u0628\u0649 end ", {0, 4, 9, 14, 18});
    check(u"abc \u05D0\u05D1\u05D2, \u0639\u0631\u0628\u0649 end ", {0, 4, 9, 14, 18}, 0, 1);
    // Oracle text only: a password source must NEVER call this worker with its
    // source content. Forms already takes SelectAll before provider admission.
    check(u"alpha, beta\tend ", {0, 7, 12, 16});
    check(u"  alpha,beta \ttail ", {0, 2, 13, 14, 19}, 2);
    check(u"alpha beta gamma delta end ", {0, 6, 11, 17, 23, 27});
    check(u"a\u00A0b\u2003c\u202Fd\u3000e ", {0, 4, 6, 8, 10});
    check(u"a\u00A9b\u2603c\U0001F600d ", {0, 5, 7, 9});
    check(u"a\u2603\uFE0Fb\U0001F469\u200D\U0001F4BBc ", {0, 4, 7, 9, 11});
    check(u"ab\rcd\nef ", {0, 2, 3, 6, 9});
    check(u"ab\rcd\nef ", {0, 2, 3, 6, 9});
    // CRCRLF has no available interior EDIT coordinates in the receipt. The
    // atomic group follows the documented EditWordBreakProc CRCRLF contract;
    // this is NOT a newly claimed observed interior coordinate at index3.
    check(u"ab\r\r\ncd ", {0, 2, 5, 8});
    check(u"abcdefghijklmnopqrstuvwxyz0123456789 ", {0, 37});
    check(u"a\U00010400b\U0001D11Ec\U00020000d ", {0, 7, 9, 11});
#if defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    check(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        {0, 4, 7, 11, 15});
    check(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 \u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        {0, 4, 8, 12, 16});
#endif
    check(u"\u0EAA\u0EB0\u0E9A\u0EB2\u0E8D\u0E94\u0EB5\u0EAA\u0EB0\u0E9A\u0EB2\u0E8D\u0E94\u0EB5 ", {0, 15});
    check(u"\u1797\u17B6\u179F\u17B6\u1781\u17D2\u1798\u17C2\u179A\u1797\u17B6\u179F\u17B6\u1781\u17D2\u1798\u17C2\u179A ",
        {0, 18, 19});
}

void missing_contracts_are_atomic()
{
    const auto check_failure = [](std::u16string_view text, edit_word_boundary_error expected,
        std::int8_t level = 0) {
        edit_word_boundary_snapshot snapshot{{17U, 23U, 29U}, 23U};
        const auto original_positions = snapshot.positions;
        edit_word_boundary_error error{};
        if (try_create_edit_word_boundary_snapshot(units(text), snapshot, error, level)) {
            std::cerr << "Unexpected admission; source UTF16:";
            for (const auto unit : units(text)) std::cerr << ' ' << unit;
            std::cerr << '\n';
            throw std::runtime_error("Unknown EDIT policy was silently admitted");
        }
        require(error == expected, "Unknown policy did not preserve its precise diagnostic");
        require(snapshot.positions == original_positions && snapshot.leading_content_start == 23U,
            "Failed classifier published a partial generation");
    };
    // These observed BMP So/rawID domains match neither measured AL nor ID
    // signatures across all three contexts. No guessed range is admitted.
    check_failure(u"a\u3200b ",
        edit_word_boundary_error::unqualified_bmp_symbol_policy);
    check_failure(u"a\u1B61b ",
        edit_word_boundary_error::unqualified_bmp_symbol_policy);
    // An explicit Syriac mark cannot select a nominal item after unrelated
    // Latin or at a standalone edge. Numeric/presentation/supplementary source
    // must not be promoted solely because it has one selected Script value.
    check_failure(u"x\u0711y ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"\u0711y ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"x\u094Dy ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"\u0628\u094Dy ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"\u0628 \u064By ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"\u0301y ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"\u200D\u0301y ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    check_failure(u"\u0628 \u200D\u064By ",
        edit_word_boundary_error::unqualified_script_item_transition_policy);
    for (const auto source : {u"x\u0967y ", u"x\u0E51y ", u"x\u0ED1y ", u"x\u17E1y ",
            u"x\uFB1Dy ", u"x\U0001EE00y ", u"x\u0640y "})
        check_failure(source, edit_word_boundary_error::unqualified_script_item_transition_policy);
    const std::array<char16_t, 1> isolated_surrogate{0xD800U};
    check_failure({isolated_surrogate.data(), isolated_surrogate.size()},
        edit_word_boundary_error::invalid_encoding);
    check_failure(u"\u1000\u1001", edit_word_boundary_error::unqualified_complex_script_policy);
    // All six held-out Myanmar composed contexts remain honestly unsupported,
    // never promoted from two observed letters to a syllable/whole-script rule.
    for (const auto level : {std::int8_t{0}, std::int8_t{1}})
        for (const auto prefix : {u"x", u"\u4E00", u"x "})
            check_failure(std::u16string(prefix) + u"\u1000\u1001y ",
                edit_word_boundary_error::unqualified_complex_script_policy, level);
#if !defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    check_failure(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        edit_word_boundary_error::dependency_unavailable);
    check_failure(u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 \u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ",
        edit_word_boundary_error::dependency_unavailable);
    check_failure(u"x\u0E01\u0E02y ", edit_word_boundary_error::dependency_unavailable, 1);
    for (const auto level : {std::int8_t{0}, std::int8_t{1}})
        for (const auto prefix : {u"\u4E00", u"x "})
            check_failure(std::u16string(prefix) + u"\u0E01\u0E02y ",
                edit_word_boundary_error::dependency_unavailable, level);
#endif
}

void reusable_property_profiles_are_not_observed_scalar_admission()
{
    using profile = detail::edit_item_profile;
    using role = detail::edit_item_source_role;
    const auto scalar_for = [](std::uint32_t cp) {
        return unicode_scalar{cp, 47U, static_cast<std::uint16_t>(cp > 0xFFFFU ? 2U : 1U),
            0U, 0U, get_unicode_script(cp)};
    };
    const auto assert_profile = [&](std::uint32_t cp, profile expected, role expected_role) {
        const auto scalar = scalar_for(cp);
        detail::edit_item_properties actual{};
        const auto admitted = detail::try_classify_edit_item_properties(scalar, actual);
        if (!admitted || actual.profile != expected || actual.role != expected_role ||
            actual.flags != detail::get_edit_profile_flags(expected)) {
            std::cerr << "Property role cp " << cp << "; admitted " << admitted <<
                "; profile " << static_cast<std::uint32_t>(actual.profile) <<
                "; role " << static_cast<std::uint32_t>(actual.role) <<
                "; category " << static_cast<std::uint32_t>(get_unicode_general_category(cp)) <<
                "; bidi " << static_cast<std::uint32_t>(get_unicode_bidi_class(cp)) << '\n';
            throw std::runtime_error("Original Unicode-property role selected the wrong portable policy");
        }
        require(scalar.code_point == cp && scalar.input_index == 47U &&
            scalar.input_length == (cp > 0xFFFFU ? 2U : 1U) && scalar.script == get_unicode_script(cp),
            "Typed policy classification rewrote original source metadata");
    };
    // These are NEW algorithm/domain controls, not unobserved Microsoft EDIT
    // oracle claims. Nominal source extends through original properties rather
    // than a 41-scalar lookup, without making presentation/numeric/mark source
    // nominal or inventing a native Windows engine ID.
    assert_profile(0x062CU, profile::arabic_nominal, role::ordinary);
    assert_profile(0x0621U, profile::arabic_nominal, role::ordinary); // nonjoining nominal letter
    assert_profile(0x05D3U, profile::hebrew_nominal, role::ordinary);
    assert_profile(0x0939U, profile::devanagari_nominal, role::ordinary);
    assert_profile(0x0713U, profile::syriac_nominal, role::ordinary);
    assert_profile(0x0E03U, profile::thai_nominal, role::ordinary);
    assert_profile(0x0E84U, profile::lao_nominal, role::ordinary);
    assert_profile(0x1782U, profile::khmer_nominal, role::ordinary);
    assert_profile(0x0661U, profile::numeric_bridge, role::ordinary);
    assert_profile(0x0031U, profile::numeric_bridge, role::ordinary);
    assert_profile(0xFE8FU, profile::paragraph_bridge, role::ordinary);
    assert_profile(0xFE91U, profile::paragraph_bridge, role::ordinary);
    assert_profile(0x094DU, profile::devanagari_nominal, role::context_mark);
    assert_profile(0x0711U, profile::syriac_nominal, role::context_mark);
    assert_profile(0x0301U, profile::paragraph_bridge, role::inherited_mark);
    assert_profile(0x200DU, profile::paragraph_bridge, role::joiner);
    assert_profile(0x0640U, profile::paragraph_bridge, role::shared_cursive_modifier);
    assert_profile(0x202BU, profile::paragraph_bridge, role::format_control);
    for (const auto cp : {0x200DU, 0x202BU, 0x0301U, 0x0020U}) {
        detail::edit_item_properties actual{};
        require(detail::try_classify_edit_item_properties(scalar_for(cp), actual) &&
            !actual.has_attachment_owner, "Unattached source invented a mark/item owner");
    }

    // Original actual-engine observations are evidence-only regression data.
    // The product header does not include this table or call a scalar lookup.
    const auto observed_profile = [](std::uint32_t engine) {
        switch (engine) {
        case 5U: return profile::paragraph_bridge;
        case 24U: return profile::hebrew_nominal;
        case 26U: return profile::arabic_nominal;
        case 27U: return profile::numeric_bridge;
        case 30U: return profile::syriac_nominal;
        case 31U: return profile::thai_nominal;
        case 34U: return profile::devanagari_nominal;
        case 56U: return profile::lao_nominal;
        case 58U: return profile::khmer_nominal;
        default: throw std::runtime_error("Unknown observed native engine in evidence");
        }
    };
    std::size_t observed_count = 0U;
    for (std::size_t offset = 0U; offset < detail::edit_item_property_ranges.size(); offset += 4U) {
        for (auto cp = detail::edit_item_property_ranges[offset];
             cp <= detail::edit_item_property_ranges[offset + 1U]; ++cp) {
            detail::edit_item_properties actual{};
            require(detail::try_classify_edit_item_properties(scalar_for(cp), actual) &&
                actual.profile == observed_profile(detail::edit_item_property_ranges[offset + 2U]) &&
                actual.flags == detail::edit_item_property_ranges[offset + 3U],
                "Property classifier contradicts an original measured scalar role");
            ++observed_count;
        }
    }
    require(observed_count == 41U, "Original observed role inventory changed");

    // Exhaust every BMP nominal-letter member of the seven exact property
    // domains. This checks the reusable rule, not Windows parity for new points.
    struct domain { open_type_tag script; profile family; unicode_bidi_class bidi; };
    constexpr std::array<domain, 7> domains{{
        {open_type_tag::from_chars('a', 'r', 'a', 'b'), profile::arabic_nominal, unicode_bidi_class::arabic_letter},
        {open_type_tag::from_chars('s', 'y', 'r', 'c'), profile::syriac_nominal, unicode_bidi_class::arabic_letter},
        {open_type_tag::from_chars('h', 'e', 'b', 'r'), profile::hebrew_nominal, unicode_bidi_class::right_to_left},
        {open_type_tag::from_chars('d', 'e', 'v', 'a'), profile::devanagari_nominal, unicode_bidi_class::left_to_right},
        {open_type_tag::from_chars('t', 'h', 'a', 'i'), profile::thai_nominal, unicode_bidi_class::left_to_right},
        {open_type_tag::from_chars('l', 'a', 'o', ' '), profile::lao_nominal, unicode_bidi_class::left_to_right},
        {open_type_tag::from_chars('k', 'h', 'm', 'r'), profile::khmer_nominal, unicode_bidi_class::left_to_right}
    }};
    std::array<std::uint32_t, domains.size()> counts{};
    for (std::uint32_t cp = 0U; cp <= 0xFFFFU; ++cp) {
        const auto category = get_unicode_general_category(cp);
        if (category < unicode_general_category::uppercase_letter ||
            category > unicode_general_category::other_letter) continue;
        const auto scalar = scalar_for(cp);
        for (std::size_t index = 0U; index < domains.size(); ++index) {
            if (scalar.script != domains[index].script || get_unicode_bidi_class(cp) != domains[index].bidi) continue;
            if ((cp >= 0xFB00U && cp <= 0xFB4FU) || detail::is_arabic_presentation_block(cp)) continue;
            detail::edit_item_properties actual{};
            require(detail::try_classify_edit_item_properties(scalar, actual) &&
                actual.profile == domains[index].family && actual.role == role::ordinary &&
                actual.flags == detail::get_edit_profile_flags(domains[index].family),
                "An unobserved nominal BMP property member still requires a scalar allowlist");
            ++counts[index];
        }
    }
    std::cout << "Nominal BMP property-domain counts:";
    for (const auto count : counts) {
        require(count > 20U, "Nominal property family did not extend beyond its observed scalars");
        std::cout << ' ' << count;
    }
    std::cout << '\n';
    for (const auto cp : {0x0967U, 0x0E51U, 0x0ED1U, 0x17E1U, 0xFB1DU, 0x1EE00U}) {
        detail::edit_item_properties actual{profile::khmer_nominal, 73U, role::hard_control};
        require(!detail::try_classify_edit_item_properties(scalar_for(cp), actual) &&
            actual.profile == profile::khmer_nominal && actual.flags == 73U && actual.role == role::hard_control,
            "Unqualified property classification partially published or promoted source");
    }
    for (const auto level : {std::int8_t{0}, std::int8_t{1}}) {
        check(u"x\u062C\u0621y ", {0, 1, 5}, 0, level);
        check(u"\u4E00\u05D3\u05D4y ", {0, 5}, 0, level);
        check(u"\u4E00\u0939\u093Ey ", {0, 5}, 0, level);
        check(u"x\u0713\u0711y ", {0, 1, 5}, 0, level);
        check(u"x\u0E84\u0E87y ", {0, 1, 5}, 0, level);
        check(u"x\u1782\u1783 ", {0, 3, 4}, 0, level);
        check(u"x\u062C\u0640\u0621y ", {0, 1, 6}, 0, level);
    }
}

void independently_observed_joiner_contexts()
{
    // Literal ScriptStringAnalyse opportunities AND actual EDIT gestures from
    // Server2025 Build36862800693. This is separate from the Win11 original24
    // receipt; no modern grapheme boundary is substituted for its UTF-16 seam.
    check(u"xaby ", {0, 5});
    check(u"xa\u200Dby ", {0, 6});
    check(u"xa\u200Cby ", {0, 6});
    check(u"x\u0628\u062Ay ", {0, 1, 5});
    check(u"x\u0628\u200D\u062Ay ", {0, 1, 6});
    check(u"x\u0628\u200C\u062Ay ", {0, 1, 6});
    check(u"x\u0915\u094D\u0937y ", {0, 6});
    check(u"x\u0915\u094D\u200D\u0937y ", {0, 7});
    check(u"x\u0915\u094D\u200C\u0937y ", {0, 7});
    check(u"x\U0001F469\U0001F4BBy ", {0, 1, 3, 5, 7});
    check(u"x\U0001F469\u200D\U0001F4BBy ", {0, 1, 4, 6, 8});
    check(u"x\U0001F469\u200C\U0001F4BBy ", {0, 1, 4, 6, 8});
    check(u"x\U00010400\U00010401y ", {0, 7});
    check(u"x\U00010400\u200D\U00010401y ", {0, 8});
    check(u"x\U00010400\u200C\U00010401y ", {0, 8});
    check(u"x\U00020000\U00020001y ", {0, 1, 3, 5, 7});
    check(u"x\U00020000\u200D\U00020001y ", {0, 1, 4, 6, 8});
    check(u"x\U00020000\u200C\U00020001y ", {0, 1, 4, 6, 8});
    check(u"\u200Da\U0001F600b ", {0, 2, 4, 6});
    check(u"a\U0001F600\u200D ", {0, 1, 5});
    check(u"a \u200Db ", {0, 2, 5});
    check(u"a\U0001F469\u200D\u200D\U0001F4BBb ", {0, 1, 5, 7, 9});
    check(u"x\u2764\uFE0F\U0001F4BBy ", {0, 3, 5, 7});
    check(u"x\u2764\uFE0F\u200D\U0001F4BBy ", {0, 4, 6, 8});
    check(u"x\u2764\uFE0F\u200C\U0001F4BBy ", {0, 4, 6, 8});
    check(u"x\u2603\u2764y ", {0, 5});
    check(u"x\u2603\u200D\u2764y ", {0, 6});
    check(u"x\u2603\u200C\u2764y ", {0, 6});

    // A non-BMP emoji profile boundary remains INSIDE the original modern
    // emoji grapheme. Default UAX14 must continue prohibiting that same seam.
    const auto original = units(u"x\U0001F469\u200D\U0001F4BBy ");
    std::vector<unicode_scalar> scalars(6U);
    std::uint32_t written = 0U;
    require(try_decode_utf16(original, scalars, written) && written == scalars.size(),
        "Joiner source decode failed");
    std::vector<unicode_line_break_class> classes(scalars.size());
    std::vector<text_line_break_kind> breaks(scalars.size());
    require(try_resolve_unicode_line_breaks(scalars, classes, breaks),
        "Default joiner UAX14 failed");
    require(breaks[2] == text_line_break_kind::prohibited,
        "EDIT joiner profile changed the original UAX14 LB8a contract");
    require(get_unicode_line_break_class(0x200DU) ==
        unicode_line_break_class::zero_width_joiner,
        "EDIT joiner profile rewrote the original Unicode property");
}

void independently_heldout_composed_item_seams()
{
    // These RTL observations and the CJK/space/RTL script-entry observations
    // are not consumed by the item-property generator. The LTR Arabic-prefix
    // and LTR Latin-entry cases train mappings and are regression controls,
    // not independent evidence for those mappings.
    constexpr std::array<std::u16string_view, 18> prefixes{
        u"x", u"\u03B1", u"\u05D0", u"\u4E00", u"1", u"x,", u"x.", u"x-",
        u"x ", u"x\u00A0", u"x\t", u"x\u200D", u"x\u200C", u"x\u0301",
        u"x\u064E", u"x\uFE8F", u"x\u0661", u"x\u202B"};
    for (const auto prefix : prefixes) {
        const auto source = std::u16string(prefix) + u"\u0628\u062Ay ";
        if (prefix.size() == 1U) check(source, {0, 1, 5}, 0, 1);
        else check(source, {0, 2, 6}, 0, 1);
    }
    struct observed_script { std::u16string_view source; bool entry_soft; };
    constexpr std::array<observed_script, 6> scripts{{
        {u"\u0E81\u0E82", true}, {u"\u1780\u1781", false},
        {u"\u0710\u0712", true}, {u"\u0915\u0937", false},
        {u"\u05D0\u05D1", false}, {u"\u0628\u062A", true}
    }};
    for (const auto& script : scripts) {
        const auto latin = std::u16string(u"x") + std::u16string(script.source) + u"y ";
        const auto cjk = std::u16string(u"\u4E00") + std::u16string(script.source) + u"y ";
        const auto space = std::u16string(u"x ") + std::u16string(script.source) + u"y ";
        if (script.entry_soft) check(latin, {0, 1, 5}, 0, 1);
        else check(latin, {0, 5}, 0, 1);
        for (const auto level : {std::int8_t{0}, std::int8_t{1}}) {
            if (script.entry_soft) check(cjk, {0, 1, 5}, 0, level);
            else check(cjk, {0, 5}, 0, level);
            check(space, {0, 2, 6}, 0, level);
        }
    }
#if defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    check(u"x\u0E01\u0E02y ", {0, 1, 5}, 0, 1);
    for (const auto level : {std::int8_t{0}, std::int8_t{1}}) {
        check(u"\u4E00\u0E01\u0E02y ", {0, 1, 5}, 0, level);
        check(u"x \u0E01\u0E02y ", {0, 2, 6}, 0, level);
    }
#endif
    for (const auto level : {std::int8_t{-1}, std::int8_t{2}}) {
        edit_word_boundary_snapshot snapshot{{17U, 23U}, 17U};
        edit_word_boundary_error error{};
        require(!try_create_edit_word_boundary_snapshot(units(u"alpha "), snapshot, error, level) &&
            error == edit_word_boundary_error::invalid_paragraph_level &&
            snapshot.positions == std::vector<std::uint32_t>{17U, 23U} &&
            snapshot.leading_content_start == 17U,
            "Invalid source paragraph direction published a partial snapshot");
    }
}

void independent_heldout_symbol_items()
{
    // Literal independent same-item observations from item-contexts.json in
    // Build36867054042. The generated property data reads ONLY the separate
    // symbol-attributes.json three-context inventory, never these requests.
    struct observed_symbol { char16_t value; bool interior_soft_break; };
    constexpr std::array<observed_symbol, 22> observed{{
        {0x00A9U, false}, {0x00AEU, false}, {0x2122U, false}, {0x2194U, false},
        {0x2300U, false}, {0x231AU, true}, {0x23F0U, true}, {0x25FDU, false},
        {0x2600U, false}, {0x2603U, false}, {0x260EU, false}, {0x2615U, true},
        {0x263AU, true}, {0x2640U, false}, {0x2665U, false}, {0x2695U, false},
        {0x26A1U, false}, {0x26BDU, true}, {0x2708U, false}, {0x2764U, false},
        {0x3030U, true}, {0x3299U, true}
    }};
    for (const auto& symbol : observed) {
        const std::array<char16_t, 3> repeated{symbol.value, symbol.value, u' '};
        const std::array<char16_t, 5> variation{
            symbol.value, 0xFE0FU, symbol.value, 0xFE0FU, u' '};
        if (symbol.interior_soft_break) {
            check({repeated.data(), repeated.size()}, {0, 1, 3});
            check({variation.data(), variation.size()}, {0, 2, 5});
        } else {
            check({repeated.data(), repeated.size()}, {0, 3});
            check({variation.data(), variation.size()}, {0, 5});
        }
        // These original72 Latin/VS16 contexts train the item property source
        // and are regression controls, NOT independent mapping qualification.
        const std::array<char16_t, 4> latin{u'a', symbol.value, u'b', u' '};
        const std::array<char16_t, 5> latin_variation{u'a', symbol.value, 0xFE0FU, u'b', u' '};
        if (symbol.interior_soft_break) {
            check({latin.data(), latin.size()}, {0, 1, 2, 4});
            check({latin_variation.data(), latin_variation.size()}, {0, 1, 3, 5});
        } else {
            check({latin.data(), latin.size()}, {0, 4});
            check({latin_variation.data(), latin_variation.size()}, {0, 5});
        }
    }
    // The measured EDIT property never changes the public Unicode17 class or
    // the ordinary line worker; modern snowman remains raw ID in that worker.
    const auto original = units(u"a\u2603b");
    std::array<unicode_scalar, 3> scalars{};
    std::uint32_t written = 0U;
    require(try_decode_utf16(original, scalars, written) && written == 3U,
        "Heldout symbol source decode failed");
    std::array<unicode_line_break_class, 3> classes{};
    std::array<text_line_break_kind, 3> breaks{};
    require(try_resolve_unicode_line_breaks(scalars, classes, breaks),
        "Default symbol UAX14 failed");
    require(get_unicode_line_break_class(0x2603U) == unicode_line_break_class::ideographic &&
        classes[1] == unicode_line_break_class::ideographic &&
        breaks[0] != text_line_break_kind::prohibited &&
        breaks[1] != text_line_break_kind::prohibited,
        "Measured EDIT symbol profile changed the original Unicode17 worker");
}

void concurrent_snapshots_own_independent_outputs()
{
#if defined(PROGPU_NATIVE_EDIT_WORD_ICU)
    constexpr std::u16string_view text =
        u"\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22\u0E20\u0E32\u0E29\u0E32\u0E44\u0E17\u0E22 ";
    const std::vector<std::uint32_t> expected{0U, 4U, 7U, 11U, 15U};
#else
    constexpr std::u16string_view text = u"  alpha  beta  ";
    const std::vector<std::uint32_t> expected{0U, 2U, 9U, 15U};
#endif
    std::array<edit_word_boundary_snapshot, 8> snapshots{};
    std::array<bool, 8> success{};
    std::array<std::thread, 8> workers;
    for (std::size_t index = 0U; index < workers.size(); ++index)
        workers[index] = std::thread([&, index] {
            auto original = units(text);
            edit_word_boundary_error error{};
            success[index] = try_create_edit_word_boundary_snapshot(original, snapshots[index], error);
            std::fill(original.begin(), original.end(), static_cast<std::uint16_t>('X'));
        });
    for (auto& worker : workers) worker.join();
    for (std::size_t index = 0U; index < snapshots.size(); ++index) {
        require(success[index] && snapshots[index].positions == expected,
            "Concurrent original-source snapshot lost its owned generation");
        for (std::size_t other = 0U; other < index; ++other)
            require(snapshots[index].positions.data() != snapshots[other].positions.data(),
                "Independent snapshots borrow a mutable cached output");
    }
    snapshots[0].positions.clear();
    require(snapshots[1].positions == expected, "Retiring one output mutated another");
}

void original_units_and_default_worker_are_independent()
{
    check(u"", {0});
    check(u"   ", {0, 3}, 3);
    check(u"\talpha ", {0, 1, 7}); // TAB is not fWhiteSpace / leading skipped content.
    check(u"\u202Falpha ", {0, 1, 7}, 1);
    check(u"\u00A0alpha ", {0, 7});
    // The UAX14 worker still prohibits a break through GL / NNBSP; EDIT's
    // explicit whitespace seam must not mutate its Unicode17 property table.
    const auto original = units(u"a\u202Fb");
    std::array<unicode_scalar, 3> scalars{};
    std::uint32_t written = 0U;
    require(try_decode_utf16(original, scalars, written) && written == 3U, "Decode failed");
    std::array<unicode_line_break_class, 3> classes{};
    std::array<text_line_break_kind, 3> breaks{};
    require(try_resolve_unicode_line_breaks(scalars, classes, breaks), "UAX14 failed");
    require(breaks[0] == text_line_break_kind::prohibited &&
        breaks[1] == text_line_break_kind::prohibited, "EDIT changed default UAX14");
}
} // namespace

int main()
{
    try {
        concurrent_snapshots_own_independent_outputs();
        original_reference_inventories();
        missing_contracts_are_atomic();
        reusable_property_profiles_are_not_observed_scalar_admission();
        independently_observed_joiner_contexts();
        independent_heldout_symbol_items();
        independently_heldout_composed_item_seams();
        original_units_and_default_worker_are_independent();
        std::cout << "EDIT boundary profile controls passed; ordinary provider admission remains closed\n";
        return 0;
    } catch (const std::exception& failure) {
        std::cerr << failure.what() << '\n';
        return 1;
    }
}
