<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ProGPU.Backend\ProGPU.Backend.csproj" />
    <ProjectReference Include="..\..\src\ProGPU.Scene\ProGPU.Scene.csproj" />
    <ProjectReference Include="..\..\src\SkiaSharp\SkiaSharp.csproj" />
  </ItemGroup>
</Project>
