using System.Globalization;
using System.Runtime.InteropServices;
using ProGPU.Backend;
using ProGPU.Backend.Dawn;
using ProGPU.Media.Audio;
using ProGPU.Media.Editing;
using ProGPU.Media.Effects;
using Silk.NET.WebGPU;

namespace ProGPU.Windows.Media;

/// <summary>
/// Precise native Media Foundation transcode lane. Identity video is decoded
/// to NV12 DXGI-backed samples and submitted directly to the H.264 sink
/// writer. Built-in saturation/grayscale uses a bounded D3D11/Dawn keyed-
/// mutex ring and one fused WebGPU pass. Audio is decoded to PCM and encoded
/// by the native AAC transform. Solid-color clips are generated by WebGPU on
/// the same bounded ring and emit explicit Media Foundation audio gaps.
/// Unsupported composition work is rejected rather than silently lost.
/// For C clips containing V video and A audio samples in total, export is
/// O(C + V + A) time and O(1) managed working storage beyond bounded native
/// codec queues. The steady sample loop allocates no managed objects. Video
/// ownership remains in Media Foundation/DXGI; PCM audio remains in native
/// Media Foundation buffers and is never copied into managed memory.
/// </summary>
public sealed class WindowsMediaFoundationCompositionExportProvider :
    IMediaCompositionExportProvider,
    IMediaCompositionExportCapabilityProvider
{
    private const uint MaximumDimension = 16_384;
    private const string ProviderId =
        "progpu.windows.mediafoundation.export";
    private readonly MediaEffectRegistry _effects;

    public WindowsMediaFoundationCompositionExportProvider(
        int priority = 100,
        MediaEffectRegistry? effects = null)
    {
        Priority = priority;
        _effects = effects ?? MediaEffectRegistry.Default;
    }

    public string Id => ProviderId;

    public int Priority { get; }

    public bool CanRender(
        MediaCompositionExportRequest request) =>
        IsRequestSupported(
            request,
            OperatingSystem.IsWindows(),
            _effects) &&
        (!HasGpuComposition(request) ||
         TryGetActiveD3D12DawnContext(out _));

    internal static bool IsRequestSupported(
        MediaCompositionExportRequest request,
        bool isWindows) =>
        IsRequestSupported(
            request,
            isWindows,
            MediaEffectRegistry.Default);

    internal static bool IsRequestSupported(
        MediaCompositionExportRequest request,
        bool isWindows,
        MediaEffectRegistry effects)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(effects);
        MediaCompositionEncodingProfile profile =
            request.EncodingProfile;
        if (!isWindows ||
            string.IsNullOrWhiteSpace(request.DestinationPath) ||
            request.TrimmingMode !=
                MediaCompositionTrimmingMode.Precise ||
            request.Clips.Count == 0 ||
            request.BackgroundAudioTracks.Count != 0 ||
            request.OverlayLayers.Count != 0 ||
            !string.Equals(
                profile.ContainerSubtype,
                "MPEG4",
                StringComparison.OrdinalIgnoreCase) ||
            !string.Equals(
                profile.VideoSubtype,
                "H264",
                StringComparison.OrdinalIgnoreCase) ||
            profile.AudioSubtype is not null &&
            !string.Equals(
                profile.AudioSubtype,
                "AAC",
                StringComparison.OrdinalIgnoreCase) ||
            profile.Width is 0 or > MaximumDimension ||
            profile.Height is 0 or > MaximumDimension ||
            profile.VideoBitrate == 0 ||
            profile.FrameRateNumerator == 0 ||
            profile.FrameRateDenominator == 0 ||
            (ulong)profile.FrameRateNumerator >
                (ulong)TimeSpan.TicksPerSecond *
                profile.FrameRateDenominator ||
            profile.AudioSubtype is not null &&
            !IsSupportedAacProfile(profile))
        {
            return false;
        }

        for (int index = 0;
             index < request.Clips.Count;
             index++)
        {
            MediaCompositionExportClip clip =
                request.Clips[index];
            bool hasSource =
                clip.SourceUri is
                    { IsAbsoluteUri: true };
            bool hasColor =
                clip.ArgbColor.HasValue;
            if (hasSource == hasColor ||
                !double.IsFinite(clip.Volume) ||
                clip.Volume is < 0d or > 1d ||
                !TryGetEffectiveAudioGain(
                    clip,
                    effects,
                    out _) ||
                clip.VideoEffectDefinitions.Count != 0 ||
                !TryGetBuiltInEffects(
                    clip.UserData,
                    out _,
                    out _) ||
                clip.OriginalDuration <= TimeSpan.Zero ||
                clip.TrimTimeFromStart < TimeSpan.Zero ||
                clip.TrimTimeFromEnd < TimeSpan.Zero ||
                clip.TrimTimeFromStart +
                    clip.TrimTimeFromEnd >=
                    clip.OriginalDuration)
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsSupportedAacProfile(
        MediaCompositionEncodingProfile profile) =>
        profile.AudioChannelCount is 1 or 2 &&
        profile.AudioSampleRate is 44_100 or 48_000 &&
        profile.AudioBitrate is
            96_000 or
            128_000 or
            160_000 or
            192_000;

    public MediaCompositionExportCapabilities GetCapabilities(
        MediaCompositionExportRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (!CanRender(request))
        {
            throw new ArgumentException(
                "The request is not supported by this provider.",
                nameof(request));
        }

        return CreateCapabilities(request);
    }

    internal static MediaCompositionExportCapabilities
        CreateCapabilities(
        MediaCompositionExportRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        bool effects = HasBuiltInEffects(request);
        bool gpuComposition =
            HasGpuComposition(request);
        return new MediaCompositionExportCapabilities(
            ProviderId,
            gpuComposition
                ? MediaCompositionExportVideoPath.GpuCopy
                : MediaCompositionExportVideoPath.NativeGpuSurface,
            request.EncodingProfile.AudioSubtype is null
                ? MediaCompositionExportAudioPath.None
                : MediaCompositionExportAudioPath.NativeBuffer,
            HardwareVideoEncoderRequested: true,
            HardwareVideoEncoderGuaranteed: false,
            EffectsBakedOnGpu: effects,
            Limitation:
                "Media Foundation negotiates the installed H.264 encoder " +
                "at runtime. Saturation and grayscale are fused into a " +
                "bounded zero-readback WebGPU lane. Solid-color clips are " +
                "generated by WebGPU and use tracked DXGI targets. Per-clip " +
                "volume and registered typed gain definitions are combined " +
                "and applied in-place to native PCM16 buffers. Overlays, " +
                "non-gain effects and audio mixing are not yet accepted. " +
                "The native PCM16 gain lane supports 0–2× with saturation.");
    }

    public ValueTask<MediaCompositionExportFailure>
        RenderAsync(
        MediaCompositionExportRequest request,
        IProgress<double>? progress,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        cancellationToken.ThrowIfCancellationRequested();
        if (!CanRender(request))
        {
            return ValueTask.FromResult(
                MediaCompositionExportFailure.InvalidProfile);
        }
        if (!TryCaptureAudioGains(
                request,
                _effects,
                out double[] audioGains))
        {
            return ValueTask.FromResult(
                MediaCompositionExportFailure.InvalidProfile);
        }

        return new ValueTask<MediaCompositionExportFailure>(
            Task.Run(
                () => RenderCore(
                    request,
                    audioGains,
                    progress,
                    cancellationToken),
                CancellationToken.None));
    }

    private static MediaCompositionExportFailure
        RenderCore(
        MediaCompositionExportRequest request,
        IReadOnlyList<double> audioGains,
        IProgress<double>? progress,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        string destinationPath =
            Path.GetFullPath(request.DestinationPath);
        string? destinationDirectory =
            Path.GetDirectoryName(destinationPath);
        if (string.IsNullOrEmpty(destinationDirectory))
        {
            return MediaCompositionExportFailure.InvalidProfile;
        }

        Directory.CreateDirectory(destinationDirectory);
        string temporaryPath = Path.Combine(
            destinationDirectory,
            $".{Path.GetFileNameWithoutExtension(destinationPath)}." +
            $"{Guid.NewGuid():N}.tmp.mp4");
        var reporter = new ExportProgressReporter(
            progress,
            GetTimelineDuration(request));
        reporter.ReportStart();

        try
        {
            cancellationToken.ThrowIfCancellationRequested();
            MediaCompositionExportFailure result =
                RenderNative(
                    request,
                    audioGains,
                    temporaryPath,
                    reporter,
                    cancellationToken);
            if (result != MediaCompositionExportFailure.None)
            {
                TryDeleteTemporaryFile(temporaryPath);
                return result;
            }

            cancellationToken.ThrowIfCancellationRequested();
            File.Move(
                temporaryPath,
                destinationPath,
                overwrite: true);
            reporter.ReportComplete();
            return MediaCompositionExportFailure.None;
        }
        catch (OperationCanceledException)
            when (cancellationToken.IsCancellationRequested)
        {
            TryDeleteTemporaryFile(temporaryPath);
            throw;
        }
        catch (COMException)
        {
            TryDeleteTemporaryFile(temporaryPath);
            return MediaCompositionExportFailure.CodecNotFound;
        }
        catch
        {
            TryDeleteTemporaryFile(temporaryPath);
            return MediaCompositionExportFailure.Unknown;
        }
    }

    private static MediaCompositionExportFailure
        RenderNative(
        MediaCompositionExportRequest request,
        IReadOnlyList<double> audioGains,
        string temporaryPath,
        ExportProgressReporter reporter,
        CancellationToken cancellationToken)
    {
        bool comInitialized = false;
        bool mediaFoundationStarted = false;
        nint d3dDevice = 0;
        nint d3dContext = 0;
        nint dxgiManager = 0;
        nint sinkWriter = 0;
        nint videoOutputType = 0;
        nint videoInputType = 0;
        nint audioOutputType = 0;
        nint audioInputType = 0;
        WindowsDxgiGpuEffectFrameSink? effectSink = null;

        try
        {
            WindowsMediaNative.InitializeCom();
            comInitialized = true;
            WindowsMediaNative.StartupMediaFoundation();
            mediaFoundationStarted = true;

            d3dDevice =
                WindowsMediaNative.CreateD3D11Device(
                    out d3dContext);
            dxgiManager =
                WindowsMediaNative.CreateDxgiDeviceManager(
                    d3dDevice);
            sinkWriter =
                WindowsMediaNative.CreateTranscodeSinkWriter(
                    temporaryPath,
                    dxgiManager);

            MediaCompositionEncodingProfile profile =
                request.EncodingProfile;
            bool gpuComposition =
                HasGpuComposition(request);
            DawnGpuContext? dawn = null;
            if (gpuComposition &&
                !TryGetActiveD3D12DawnContext(
                    out dawn))
            {
                throw new NotSupportedException(
                    "The WebGPU composition lane requires the active Dawn D3D12 device.");
            }
            videoOutputType =
                WindowsMediaNative.CreateH264VideoType(
                    profile.Width,
                    profile.Height,
                    profile.VideoBitrate,
                    profile.FrameRateNumerator,
                    profile.FrameRateDenominator);
            videoInputType = gpuComposition
                ? WindowsMediaNative.CreateArgb32VideoType(
                    profile.Width,
                    profile.Height,
                    profile.FrameRateNumerator,
                    profile.FrameRateDenominator)
                : WindowsMediaNative.CreateNv12VideoType(
                    profile.Width,
                    profile.Height,
                    profile.FrameRateNumerator,
                    profile.FrameRateDenominator);
            uint videoStream =
                WindowsMediaNative.AddSinkWriterStream(
                    sinkWriter,
                    videoOutputType);
            WindowsMediaNative.SetSinkWriterInputType(
                sinkWriter,
                videoStream,
                videoInputType);

            uint? audioStream = null;
            if (profile.AudioSubtype is not null)
            {
                audioOutputType =
                    WindowsMediaNative.CreateAacAudioType(
                        profile.AudioChannelCount,
                        profile.AudioSampleRate,
                        profile.AudioBitrate);
                audioInputType =
                    WindowsMediaNative.CreatePcmAudioType(
                        profile.AudioChannelCount,
                        profile.AudioSampleRate);
                audioStream =
                    WindowsMediaNative.AddSinkWriterStream(
                        sinkWriter,
                        audioOutputType);
                WindowsMediaNative.SetSinkWriterInputType(
                    sinkWriter,
                    audioStream.Value,
                    audioInputType);
            }

            WindowsMediaNative.BeginSinkWriter(sinkWriter);
            if (gpuComposition)
            {
                effectSink =
                    new WindowsDxgiGpuEffectFrameSink(
                        dawn!,
                        d3dDevice,
                        d3dContext,
                        profile.Width,
                        profile.Height);
            }

            long timelineOffset = 0;
            bool audioDiscontinuityPending = false;
            for (int index = 0;
                 index < request.Clips.Count;
                 index++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                MediaCompositionExportClip clip =
                    request.Clips[index];
                long sourceStart =
                    ToMediaTime(clip.TrimTimeFromStart);
                long clipDuration =
                    ToMediaTime(
                        clip.OriginalDuration -
                        clip.TrimTimeFromStart -
                        clip.TrimTimeFromEnd);
                long sourceEnd =
                    checked(sourceStart + clipDuration);
                if (!TryGetBuiltInEffects(
                        clip.UserData,
                        out float saturation,
                        out float grayscale))
                {
                    throw new InvalidOperationException(
                        "Validated built-in effect values became invalid.");
                }

                if (clip.ArgbColor is uint argbColor)
                {
                    RenderColorClip(
                        request.EncodingProfile,
                        sinkWriter,
                        videoStream,
                        audioStream,
                        timelineOffset,
                        clipDuration,
                        argbColor,
                        saturation,
                        grayscale,
                        effectSink!,
                        reporter,
                        cancellationToken);
                    audioDiscontinuityPending =
                        audioStream.HasValue;
                }
                else
                {
                    RenderClip(
                        clip.SourceUri!,
                        request.EncodingProfile,
                        dxgiManager,
                        sinkWriter,
                        videoStream,
                        audioStream,
                        sourceStart,
                        sourceEnd,
                        timelineOffset,
                        saturation,
                        grayscale,
                        audioGains[index],
                        ref audioDiscontinuityPending,
                        effectSink,
                        reporter,
                        cancellationToken);
                }
                timelineOffset =
                    checked(timelineOffset + clipDuration);
            }

            cancellationToken.ThrowIfCancellationRequested();
            WindowsMediaNative.FinalizeSinkWriter(
                sinkWriter);
            return MediaCompositionExportFailure.None;
        }
        finally
        {
            WindowsMediaNative.Release(audioInputType);
            WindowsMediaNative.Release(audioOutputType);
            WindowsMediaNative.Release(videoInputType);
            WindowsMediaNative.Release(videoOutputType);
            WindowsMediaNative.Release(sinkWriter);
            effectSink?.Dispose();
            WindowsMediaNative.Release(dxgiManager);
            WindowsMediaNative.Release(d3dContext);
            WindowsMediaNative.Release(d3dDevice);
            if (mediaFoundationStarted)
            {
                WindowsMediaNative.ShutdownMediaFoundation();
            }
            if (comInitialized)
            {
                WindowsMediaNative.UninitializeCom();
            }
        }
    }

    private static void RenderColorClip(
        MediaCompositionEncodingProfile profile,
        nint sinkWriter,
        uint videoStream,
        uint? audioStream,
        long timelineOffset,
        long clipDuration,
        uint argbColor,
        float saturation,
        float grayscale,
        WindowsDxgiGpuEffectFrameSink effectSink,
        ExportProgressReporter reporter,
        CancellationToken cancellationToken)
    {
        long frameOffset = 0;
        ulong frameRemainder = 0;
        while (frameOffset < clipDuration)
        {
            cancellationToken.ThrowIfCancellationRequested();
            long nextFrameOffset =
                GetNextColorFrameTimestamp(
                    frameOffset,
                    ref frameRemainder,
                    profile.FrameRateNumerator,
                    profile.FrameRateDenominator);
            long frameEnd =
                Math.Min(
                    nextFrameOffset,
                    clipDuration);
            long frameDuration =
                checked(frameEnd - frameOffset);
            long outputTimestamp =
                checked(timelineOffset + frameOffset);
            effectSink.ProcessColorAndWrite(
                argbColor,
                sinkWriter,
                videoStream,
                outputTimestamp,
                frameDuration,
                saturation,
                grayscale,
                cancellationToken);
            reporter.Report(outputTimestamp);
            frameOffset = nextFrameOffset;
        }

        if (audioStream.HasValue)
        {
            SendAudioGap(
                sinkWriter,
                audioStream.Value,
                timelineOffset,
                clipDuration,
                cancellationToken);
        }
    }

    /// <summary>
    /// Advances a rational frame clock without cumulative rounding drift.
    /// </summary>
    /// <remarks>
    /// O(1) time and storage. The carried remainder is always less than the
    /// frame-rate numerator.
    /// </remarks>
    internal static long GetNextColorFrameTimestamp(
        long currentTimestamp,
        ref ulong remainder,
        uint frameRateNumerator,
        uint frameRateDenominator)
    {
        if (currentTimestamp < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(currentTimestamp));
        }
        if (frameRateNumerator == 0 ||
            frameRateDenominator == 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(frameRateNumerator));
        }

        ulong stepNumerator =
            (ulong)TimeSpan.TicksPerSecond *
            frameRateDenominator;
        ulong wholeTicks =
            stepNumerator / frameRateNumerator;
        remainder =
            checked(
                remainder +
                stepNumerator %
                frameRateNumerator);
        ulong carry =
            remainder / frameRateNumerator;
        remainder %=
            frameRateNumerator;
        ulong delta =
            checked(wholeTicks + carry);
        if (delta == 0 ||
            delta > long.MaxValue)
        {
            throw new ArgumentOutOfRangeException(
                nameof(frameRateNumerator),
                "The frame rate must produce at least one 100-nanosecond media tick per frame.");
        }
        return checked(
            currentTimestamp +
            (long)delta);
    }

    private static void SendAudioGap(
        nint sinkWriter,
        uint audioStream,
        long timelineOffset,
        long clipDuration,
        CancellationToken cancellationToken)
    {
        long gapEnd =
            checked(timelineOffset + clipDuration);
        for (long timestamp = timelineOffset;
             timestamp < gapEnd;
             timestamp =
                 checked(
                     timestamp +
                     TimeSpan.TicksPerSecond))
        {
            cancellationToken.ThrowIfCancellationRequested();
            WindowsMediaNative.SendSinkStreamTick(
                sinkWriter,
                audioStream,
                timestamp);
        }
        WindowsMediaNative.SendSinkStreamTick(
            sinkWriter,
            audioStream,
            gapEnd);
    }

    private static void RenderClip(
        Uri sourceUri,
        MediaCompositionEncodingProfile profile,
        nint dxgiManager,
        nint sinkWriter,
        uint videoStream,
        uint? audioStream,
        long sourceStart,
        long sourceEnd,
        long timelineOffset,
        float saturation,
        float grayscale,
        double audioGain,
        ref bool audioDiscontinuityPending,
        WindowsDxgiGpuEffectFrameSink? effectSink,
        ExportProgressReporter reporter,
        CancellationToken cancellationToken)
    {
        nint reader = 0;
        nint videoType = 0;
        nint audioType = 0;
        try
        {
            reader =
                WindowsMediaNative.CreateTranscodeSourceReader(
                    ToSourceUrl(sourceUri),
                    dxgiManager);
            videoType = effectSink is null
                ? WindowsMediaNative.CreateNv12VideoType(
                    profile.Width,
                    profile.Height,
                    profile.FrameRateNumerator,
                    profile.FrameRateDenominator)
                : WindowsMediaNative.CreateArgb32VideoType(
                    profile.Width,
                    profile.Height,
                    profile.FrameRateNumerator,
                    profile.FrameRateDenominator);
            WindowsMediaNative.ConfigureSourceReaderStream(
                reader,
                WindowsMediaNative.FirstVideoStream,
                videoType);

            if (audioStream.HasValue)
            {
                audioType =
                    WindowsMediaNative.CreatePcmAudioType(
                        profile.AudioChannelCount,
                        profile.AudioSampleRate);
                WindowsMediaNative.ConfigureSourceReaderStream(
                    reader,
                    WindowsMediaNative.FirstAudioStream,
                    audioType);
            }

            WindowsMediaNative.SetSourceReaderPosition(
                reader,
                sourceStart);
            bool videoComplete = false;
            bool audioComplete = !audioStream.HasValue;
            bool videoDiscontinuityPending = false;
            while (!videoComplete || !audioComplete)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (!videoComplete)
                {
                    videoComplete = ProcessNextSample(
                        reader,
                        WindowsMediaNative.FirstVideoStream,
                        sinkWriter,
                        videoStream,
                        sourceStart,
                        sourceEnd,
                        timelineOffset,
                        effectSink,
                        saturation,
                        grayscale,
                        1d,
                        ref videoDiscontinuityPending,
                        profile,
                        cancellationToken,
                        reporter);
                }
                if (!audioComplete)
                {
                    audioComplete = ProcessNextSample(
                        reader,
                        WindowsMediaNative.FirstAudioStream,
                        sinkWriter,
                        audioStream!.Value,
                        sourceStart,
                        sourceEnd,
                        timelineOffset,
                        effectSink: null,
                        saturation: 1f,
                        grayscale: 0f,
                        audioGain: audioGain,
                        discontinuityPending:
                            ref audioDiscontinuityPending,
                        profile: profile,
                        cancellationToken: cancellationToken,
                        reporter: reporter);
                }
            }
        }
        finally
        {
            WindowsMediaNative.Release(audioType);
            WindowsMediaNative.Release(videoType);
            WindowsMediaNative.Release(reader);
        }
    }

    private static bool ProcessNextSample(
        nint reader,
        uint sourceStream,
        nint sinkWriter,
        uint sinkStream,
        long sourceStart,
        long sourceEnd,
        long timelineOffset,
        WindowsDxgiGpuEffectFrameSink? effectSink,
        float saturation,
        float grayscale,
        double audioGain,
        ref bool discontinuityPending,
        MediaCompositionEncodingProfile profile,
        CancellationToken cancellationToken,
        ExportProgressReporter reporter)
    {
        nint sample =
            WindowsMediaNative.ReadSourceSample(
                reader,
                sourceStream,
                out uint flags,
                out long timestamp);
        try
        {
            if ((flags &
                 WindowsMediaNative.SourceReaderEndOfStream) !=
                0)
            {
                return true;
            }
            if (timestamp >= sourceEnd)
            {
                return true;
            }
            if (timestamp < sourceStart)
            {
                return false;
            }

            long outputTimestamp =
                checked(
                    timelineOffset +
                    timestamp -
                    sourceStart);
            if (sample != 0)
            {
                if (discontinuityPending)
                {
                    WindowsMediaNative.SetSampleDiscontinuity(
                        sample);
                    discontinuityPending = false;
                }
                long remainingDuration =
                    sourceEnd - timestamp;
                long sampleDuration;
                if (!WindowsMediaNative.TryGetSampleDuration(
                        sample,
                        out sampleDuration) ||
                    sampleDuration <= 0)
                {
                    sampleDuration =
                        Math.Max(
                            1,
                            checked(
                                TimeSpan.TicksPerSecond *
                                (long)profile
                                    .FrameRateDenominator /
                                profile
                                    .FrameRateNumerator));
                }
                sampleDuration =
                    Math.Min(
                        sampleDuration,
                        remainingDuration);
                if (effectSink is null)
                {
                    if (audioGain != 1d)
                    {
                        WindowsMediaNative.ApplyPcm16Gain(
                            sample,
                            audioGain);
                    }
                    WindowsMediaNative.SetSampleDuration(
                        sample,
                        sampleDuration);
                    WindowsMediaNative.SetSampleTime(
                        sample,
                        outputTimestamp);
                    WindowsMediaNative.WriteSinkSample(
                        sinkWriter,
                        sinkStream,
                        sample);
                }
                else
                {
                    effectSink.ProcessAndWrite(
                        sample,
                        sinkWriter,
                        sinkStream,
                        outputTimestamp,
                        sampleDuration,
                        saturation,
                        grayscale,
                        cancellationToken);
                }
                reporter.Report(outputTimestamp);
            }
            else if ((flags &
                      WindowsMediaNative
                          .SourceReaderStreamTick) != 0)
            {
                WindowsMediaNative.SendSinkStreamTick(
                    sinkWriter,
                    sinkStream,
                    outputTimestamp);
            }

            return false;
        }
        finally
        {
            WindowsMediaNative.Release(sample);
        }
    }

    private static long ToMediaTime(TimeSpan value) =>
        value.Ticks;

    private static bool HasBuiltInEffects(
        MediaCompositionExportRequest request)
    {
        for (int index = 0;
             index < request.Clips.Count;
             index++)
        {
            if (!TryGetBuiltInEffects(
                    request.Clips[index].UserData,
                    out float saturation,
                    out float grayscale) ||
                saturation != 1f ||
                grayscale != 0f)
            {
                return true;
            }
        }
        return false;
    }

    private static bool TryCaptureAudioGains(
        MediaCompositionExportRequest request,
        MediaEffectRegistry effects,
        out double[] gains)
    {
        gains = new double[request.Clips.Count];
        for (int index = 0;
             index < request.Clips.Count;
             index++)
        {
            if (!TryGetEffectiveAudioGain(
                    request.Clips[index],
                    effects,
                    out gains[index]))
            {
                gains = [];
                return false;
            }
        }
        return true;
    }

    private static bool TryGetEffectiveAudioGain(
        MediaCompositionExportClip clip,
        MediaEffectRegistry effects,
        out double gain)
    {
        if (!MediaAudioGraphEffectResolver
                .TryCaptureCombinedGain(
                    effects,
                    clip.AudioEffectDefinitions,
                    out double effectGain))
        {
            gain = 0d;
            return false;
        }

        gain = clip.Volume * effectGain;
        return double.IsFinite(gain) &&
               gain is >= 0d and
               <= WindowsPcm16GainProcessor.MaximumGain;
    }

    private static bool HasGpuComposition(
        MediaCompositionExportRequest request)
    {
        if (HasBuiltInEffects(request))
        {
            return true;
        }
        for (int index = 0;
             index < request.Clips.Count;
             index++)
        {
            if (request.Clips[index].ArgbColor.HasValue)
            {
                return true;
            }
        }
        return false;
    }

    private static bool TryGetBuiltInEffects(
        IReadOnlyDictionary<string, string> userData,
        out float saturation,
        out float grayscale)
    {
        saturation = 1f;
        grayscale = 0f;
        if (userData.TryGetValue(
                "progpu.saturation",
                out string? saturationText) &&
            (!float.TryParse(
                saturationText,
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out saturation) ||
             !float.IsFinite(saturation) ||
             saturation is < 0f or > 1f))
        {
            return false;
        }
        if (userData.TryGetValue(
                "progpu.grayscale",
                out string? grayscaleText) &&
            (!float.TryParse(
                grayscaleText,
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out grayscale) ||
             !float.IsFinite(grayscale) ||
             grayscale is < 0f or > 1f))
        {
            return false;
        }
        return true;
    }

    private static bool TryGetActiveD3D12DawnContext(
        out DawnGpuContext? dawn)
    {
        IReadOnlyList<WgpuContext> contexts =
            WgpuContext.ActiveContexts;
        for (int index = 0;
             index < contexts.Count;
             index++)
        {
            if (contexts[index].ExternalTextureImporter is
                    DawnGpuContext candidate &&
                contexts[index].AdapterBackendType ==
                    BackendType.D3D12)
            {
                dawn = candidate;
                return true;
            }
        }
        dawn = null;
        return false;
    }

    private static long GetTimelineDuration(
        MediaCompositionExportRequest request)
    {
        long duration = 0;
        for (int index = 0;
             index < request.Clips.Count;
             index++)
        {
            MediaCompositionExportClip clip =
                request.Clips[index];
            duration = checked(
                duration +
                (clip.OriginalDuration -
                 clip.TrimTimeFromStart -
                 clip.TrimTimeFromEnd).Ticks);
        }
        return Math.Max(1, duration);
    }

    private static string ToSourceUrl(Uri uri) =>
        uri.IsFile
            ? uri.LocalPath
            : uri.AbsoluteUri;

    private static void TryDeleteTemporaryFile(
        string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch
        {
            // Best-effort cleanup must not hide the export result.
        }
    }

    private sealed class ExportProgressReporter
    {
        private readonly IProgress<double>? _progress;
        private readonly long _duration;
        private double _last = -1d;

        public ExportProgressReporter(
            IProgress<double>? progress,
            long duration)
        {
            _progress = progress;
            _duration = duration;
        }

        public void ReportStart() => ReportValue(0d);

        public void Report(long timelinePosition)
        {
            if (_progress is null)
            {
                return;
            }
            double value = Math.Clamp(
                timelinePosition * 100d / _duration,
                0d,
                99.9d);
            if (value - _last >= 0.5d)
            {
                ReportValue(value);
            }
        }

        public void ReportComplete() => ReportValue(100d);

        private void ReportValue(double value)
        {
            _last = value;
            _progress?.Report(value);
        }
    }
}
