namespace HintedTextureSamplingProbe;

// Executes against the real pinned shader components, without creating a device
// or invoking native code. Run with --verify-source-only.
internal static class ShaderSourceControls
{
    internal static int Run()
    {
        int passed = 0;
        foreach (bool paint in new[] { false, true })
        {
            _ = ShaderDiagnostics.VerifySource(paint);
            string[] lfComponents = ShaderDiagnostics.ReadComponents(paint)
                .Select(value => value.Replace("\r\n", "\n", StringComparison.Ordinal)).ToArray();
            string lf = string.Join("\n", lfComponents);
            foreach (bool windows in new[] { false, true })
            {
                string[] components = windows
                    ? lfComponents.Select(value => value.Replace("\n", "\r\n", StringComparison.Ordinal)).ToArray()
                    : lfComponents;
                // The production composer always inserts LF BETWEEN components,
                // even when each checked-out resource internally contains CRLF.
                string original = string.Join("\n", components);
                string exact = ShaderDiagnostics.VerifySource(original, components, paint);
                Check(ReferenceEquals(original, exact), "Verification rewrote the compiled module.");
                Check(ShaderDiagnostics.CanonicalHash(exact) == ShaderDiagnostics.Hash(lf), "Canonical content hash differs.");
                Check((ShaderDiagnostics.Hash(exact) != ShaderDiagnostics.Hash(lf)) == windows,
                    "Exact compiled-source identity did not preserve checkout line endings.");

                foreach (bool sample in new[] { false, true })
                {
                    string instrumented = ShaderDiagnostics.Instrument(exact, paint, sample);
                    string expected = ShaderDiagnostics.Instrument(lf, paint, sample);
                    Check(instrumented.Replace("\r\n", "\n", StringComparison.Ordinal) == expected,
                        "LF/CRLF instrumentation changed shader semantics.");
                    int firstAnchor = exact.IndexOf("fn text_coverage_to_alpha(", StringComparison.Ordinal);
                    Check(instrumented.StartsWith(exact[..firstAnchor], StringComparison.Ordinal),
                        "Instrumentation rewrote untouched vertex or mask source bytes.");
                    int lastFragment = exact.LastIndexOf("@fragment", StringComparison.Ordinal);
                    Check(instrumented.EndsWith(exact[lastFragment..], StringComparison.Ordinal),
                        "Instrumentation rewrote untouched fragment entrypoint bytes.");
                }

                string[] changed = components.Select(value => value.Replace("1.43", "1.44", StringComparison.Ordinal)).ToArray();
                Reject(() => ShaderDiagnostics.VerifySource(string.Join("\n", changed), changed, paint),
                    "Changed production scalar passed the pinned parent check.");
                string[] changedCopy = components.ToArray();
                changedCopy[0] += " ";
                Reject(() => ShaderDiagnostics.VerifySource(original, changedCopy, paint),
                    "Mismatched embedded/copied component bytes were accepted.");
            }
        }
        byte[] originalAtlas = Program.Atlas(17, 11), translatedAtlas = Program.Atlas();
        byte[] originalInstances = Program.Instances(17, 11), translatedInstances = Program.Instances();
        // Bind the unchanged control to the exact original successful Windows
        // receipt, not merely two inputs generated by the same new helper.
        Check(ShaderDiagnostics.Hash(originalAtlas) == "B2DE6F471A7FAE6457CE0D45CB127F244E79C823858F7AA231260BA5150804BC",
            "Original atlas bytes changed from run36877876254.");
        Check(ShaderDiagnostics.Hash(originalInstances) == "4957887C14D95152E1DF12BD708E1E69589404D230F9AAE86A0BC80A6C1C5044",
            "Original positioned instance bytes changed from run36877876254.");
        for (int row = 0; row < 25; row++)
            Check(originalAtlas.AsSpan((11 + row) * 1024 + 17, 23)
                    .SequenceEqual(translatedAtlas.AsSpan((2 + row) * 1024 + 2, 23)),
                "Atlas translation changed relative coverage bytes.");
        Check(originalAtlas.Count(value => value != 0) == translatedAtlas.Count(value => value != 0),
            "Atlas translation left extra coverage outside the translated tile.");
        for (int occurrence = 0; occurrence < 2; occurrence++)
        {
            int start = occurrence * 96;
            Check(originalInstances.AsSpan(start, 40).SequenceEqual(translatedInstances.AsSpan(start, 40)) &&
                originalInstances.AsSpan(start + 56, 40).SequenceEqual(translatedInstances.AsSpan(start + 56, 40)),
                "Atlas translation changed physical geometry, style, opacity or ownership fields.");
            Check(BitConverter.ToSingle(translatedInstances, start + 40) == 2 &&
                BitConverter.ToSingle(translatedInstances, start + 44) == 2 &&
                BitConverter.ToSingle(translatedInstances, start + 48) == 25 &&
                BitConverter.ToSingle(translatedInstances, start + 52) == 27,
                "Translated texture bounds do not match the original23×25 tile at(2,2).");
        }

        byte[] nativeInstances = NativeFrameControl.Instances(), nativeAtlas = NativeFrameControl.Atlas();
        Check(NativeFrameControl.BearingX == -3 && NativeFrameControl.BearingY == -18 &&
            NativeFrameControl.Width == 20 && NativeFrameControl.Height == 22 && NativeFrameControl.Padding == 4,
            "Native frame does not preserve the original producer's floor/ceil and padding arithmetic.");
        // Independently packed from original reference-glyphs.bin, captured
        // outline bounds and the native gpu_glyph_instance writer; not a hash
        // calculated by this C# instance helper, nor a captured GPU buffer.
        Check(ShaderDiagnostics.Hash(nativeInstances) == "7238032D7F006B96C46684366A4009DEA2C06B22A8C106D413BFE5EA49263314",
            "Native-frame instances differ from independently derived original96byte records.");
        Check(ShaderDiagnostics.Hash(Program.PaintBytes(true, 96)) == "2D56BE36B794AE5BBE080FB813F99677732A88329F606BD0000DA58532EDE807",
            "Bounded paint changed from the authentic frame0 receipt.");
        for (int occurrence = 0; occurrence < 2; occurrence++)
        {
            int start = occurrence * 96;
            Check(nativeInstances.AsSpan(start + 8, 16).SequenceEqual(translatedInstances.AsSpan(start + 8, 16)) &&
                nativeInstances.AsSpan(start + 56, 40).SequenceEqual(translatedInstances.AsSpan(start + 56, 40)),
                "Native frame changed basis, original reference color, scale, flags or brush/paint identity.");
            float x = BitConverter.ToSingle(nativeInstances, start) + BitConverter.ToSingle(nativeInstances, start + 24) / 2;
            float y = BitConverter.ToSingle(nativeInstances, start + 4) + BitConverter.ToSingle(nativeInstances, start + 28) / 2;
            Check(x == (occurrence == 0 ? 2.5625f : 2.75f) && y == (occurrence == 0 ? 4.1875f : 4.25f) &&
                x + BitConverter.ToSingle(nativeInstances, start + 32) / 2 == (occurrence == 0 ? 12.5625f : 12.75f) &&
                y + BitConverter.ToSingle(nativeInstances, start + 36) / 2 == (occurrence == 0 ? 15.1875f : 15.25f),
                "Native logical frame differs from original division-by-DPI and writer placement.");
        }
        Check(nativeAtlas.Length == 1024 * 1024 && nativeAtlas.Count(value => value != 0) == 12 * 14,
            "Controlled synthetic interior escaped the native frame's four-texel clear padding.");
        for (int row = 0; row < 22; row++)
        {
            var data = nativeAtlas.AsSpan((2 + row) * 1024 + 2, 20);
            if (row < 4 || row >= 18)
                Check(data.IndexOfAnyExcept((byte)0) < 0, "Native frame vertical padding is not clear.");
            else
                Check(data[..4].IndexOfAnyExcept((byte)0) < 0 && data[16..].IndexOfAnyExcept((byte)0) < 0 &&
                    data.Slice(4, 12).SequenceEqual(translatedAtlas.AsSpan((2 + row) * 1024 + 6, 12)),
                    "Native frame padding or controlled relative coverage formula changed.");
        }
        byte[] uniform96 = Program.UniformBytes(96), uniform128 = Program.UniformBytes(128);
        Check(BitConverter.ToUInt32(uniform96, 0) == 0x3d2aaaab && BitConverter.ToUInt32(uniform96, 20) == 0xbd2aaaab &&
            BitConverter.ToSingle(uniform96, 192) == 48 && BitConverter.ToSingle(uniform96, 200) == 2,
            "Native96px projection no longer matches original float32(2/48) and DPI2.");
        Check(BitConverter.ToSingle(uniform128, 0) == .03125f && BitConverter.ToSingle(uniform128, 20) == -.03125f &&
            BitConverter.ToSingle(uniform128, 192) == 64 && BitConverter.ToSingle(uniform128, 200) == 2,
            "128px projection control changed physical DPI or canvas extent.");
        byte[] certified = Program.UniformBytes(96, canonicalFrame: true);
        Check(BitConverter.ToSingle(certified, 204) == -1 && BitConverter.ToSingle(uniform96, 204) == 0 &&
            certified.AsSpan(0, 204).SequenceEqual(uniform96.AsSpan(0, 204)) &&
            certified.AsSpan(208).SequenceEqual(uniform96.AsSpan(208)),
            "Canonical-frame opt-in changed its exact negative token, defaultgate0, or unrelated uniforms.");
        Check(!(BitConverter.ToSingle(certified, 204) > .5f),
            "Coverage certificate accidentally selected the existing Texture boundedSourcePass policy.");
        byte[] boundedPaint = Program.PaintBytes(true, 96), materialPaint = Program.PaintBytes(false, 96);
        byte[] extendedPaint = boundedPaint.ToArray(), taggedMaterial = materialPaint.ToArray();
        // Original kind/flags bytes, independently exercising both halves of
        // the engine's bounded-texture predicate. These do not render or admit
        // new extended/affine geometry in the existing axis-frame probe.
        extendedPaint[8] &= unchecked((byte)~2);
        taggedMaterial[8] |= 2;
        foreach (string profile in new[] { ShaderDiagnostics.BaselineProfile,
            ShaderDiagnostics.CanonicalFrameProfile, ShaderDiagnostics.AffineCanonicalFrameProfile })
        {
            Check(Program.DrawVertexCount(profile, false, []) == 6,
                "Ordinary Text must retain its original six-vertex quad.");
            Check(Program.DrawVertexCount(profile, true, boundedPaint) ==
                (profile == ShaderDiagnostics.AffineCanonicalFrameProfile ? 12u : 6u),
                "Bounded texture count does not match its exact reviewed shader profile.");
            Check(Program.DrawVertexCount(profile, true, materialPaint) == 6,
                "Registered material gained an extra glyph contribution.");
            Check(Program.DrawVertexCount(profile, true, extendedPaint) == 6,
                "Extended texture gained a bounded image-quad copy.");
            Check(Program.DrawVertexCount(profile, true, taggedMaterial) == 6,
                "Texture flag alone selected a second registered-material quad.");
        }
        Check(!ShaderDiagnostics.HasCanonicalFrame(ShaderDiagnostics.BaselineProfile),
            "Original baseline profile gained canonical-frame admission.");
        Check(ShaderDiagnostics.HasCanonicalFrame(ShaderDiagnostics.CanonicalFrameProfile),
            "Reviewed coverage-frame profile lost its exact canonical capability.");
        Check(ShaderDiagnostics.HasCanonicalFrame(ShaderDiagnostics.AffineCanonicalFrameProfile),
            "Integrated affine paint profile lost its exact canonical capability.");
        Reject(() => Program.DrawVertexCount("unreviewed", true, boundedPaint),
            "Unknown shader profile selected a draw contract.");
        return passed + CanonicalCoverageOracle.RunControls();

        void Check(bool condition, string message)
        {
            if (!condition) throw new InvalidOperationException(message);
            passed++;
        }
        void Reject(Action action, string message)
        {
            try { action(); }
            catch (InvalidOperationException) { passed++; return; }
            throw new InvalidOperationException(message);
        }
    }
}
