<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProGpuUseWindowsBaseShim>true</ProGpuUseWindowsBaseShim>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ProGPU.WinUI/ProGPU.WinUI.csproj" />
    <ProjectReference Include="../ProGPU.WinUI.Themes.Fluent/ProGPU.WinUI.Themes.Fluent.csproj" />
    <ProjectReference Include="../ProGPU.Fonts.Inter/ProGPU.Fonts.Inter.csproj" />
  </ItemGroup>
</Project>
