#!/usr/bin/env python3
"""Generate the pinned Ragel USE syllable state-machine tables for C#."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ARRAYS = (
    ("unsigned char", "trans_keys", "byte"),
    ("char", "key_spans", "byte"),
    ("short", "index_offsets", "ushort"),
    ("unsigned char", "indicies", "byte"),
    ("char", "trans_targs", "byte"),
    ("char", "trans_actions", "byte"),
    ("char", "to_state_actions", "byte"),
    ("char", "from_state_actions", "byte"),
    ("short", "eof_trans", "short"),
)


def parse_array(source: str, c_type: str, suffix: str) -> list[int]:
    match = re.search(
        rf"static const {re.escape(c_type)} _use_syllable_machine_{suffix}\[\]\s*=\s*\{{(?P<body>.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find {suffix}")
    return [int(value) for value in re.findall(r"-?\d+", match.group("body"))]


def format_values(values: list[int]) -> str:
    return "\n".join(
        "        " + ", ".join(str(value) for value in values[index : index + 24]) + ","
        for index in range(0, len(values), 24)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    source_path = args.harfbuzz_root / "src" / "hb-ot-shaper-use-machine.hh"
    source = source_path.read_text(encoding="utf-8")
    declarations = []
    for c_type, suffix, cs_type in ARRAYS:
        values = parse_array(source, c_type, suffix)
        declarations.append(
            f"    private static readonly {cs_type}[] s_{suffix} =\n"
            f"    [\n{format_values(values)}\n    ];"
        )

    generated = f'''// <auto-generated />
// Source: HarfBuzz hb-ot-shaper-use-machine.hh generated from the USE Ragel grammar.
// Regenerate with eng/generate-use-syllable-machine.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class UseSyllableMachineData
{{
{chr(10).join(declarations)}

    public const int StartState = 1;

    public static int GetTransition(int state, byte category)
    {{
        int keyOffset = state << 1;
        int keySpan = s_key_spans[state];
        int relative = keySpan > 0 && category >= s_trans_keys[keyOffset] && category <= s_trans_keys[keyOffset + 1]
            ? category - s_trans_keys[keyOffset]
            : keySpan;
        return s_indicies[s_index_offsets[state] + relative];
    }}

    public static int GetTarget(int transition) => s_trans_targs[transition];
    public static int GetAction(int transition) => s_trans_actions[transition];
    public static int GetToStateAction(int state) => s_to_state_actions[state];
    public static int GetFromStateAction(int state) => s_from_state_actions[state];
    public static int GetEofTransition(int state) => s_eof_trans[state] - 1;
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
