#!/usr/bin/env python3
"""Generate ProGPU's packed Unicode 17 grapheme property source."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


EXPECTED = {
    "grapheme": "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89",
    "emoji": "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b",
    "derived": "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08",
}

GCB_VALUES = {
    "CR": 1,
    "LF": 2,
    "Control": 3,
    "Extend": 4,
    "ZWJ": 5,
    "Regional_Indicator": 6,
    "Prepend": 7,
    "SpacingMark": 8,
    "L": 9,
    "V": 10,
    "T": 11,
    "LV": 12,
    "LVT": 13,
}

INCB_VALUES = {"Consonant": 1, "Extend": 2, "Linker": 3}


def verify(path: Path, expected: str) -> str:
    data = path.read_bytes()
    actual = hashlib.sha256(data).hexdigest()
    if actual != expected:
        raise RuntimeError(f"Unexpected SHA-256 for {path}: {actual}")
    return data.decode("utf-8")


def code_range(raw: str) -> tuple[int, int]:
    values = raw.strip().split("..")
    start = int(values[0], 16)
    return start, int(values[-1], 16)


def parse_gcb(source: str) -> list[tuple[int, int, int]]:
    result: list[tuple[int, int, int]] = []
    for line in source.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        fields = [field.strip() for field in body.split(";")]
        if len(fields) != 2 or fields[1] not in GCB_VALUES:
            continue
        start, end = code_range(fields[0])
        result.append((start, end, GCB_VALUES[fields[1]]))
    return sorted(result)


def parse_extended_pictographic(source: str) -> list[tuple[int, int, int]]:
    result: list[tuple[int, int, int]] = []
    for line in source.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        fields = [field.strip() for field in body.split(";")]
        if len(fields) == 2 and fields[1] == "Extended_Pictographic":
            start, end = code_range(fields[0])
            result.append((start, end, 1))
    return sorted(result)


def parse_incb(source: str) -> list[tuple[int, int, int]]:
    result: list[tuple[int, int, int]] = []
    pattern = re.compile(
        r"^(?P<range>[0-9A-F]+(?:\.\.[0-9A-F]+)?)\s*;\s*InCB\s*;\s*"
        r"(?P<value>Consonant|Extend|Linker)\b"
    )
    for line in source.splitlines():
        match = pattern.match(line)
        if match is None:
            continue
        start, end = code_range(match.group("range"))
        result.append((start, end, INCB_VALUES[match.group("value")]))
    return sorted(result)


def flatten(records: list[tuple[int, int, int]]) -> list[int]:
    return [value for record in records for value in record]


def format_values(values: list[int]) -> str:
    return "\n".join(
        "        " + ", ".join(str(value) for value in values[index:index + 12]) + ","
        for index in range(0, len(values), 12)
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--grapheme", type=Path, required=True)
    parser.add_argument("--emoji", type=Path, required=True)
    parser.add_argument("--derived", type=Path, required=True)
    args = parser.parse_args()
    grapheme = verify(args.grapheme, EXPECTED["grapheme"])
    emoji = verify(args.emoji, EXPECTED["emoji"])
    derived = verify(args.derived, EXPECTED["derived"])
    gcb = flatten(parse_gcb(grapheme))
    pictographic = flatten(parse_extended_pictographic(emoji))
    incb = flatten(parse_incb(derived))
    root = Path(__file__).resolve().parent.parent
    output = root / "src/ProGPU.Text/UnicodeGraphemeData.Generated.cs"
    source = f'''namespace ProGPU.Text;

// <auto-generated />
// Unicode 17.0.0 UAX #29 property data. Generated by
// eng/generate-unicode-grapheme-table.py from the pinned official UCD files.
internal static class UnicodeGraphemeData
{{
    internal static readonly uint[] s_graphemeRanges =
    [
{format_values(gcb)}
    ];

    internal static readonly uint[] s_extendedPictographicRanges =
    [
{format_values(pictographic)}
    ];

    internal static readonly uint[] s_indicConjunctRanges =
    [
{format_values(incb)}
    ];
}}
'''
    output.write_text(source, encoding="utf-8", newline="\n")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
