#!/usr/bin/env python3
"""Generate the USE/Indic invalid-vowel sequence table from HarfBuzz data."""

from __future__ import annotations

import argparse
from pathlib import Path


SCRIPT_RANGES = (
    (0x0900, 0x097F, "deva"),
    (0x0980, 0x09FF, "beng"),
    (0x0A00, 0x0A7F, "guru"),
    (0x0A80, 0x0AFF, "gujr"),
    (0x0B00, 0x0B7F, "orya"),
    (0x0B80, 0x0BFF, "taml"),
    (0x0C00, 0x0C7F, "telu"),
    (0x0C80, 0x0CFF, "knda"),
    (0x0D00, 0x0D7F, "mlym"),
    (0x0D80, 0x0DFF, "sinh"),
    (0x11000, 0x1107F, "brah"),
    (0x11200, 0x1124F, "khoj"),
    (0x112B0, 0x112FF, "sind"),
    (0x11480, 0x114DF, "tirh"),
    (0x11600, 0x1165F, "modi"),
    (0x11680, 0x116CF, "takr"),
)


def script_for(code_point: int) -> str:
    for start, end, script in SCRIPT_RANGES:
        if start <= code_point <= end:
            return script
    raise RuntimeError(f"No script mapping for U+{code_point:04X}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    source_path = args.harfbuzz_root / "src" / "ms-use" / "IndicShapingInvalidCluster.txt"
    constraints: list[tuple[str, int, int, int]] = []
    for raw_line in source_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", maxsplit=1)[0].strip()
        if not line:
            continue
        values = [int(value, 16) for value in line.split(";", maxsplit=1)[0].split()]
        if len(values) not in (2, 3):
            raise RuntimeError(f"Unsupported constraint length: {raw_line}")
        constraints.append((script_for(values[0]), values[0], values[1], values[2] if len(values) == 3 else 0))
    constraints.sort()

    rows = "\n".join(
        f'        new("{script}", 0x{first:X}u, 0x{second:X}u, 0x{third:X}u),'
        for script, first, second, third in constraints
    )
    generated = f'''// <auto-generated />
// Source: HarfBuzz src/ms-use/IndicShapingInvalidCluster.txt.
// Regenerate with eng/generate-vowel-constraints.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class VowelConstraintData
{{
    private static readonly Constraint[] s_constraints =
    [
{rows}
    ];

    public static int MatchLength(string script, uint first, uint second, uint third)
    {{
        ReadOnlySpan<Constraint> constraints = s_constraints;
        for (var index = 0; index < constraints.Length; index++)
        {{
            ref readonly Constraint constraint = ref constraints[index];
            if (constraint.First != first || constraint.Second != second || constraint.Script != script)
            {{
                continue;
            }}
            if (constraint.Third == 0)
            {{
                return 2;
            }}
            if (constraint.Third == third)
            {{
                return 3;
            }}
        }}
        return 0;
    }}

    private readonly record struct Constraint(string Script, uint First, uint Second, uint Third);
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
