#!/usr/bin/env python3
"""Generate Unicode 17 joining-fallback ranges shared by managed/native text."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


EXPECTED_SHA256 = "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"
TRANSPARENT_CATEGORIES = {"Mn", "Me", "Cf"}


def parse_ranges(source: Path) -> list[tuple[int, int]]:
    payload = source.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != EXPECTED_SHA256:
        raise RuntimeError(
            f"UnicodeData.txt SHA-256 mismatch: {digest}; expected {EXPECTED_SHA256}"
        )
    points: list[tuple[int, int]] = []
    pending_start: int | None = None
    pending_category: str | None = None
    for raw_line in payload.decode("utf-8").splitlines():
        fields = raw_line.split(";")
        if len(fields) < 3:
            raise RuntimeError("Malformed UnicodeData.txt record")
        code_point = int(fields[0], 16)
        name = fields[1]
        category = fields[2]
        if name.endswith(", First>"):
            pending_start = code_point
            pending_category = category
            continue
        if name.endswith(", Last>"):
            if pending_start is None or pending_category != category:
                raise RuntimeError("Malformed UnicodeData First/Last range")
            if category in TRANSPARENT_CATEGORIES:
                points.append((pending_start, code_point))
            pending_start = None
            pending_category = None
            continue
        if category in TRANSPARENT_CATEGORIES:
            points.append((code_point, code_point))
    if pending_start is not None:
        raise RuntimeError("Unterminated UnicodeData First/Last range")

    merged: list[tuple[int, int]] = []
    for start, end in points:
        if merged and start == merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], end)
        else:
            merged.append((start, end))
    return merged


def render(ranges: list[tuple[int, int]]) -> str:
    values = [value for pair in ranges for value in pair]
    rows = [
        "        " + ", ".join(str(value) for value in values[index:index + 12]) + ","
        for index in range(0, len(values), 12)
    ]
    return f'''// <auto-generated />
// Source: Unicode 17.0 UnicodeData.txt (Mn, Me, and Cf categories).
// SHA-256: {EXPECTED_SHA256}
// Regenerate with eng/generate-unicode-joining-fallback-table.py.

namespace ProGPU.Text;

internal static class UnicodeJoiningFallbackData
{{
    private static ReadOnlySpan<uint> s_ranges =>
    [
{chr(10).join(rows)}
    ];

    public static bool IsTransparent(uint codePoint)
    {{
        ReadOnlySpan<uint> ranges = s_ranges;
        int low = 0;
        int high = ranges.Length / 2 - 1;
        while (low <= high)
        {{
            int middle = low + ((high - low) >> 1);
            uint start = ranges[middle * 2];
            uint end = ranges[middle * 2 + 1];
            if (codePoint < start) high = middle - 1;
            else if (codePoint > end) low = middle + 1;
            else return true;
        }}
        return false;
    }}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("unicode_data", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render(parse_ranges(args.unicode_data)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
