#!/usr/bin/env python3
"""Generate the Unicode 17 Indic category/position lookup from HarfBuzz."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


CATEGORIES = {
    "X": 0, "C": 1, "V": 2, "N": 3, "H": 4, "ZWNJ": 5,
    "ZWJ": 6, "M": 7, "SM": 8, "A": 9, "VD": 9,
    "GB": 10, "DC": 11, "RS": 12, "MP": 13, "Rf": 14,
    "R": 15, "CM": 16, "S": 17, "CS": 18, "SP": 57,
    # Categories shared with the Khmer/Myanmar machines.
    "VA": 20, "VB": 21, "VL": 22, "VR": 23, "Rt": 25,
    "Xg": 26, "Yg": 27, "As": 32, "MH": 35, "MR": 36,
    "MW": 37, "MY": 38, "PT": 39, "VS": 40, "ML": 41,
}

POSITIONS = {
    "T": 6, "A": 5, "AP": 12, "AS": 9, "C": 4, "BS": 7,
    "B": 8, "X": 14, "R": 11, "L": 3, "LM": 2, "SM": 13,
}


def parse_array(source: str, c_type: str, name: str) -> list[int]:
    match = re.search(
        rf"static const {c_type} {name}\[\d+\]\s*=\s*\{{(?P<body>.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find {name}")
    return [int(value) for value in re.findall(r"\d+", match.group("body"))]


def parse_values(source: str) -> list[int]:
    match = re.search(
        r"static const uint16_t _hb_indic_values\[\d+\]\s*=\s*\{(?P<body>.*?)\};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError("Could not find _hb_indic_values")
    values: list[int] = []
    for category, position in re.findall(r"_\((\w+),(\w+)\)", match.group("body")):
        values.append(CATEGORIES[category] | POSITIONS[position] << 8)
    return values


def format_values(values: list[int], per_line: int) -> str:
    return "\n".join(
        "        " + ", ".join(str(value) for value in values[index : index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    source = (args.harfbuzz_root / "src" / "hb-ot-shaper-indic-table.cc").read_text(encoding="utf-8")
    values = parse_values(source)
    u8 = parse_array(source, "uint8_t", "_hb_indic_u8")
    if len(values) != 42 or len(u8) != 1220:
        raise RuntimeError(f"Unexpected Indic table sizes: values={len(values)}, u8={len(u8)}")

    generated = f'''// <auto-generated />
// Source: HarfBuzz hb-ot-shaper-indic-table.cc, Unicode 17.0.0.
// Regenerate with eng/generate-indic-shaping-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class IndicShapingData
{{
    private static readonly ushort[] s_values =
    [
{format_values(values, 14)}
    ];

    private static readonly byte[] s_u8 =
    [
{format_values(u8, 24)}
    ];

    public static ushort GetProperties(uint codePoint)
    {{
        int valueIndex;
        if (codePoint >= 71_396u)
        {{
            valueIndex = 37;
        }}
        else
        {{
            int level0 = GetNibble(s_u8, (int)(codePoint >> 9));
            int level1 = s_u8[70 + (level0 << 3) + (int)((codePoint >> 6) & 7)];
            int level2 = s_u8[186 + (level1 << 3) + (int)((codePoint >> 3) & 7)];
            int level3 = s_u8[488 + (level2 << 2) + (int)((codePoint >> 1) & 3)];
            valueIndex = s_u8[996 + level3 + (int)(codePoint & 1)];
        }}
        return s_values[valueIndex];
    }}

    private static int GetNibble(byte[] values, int index) =>
        values[index >> 1] >> ((index & 1) << 2) & 15;

    public static byte GetCategory(ushort properties) => (byte)properties;
    public static byte GetPosition(ushort properties) => (byte)(properties >> 8);

    public const byte Other = 0;
    public const byte Consonant = 1;
    public const byte Vowel = 2;
    public const byte Nukta = 3;
    public const byte Halant = 4;
    public const byte Zwnj = 5;
    public const byte Zwj = 6;
    public const byte Matra = 7;
    public const byte SyllableModifier = 8;
    public const byte VedicSign = 9;
    public const byte Placeholder = 10;
    public const byte DottedCircle = 11;
    public const byte RegisterShifter = 12;
    public const byte MatraPost = 13;
    public const byte Repha = 14;
    public const byte Ra = 15;
    public const byte ConsonantMedial = 16;
    public const byte Symbol = 17;
    public const byte ConsonantWithStacker = 18;
    public const byte SyllableModifierPost = 57;
    public const byte VowelAbove = 20;
    public const byte VowelBelow = 21;
    public const byte VowelPre = 22;
    public const byte VowelPost = 23;
    public const byte Robatic = 25;
    public const byte XGroup = 26;
    public const byte YGroup = 27;
    public const byte Asat = 32;
    public const byte MedialHa = 35;
    public const byte MedialRa = 36;
    public const byte MedialWa = 37;
    public const byte MedialYa = 38;
    public const byte PwoTone = 39;
    public const byte VariationSelector = 40;
    public const byte MedialLa = 41;

    public const byte PositionStart = 0;
    public const byte PositionRaToBecomeReph = 1;
    public const byte PositionPreMatra = 2;
    public const byte PositionPreConsonant = 3;
    public const byte PositionBaseConsonant = 4;
    public const byte PositionAfterMain = 5;
    public const byte PositionAboveConsonant = 6;
    public const byte PositionBeforeSub = 7;
    public const byte PositionBelowConsonant = 8;
    public const byte PositionAfterSub = 9;
    public const byte PositionBeforePost = 10;
    public const byte PositionPostConsonant = 11;
    public const byte PositionAfterPost = 12;
    public const byte PositionSyllableModifierVedic = 13;
    public const byte PositionEnd = 14;
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
