#!/usr/bin/env python3
"""Generate the Unicode 17 USE category lookup from pinned HarfBuzz data."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


CATEGORIES = {
    "O": 0, "B": 1, "N": 4, "GB": 5, "CGJ": 6, "SUB": 11, "H": 12,
    "HN": 13, "ZWNJ": 14, "WJ": 16, "R": 18, "VPre": 22, "VMPre": 23,
    "FAbv": 24, "FBlw": 25, "FPst": 26, "MAbv": 27, "MBlw": 28,
    "MPst": 29, "MPre": 30, "CMAbv": 31, "CMBlw": 32, "VAbv": 33,
    "VBlw": 34, "VPst": 35, "VMAbv": 37, "VMBlw": 38, "VMPst": 39,
    "SMAbv": 41, "SMBlw": 42, "CS": 43, "IS": 44, "FMAbv": 45,
    "FMBlw": 46, "FMPst": 47, "Sk": 48, "G": 49, "J": 50, "SB": 51,
    "SE": 52, "HVM": 53, "HM": 54, "HR": 55, "RK": 56,
}


def parse_array(source: str, c_type: str, name: str) -> list[int]:
    match = re.search(
        rf"static const {c_type} {name}\[\d+\]\s*=\s*\{{(?P<body>.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find {name}")
    values = []
    for token in match.group("body").split(","):
        token = token.strip()
        if not token:
            continue
        if token in CATEGORIES:
            values.append(CATEGORIES[token])
        else:
            values.append(int(token.removesuffix("u")))
    return values


def format_values(values: list[int], indent: str, per_line: int) -> str:
    lines = []
    for index in range(0, len(values), per_line):
        chunk = ", ".join(str(value) for value in values[index : index + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    table_path = args.harfbuzz_root / "src" / "hb-ot-shaper-use-table.hh"
    source = table_path.read_text(encoding="utf-8")
    fast_source = source.split("\n#else\n", maxsplit=1)[0]
    u8 = parse_array(fast_source, "uint8_t", "hb_use_u8")
    u16 = parse_array(fast_source, "uint16_t", "hb_use_u16")
    if len(u8) != 3343 or len(u16) != 864:
        raise RuntimeError(f"Unexpected USE table sizes: u8={len(u8)}, u16={len(u16)}")

    generated = f"""// <auto-generated />
// Source: HarfBuzz hb-ot-shaper-use-table.hh, Unicode 17.0.0.
// Regenerate with eng/generate-use-shaping-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class UseShapingData
{{
    private static readonly byte[] s_u8 =
    [
{format_values(u8, "        ", 24)}
    ];

    private static readonly ushort[] s_u16 =
    [
{format_values(u16, "        ", 16)}
    ];

    public static byte GetCategory(uint codePoint)
    {{
        if (codePoint >= 921_600u)
        {{
            return Other;
        }}

        int page = GetNibble(s_u8, (int)(codePoint >> 12));
        int level1 = s_u8[113 + (page << 5) + (int)((codePoint >> 7) & 31)];
        int level2 = s_u16[(level1 << 3) + (int)((codePoint >> 4) & 7)];
        int level3 = s_u8[625 + level2 + (int)((codePoint >> 1) & 7)];
        return s_u8[2953 + (level3 << 1) + (int)(codePoint & 1)];
    }}

    private static int GetNibble(byte[] values, int index) =>
        values[index >> 1] >> ((index & 1) << 2) & 15;

    public const byte Other = 0;
    public const byte Base = 1;
    public const byte BaseNumber = 4;
    public const byte BaseOther = 5;
    public const byte Cgj = 6;
    public const byte ConsonantSubjoined = 11;
    public const byte Halant = 12;
    public const byte HalantNumber = 13;
    public const byte Zwnj = 14;
    public const byte WordJoiner = 16;
    public const byte Repha = 18;
    public const byte VowelPre = 22;
    public const byte VowelModifierPre = 23;
    public const byte FinalAbove = 24;
    public const byte FinalBelow = 25;
    public const byte FinalPost = 26;
    public const byte MedialAbove = 27;
    public const byte MedialBelow = 28;
    public const byte MedialPost = 29;
    public const byte MedialPre = 30;
    public const byte ConsonantModifierAbove = 31;
    public const byte ConsonantModifierBelow = 32;
    public const byte VowelAbove = 33;
    public const byte VowelBelow = 34;
    public const byte VowelPost = 35;
    public const byte VowelModifierAbove = 37;
    public const byte VowelModifierBelow = 38;
    public const byte VowelModifierPost = 39;
    public const byte SymbolModifierAbove = 41;
    public const byte SymbolModifierBelow = 42;
    public const byte ConsonantWithStacker = 43;
    public const byte InvisibleStacker = 44;
    public const byte FinalModifierAbove = 45;
    public const byte FinalModifierBelow = 46;
    public const byte FinalModifierPost = 47;
    public const byte Sakot = 48;
    public const byte Hieroglyph = 49;
    public const byte HieroglyphJoiner = 50;
    public const byte HieroglyphSegmentBegin = 51;
    public const byte HieroglyphSegmentEnd = 52;
    public const byte HalantOrVowelModifier = 53;
    public const byte HieroglyphModifier = 54;
    public const byte HieroglyphMirror = 55;
    public const byte ReorderingKiller = 56;
}}
"""
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
