#!/usr/bin/env python3
"""Generate the Unicode 17 script-range lookup from pinned HarfBuzz data."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_array(source: str, c_type: str, name: str) -> list[int]:
    match = re.search(
        rf"static const {re.escape(c_type)} {re.escape(name)}\[\d+\]\s*=\s*\{{(?P<body>.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find {name}")
    return [int(value) for value in re.findall(r"\d+", match.group("body"))]


def parse_script_map(source: str) -> list[str]:
    match = re.search(
        r"static const hb_script_t _hb_ucd_sc_map\[\d+\]\s*=\s*\{(?P<body>.*?)\};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError("Could not find _hb_ucd_sc_map")
    return re.findall(r"HB_SCRIPT_[A-Z0-9_]+", match.group("body"))


def parse_script_tags(source: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for name, tag in re.findall(r"@(HB_SCRIPT_[A-Z0-9_]+):\s*`([A-Za-z0-9]{4})`", source):
        result.setdefault(name, tag.lower())
    return result


def format_values(values: list[int], per_line: int) -> str:
    return "\n".join(
        "        " + ", ".join(str(value) for value in values[index : index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    ucd_source = (args.harfbuzz_root / "src" / "hb-ucd-table.hh").read_text(encoding="utf-8")
    script_source = (args.harfbuzz_root / "src" / "hb-script-list.h").read_text(encoding="utf-8")
    u8 = parse_array(ucd_source, "uint8_t", "_hb_ucd_u8")
    u16 = parse_array(ucd_source, "uint16_t", "_hb_ucd_u16")
    script_names = parse_script_map(ucd_source)
    script_tags = parse_script_tags(script_source)
    if len(u8) != 19_845 or len(u16) != 10_784 or len(script_names) != 176:
        raise RuntimeError(
            f"Unexpected HarfBuzz UCD data: u8={len(u8)}, u16={len(u16)}, scripts={len(script_names)}"
        )

    def script_index(code_point: int) -> int:
        if code_point >= 918_000:
            return 2
        level0 = u8[11454 + (code_point >> 11)]
        level1 = u8[11903 + (level0 << 4) + ((code_point >> 7) & 15)]
        level2 = u16[3296 + (level1 << 4) + ((code_point >> 3) & 15)]
        return u8[12639 + level2 + (code_point & 7)]

    ranges: list[int] = []
    start = 0
    current = script_index(0)
    for code_point in range(1, 0x110000):
        value = script_index(code_point)
        if value == current:
            continue
        ranges.extend((start, code_point - 1, current))
        start = code_point
        current = value
    ranges.extend((start, 0x10FFFF, current))

    tags = [script_tags.get(name, "") for name in script_names]
    tags[0] = tags[1] = tags[2] = ""
    formatted_tags = ",\n".join(
        "        " + ", ".join(f'"{tag}"' for tag in tags[index : index + 12])
        for index in range(0, len(tags), 12)
    )
    generated = f'''// <auto-generated />
// Source: HarfBuzz hb-ucd-table.hh and hb-script-list.h, Unicode 17.0.0.
// Regenerate with eng/generate-unicode-script-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class UnicodeScriptData
{{
    private static readonly string[] s_scripts =
    [
{formatted_tags}
    ];

    private static readonly uint[] s_ranges =
    [
{format_values(ranges, 18)}
    ];

    public static string GetScript(uint codePoint)
    {{
        var low = 0;
        var high = s_ranges.Length / 3 - 1;
        while (low <= high)
        {{
            int middle = (low + high) >> 1;
            int offset = middle * 3;
            if (codePoint < s_ranges[offset]) high = middle - 1;
            else if (codePoint > s_ranges[offset + 1]) low = middle + 1;
            else return s_scripts[s_ranges[offset + 2]];
        }}
        return string.Empty;
    }}
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
