#!/usr/bin/env python3
"""Generate native packed Unicode tables from ProGPU's managed generated data."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_uint_array(source: str, name: str) -> list[int]:
    match = re.search(
        rf"{re.escape(name)}\s*=\s*\[(?P<body>.*?)\];",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find managed array {name}")
    return [int(value) for value in re.findall(r"\b\d+\b", match.group("body"))]


def parse_ulong_span(source: str, name: str) -> list[int]:
    match = re.search(
        rf"{re.escape(name)}\s*=>\s*\[(?P<body>.*?)\];",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find managed span {name}")
    return [
        int(value, 16)
        for value in re.findall(r"0x([0-9A-Fa-f]+)UL", match.group("body"))
    ]


def parse_uint_span(source: str, name: str) -> list[int]:
    match = re.search(
        rf"{re.escape(name)}\s*=>\s*\[(?P<body>.*?)\];",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find managed span {name}")
    return [int(value) for value in re.findall(r"\b\d+\b", match.group("body"))]


def format_values(values: list[int], per_line: int = 12) -> str:
    return "\n".join(
        "    " + ", ".join(f"{value}U" for value in values[index:index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def format_u64_values(values: list[int], per_line: int = 4) -> str:
    return "\n".join(
        "    " + ", ".join(
            f"0x{value:016X}ULL" for value in values[index:index + per_line]
        ) + ","
        for index in range(0, len(values), per_line)
    )


def pack_tag(value: str) -> int:
    if not value:
        return 0
    if len(value) != 4 or any(ord(character) > 0x7F for character in value):
        raise RuntimeError(f"Invalid OpenType script tag {value!r}")
    result = 0
    for character in value:
        result = result << 8 | ord(character)
    return result


def generate(root: Path) -> str:
    script_path = root / "src/ProGPU.Text/UnicodeScriptData.Generated.cs"
    combining_path = root / "src/ProGPU.Text/UnicodeCombiningClassData.Generated.cs"
    bidi_path = root / "src/ProGPU.Text/Bidi/UnicodeBidiData.Generated.cs"
    grapheme_path = root / "src/ProGPU.Text/UnicodeGraphemeData.Generated.cs"
    arabic_path = root / "src/ProGPU.Text/ArabicJoiningData.Generated.cs"
    joining_fallback_path = root / "src/ProGPU.Text/UnicodeJoiningFallbackData.Generated.cs"
    script_source = script_path.read_text(encoding="utf-8")
    combining_source = combining_path.read_text(encoding="utf-8")
    bidi_source = bidi_path.read_text(encoding="utf-8")
    grapheme_source = grapheme_path.read_text(encoding="utf-8")
    arabic_source = arabic_path.read_text(encoding="utf-8")
    joining_fallback_source = joining_fallback_path.read_text(encoding="utf-8")

    scripts_match = re.search(
        r"s_scripts\s*=\s*\[(?P<body>.*?)\];",
        script_source,
        re.DOTALL,
    )
    if scripts_match is None:
        raise RuntimeError("Could not find managed script tags")
    scripts = re.findall(r'"([^"]*)"', scripts_match.group("body"))
    script_ranges = parse_uint_array(script_source, "s_ranges")
    combining_ranges = parse_uint_array(combining_source, "s_ranges")
    bidi_class_ranges = parse_ulong_span(bidi_source, "ClassRanges")
    bidi_bracket_records = parse_ulong_span(bidi_source, "BracketRecords")
    grapheme_ranges = parse_uint_array(grapheme_source, "s_graphemeRanges")
    extended_pictographic_ranges = parse_uint_array(
        grapheme_source, "s_extendedPictographicRanges"
    )
    indic_conjunct_ranges = parse_uint_array(
        grapheme_source, "s_indicConjunctRanges"
    )
    arabic_joining_packed = parse_uint_span(arabic_source, "Packed")
    joining_fallback_ranges = parse_uint_span(joining_fallback_source, "s_ranges")
    if len(script_ranges) % 3 != 0 or len(combining_ranges) % 3 != 0:
        raise RuntimeError("Managed Unicode range tables are malformed")
    highest_script_index = max(script_ranges[2::3], default=0)
    if highest_script_index >= len(scripts):
        raise RuntimeError("Managed Unicode script table references a missing tag")

    packed_scripts = [pack_tag(value) for value in scripts]
    return f'''// <auto-generated />
// Source: ProGPU.Text UnicodeScriptData.Generated.cs,
// UnicodeCombiningClassData.Generated.cs, UnicodeGraphemeData.Generated.cs,
// ArabicJoiningData.Generated.cs, UnicodeJoiningFallbackData.Generated.cs,
// and Bidi/UnicodeBidiData.Generated.cs.
// Regenerate with: ./eng/generate-native-unicode-tables.py --write

#ifndef PROGPU_NATIVE_UNICODE_DATA_GENERATED_HPP
#define PROGPU_NATIVE_UNICODE_DATA_GENERATED_HPP

#include <array>
#include <cstdint>

namespace progpu::native::text::detail {{

inline constexpr std::array<std::uint32_t, {len(packed_scripts)}> unicode_script_tags{{
{format_values(packed_scripts)}
}};

inline constexpr std::array<std::uint32_t, {len(script_ranges)}> unicode_script_ranges{{
{format_values(script_ranges)}
}};

inline constexpr std::array<std::uint32_t, {len(combining_ranges)}> unicode_combining_class_ranges{{
{format_values(combining_ranges)}
}};

inline constexpr std::array<std::uint64_t, {len(bidi_class_ranges)}> unicode_bidi_class_ranges{{
{format_u64_values(bidi_class_ranges)}
}};

inline constexpr std::array<std::uint64_t, {len(bidi_bracket_records)}> unicode_bidi_bracket_records{{
{format_u64_values(bidi_bracket_records)}
}};

inline constexpr std::array<std::uint32_t, {len(grapheme_ranges)}> unicode_grapheme_ranges{{
{format_values(grapheme_ranges)}
}};

inline constexpr std::array<std::uint32_t, {len(extended_pictographic_ranges)}> unicode_extended_pictographic_ranges{{
{format_values(extended_pictographic_ranges)}
}};

inline constexpr std::array<std::uint32_t, {len(indic_conjunct_ranges)}> unicode_indic_conjunct_ranges{{
{format_values(indic_conjunct_ranges)}
}};

inline constexpr std::array<std::uint8_t, {len(arabic_joining_packed)}> unicode_arabic_joining_packed{{
{format_values(arabic_joining_packed)}
}};

inline constexpr std::array<std::uint32_t, {len(joining_fallback_ranges)}> unicode_joining_fallback_ranges{{
{format_values(joining_fallback_ranges)}
}};

}} // namespace progpu::native::text::detail

#endif
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--verify", action="store_true")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    output = root / "src/ProGPU.Native/src/progpu_native_unicode_data.generated.hpp"
    generated = generate(root)
    if args.verify:
        if not output.exists() or output.read_text(encoding="utf-8") != generated:
            raise RuntimeError(
                "Native Unicode tables are stale; run "
                "./eng/generate-native-unicode-tables.py --write"
            )
        print(f"Verified {output}")
        return 0

    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
