#ifndef PROGPU_NATIVE_MIL_HPP
#define PROGPU_NATIVE_MIL_HPP

#include <cstddef>
#include <cstdint>
#include <memory>
#include <span>
#include <vector>

namespace progpu::native::mil {

// Canonical command identifiers generated by the open-source WPF MCG model.
// Keep numeric values stable: they are the on-wire DUCE/MIL protocol ABI.
enum class command : std::uint32_t {
    invalid = 0x00,
    transport_sync_flush = 0x01,
    transport_destroy_resources_on_channel = 0x02,
    partition_register_for_notifications = 0x03,
    channel_request_tier = 0x04,
    partition_set_vblank_sync_mode = 0x05,
    partition_notify_present = 0x06,
    channel_create_resource = 0x07,
    channel_delete_resource = 0x08,
    channel_duplicate_handle = 0x09,
    d3d_image = 0x0a,
    d3d_image_present = 0x0b,
    bitmap_source = 0x0c,
    bitmap_invalidate = 0x0d,
    double_resource = 0x0e,
    color_resource = 0x0f,
    point_resource = 0x10,
    rect_resource = 0x11,
    size_resource = 0x12,
    matrix_resource = 0x13,
    point3d_resource = 0x14,
    vector3d_resource = 0x15,
    quaternion_resource = 0x16,
    media_player = 0x17,
    render_data = 0x18,
    etw_event_resource = 0x19,
    visual_create = 0x1a,
    visual_set_offset = 0x1b,
    visual_set_transform = 0x1c,
    visual_set_effect = 0x1d,
    visual_set_cache_mode = 0x1e,
    visual_set_clip = 0x1f,
    visual_set_alpha = 0x20,
    visual_set_render_options = 0x21,
    visual_set_content = 0x22,
    visual_set_alpha_mask = 0x23,
    visual_remove_all_children = 0x24,
    visual_remove_child = 0x25,
    visual_insert_child_at = 0x26,
    visual_set_guideline_collection = 0x27,
    visual_set_scrollable_area_clip = 0x28,
    viewport3d_visual_set_camera = 0x29,
    viewport3d_visual_set_viewport = 0x2a,
    viewport3d_visual_set_3d_child = 0x2b,
    visual3d_set_content = 0x2c,
    visual3d_set_transform = 0x2d,
    visual3d_remove_all_children = 0x2e,
    visual3d_remove_child = 0x2f,
    visual3d_insert_child_at = 0x30,
    hwnd_target_create = 0x31,
    hwnd_target_suppress_layered = 0x32,
    target_update_window_settings = 0x33,
    generic_target_create = 0x34,
    target_set_root = 0x35,
    target_set_clear_color = 0x36,
    target_invalidate = 0x37,
    target_set_flags = 0x38,
    hwnd_target_dpi_changed = 0x39,
    glyph_run_create = 0x3a,
    double_buffered_bitmap = 0x3b,
    double_buffered_bitmap_copy_forward = 0x3c,
    partition_notify_policy_change_for_non_interactive_mode = 0x3d,
    draw_line = 0x3e,
    draw_line_animate = 0x3f,
    draw_rectangle = 0x40,
    draw_rectangle_animate = 0x41,
    draw_rounded_rectangle = 0x42,
    draw_rounded_rectangle_animate = 0x43,
    draw_ellipse = 0x44,
    draw_ellipse_animate = 0x45,
    draw_geometry = 0x46,
    draw_image = 0x47,
    draw_image_animate = 0x48,
    draw_glyph_run = 0x49,
    draw_drawing = 0x4a,
    draw_video = 0x4b,
    draw_video_animate = 0x4c,
    push_clip = 0x4d,
    push_opacity_mask = 0x4e,
    push_opacity = 0x4f,
    push_opacity_animate = 0x50,
    push_transform = 0x51,
    push_guideline_set = 0x52,
    push_guideline_y1 = 0x53,
    push_guideline_y2 = 0x54,
    push_effect = 0x55,
    pop = 0x56,
    axis_angle_rotation3d = 0x57,
    quaternion_rotation3d = 0x58,
    perspective_camera = 0x59,
    orthographic_camera = 0x5a,
    matrix_camera = 0x5b,
    model3d_group = 0x5c,
    ambient_light = 0x5d,
    directional_light = 0x5e,
    point_light = 0x5f,
    spot_light = 0x60,
    geometry_model3d = 0x61,
    mesh_geometry3d = 0x62,
    material_group = 0x63,
    diffuse_material = 0x64,
    specular_material = 0x65,
    emissive_material = 0x66,
    transform3d_group = 0x67,
    translate_transform3d = 0x68,
    scale_transform3d = 0x69,
    rotate_transform3d = 0x6a,
    matrix_transform3d = 0x6b,
    pixel_shader = 0x6c,
    implicit_input_brush = 0x6d,
    blur_effect = 0x6e,
    drop_shadow_effect = 0x6f,
    shader_effect = 0x70,
    drawing_image = 0x71,
    transform_group = 0x72,
    translate_transform = 0x73,
    scale_transform = 0x74,
    skew_transform = 0x75,
    rotate_transform = 0x76,
    matrix_transform = 0x77,
    line_geometry = 0x78,
    rectangle_geometry = 0x79,
    ellipse_geometry = 0x7a,
    geometry_group = 0x7b,
    combined_geometry = 0x7c,
    path_geometry = 0x7d,
    solid_color_brush = 0x7e,
    linear_gradient_brush = 0x7f,
    radial_gradient_brush = 0x80,
    image_brush = 0x81,
    drawing_brush = 0x82,
    visual_brush = 0x83,
    bitmap_cache_brush = 0x84,
    dash_style = 0x85,
    pen = 0x86,
    geometry_drawing = 0x87,
    glyph_run_drawing = 0x88,
    image_drawing = 0x89,
    video_drawing = 0x8a,
    drawing_group = 0x8b,
    guideline_set = 0x8c,
    bitmap_cache = 0x8d
};

enum class status : std::uint32_t {
    success,
    end_of_batch,
    invalid_argument,
    malformed_batch,
    unknown_command,
    unsupported_command,
    duplicate_handle,
    invalid_handle,
    invalid_resource_type,
    resource_type_mismatch,
    invalid_graph,
    capacity_exceeded
};

struct command_view {
    command kind{command::invalid};
    std::span<const std::byte> packet{};
    std::uint32_t batch_offset{};
};

struct batch_metrics {
    std::uint32_t command_count{};
    std::uint32_t supported_command_count{};
    std::uint32_t unsupported_command_count{};
    std::uint32_t created_resource_count{};
    std::uint32_t deleted_resource_count{};
    std::uint32_t updated_resource_count{};
    std::uint32_t total_bytes{};
};

struct visual_snapshot {
    std::uint32_t handle{};
    double offset_x{};
    double offset_y{};
    double opacity{1.0};
    std::uint32_t content_handle{};
    std::uint32_t child_count{};
};

struct target_snapshot {
    std::uint32_t handle{};
    std::uint32_t root_handle{};
    float clear_red{};
    float clear_green{};
    float clear_blue{};
    float clear_alpha{};
    std::uint32_t flags{};
};

struct scene_metrics {
    std::uint32_t visual_count{};
    std::uint32_t rectangle_count{};
    std::uint32_t ellipse_count{};
    std::uint32_t rounded_rectangle_count{};
    std::uint32_t line_count{};
    std::uint32_t brush_count{};
    std::uint32_t maximum_visual_depth{};
    std::uint64_t stream_bytes{};
};

class batch_reader final {
public:
    explicit batch_reader(std::span<const std::byte> bytes) noexcept;

    status next(command_view& view) noexcept;
    std::uint32_t offset() const noexcept;

private:
    std::span<const std::byte> bytes_;
    std::uint32_t offset_{};
};

class channel final {
public:
    channel();
    ~channel();
    channel(channel&&) noexcept;
    channel& operator=(channel&&) noexcept;
    channel(const channel&) = delete;
    channel& operator=(const channel&) = delete;

    // Applies a batch transactionally. A malformed, unsupported, or invalid
    // command leaves the live resource graph unchanged.
    status apply(
        std::span<const std::byte> bytes,
        batch_metrics* metrics = nullptr) noexcept;

    // Binds pointer-free RGBA8 pixels to a canonical TYPE_BITMAPSOURCE
    // handle. WPF's native MilCmdBitmapSource carries an in-process WIC
    // pointer, so portable hosts provide the equivalent pixels through this
    // typed channel sideband before scene compilation.
    status set_bitmap_source_rgba8(
        std::uint32_t handle,
        std::uint32_t width,
        std::uint32_t height,
        std::uint32_t row_bytes,
        std::span<const std::byte> pixels) noexcept;

    // Binds the exact local content bounds used by WPF DrawingImage when it
    // maps its retained Drawing into an ImageDrawing destination rectangle.
    status set_drawing_image_bounds(
        std::uint32_t handle,
        double x,
        double y,
        double width,
        double height) noexcept;

    // Binds copied SFNT/TTC bytes to a canonical TYPE_GLYPHRUN handle. The
    // canonical MilCmdGlyphRunCreate keeps indices, advances, offsets, origin,
    // and bounds on the wire but carries an in-process IDWriteFont pointer;
    // portable hosts replace only that pointer through this typed sideband.
    status set_glyph_run_font_sfnt(
        std::uint32_t handle,
        std::uint32_t face_index,
        std::uint32_t style_simulations,
        std::span<const std::byte> font_data) noexcept;

    std::size_t resource_count() const noexcept;
    bool has_resource(std::uint32_t handle) const noexcept;
    std::uint32_t resource_type(std::uint32_t handle) const noexcept;
    std::uint64_t resource_generation(std::uint32_t handle) const noexcept;
    bool try_get_visual(
        std::uint32_t handle,
        visual_snapshot& snapshot) const noexcept;
    bool try_get_visual_child(
        std::uint32_t handle,
        std::uint32_t index,
        std::uint32_t& child_handle) const noexcept;
    bool try_get_target(
        std::uint32_t handle,
        target_snapshot& snapshot) const noexcept;

    // Compiles one retained MIL target into the pointer-free semantic scene
    // stream consumed by both the wgpu-native and Dawn renderers.
    status build_scene(
        std::uint32_t target_handle,
        std::uint64_t scene_id,
        std::uint64_t generation,
        std::vector<std::byte>& stream,
        scene_metrics* metrics = nullptr) const noexcept;

private:
    struct implementation;
    std::unique_ptr<implementation> implementation_;
};

constexpr bool is_known(command value) noexcept {
    const auto raw = static_cast<std::uint32_t>(value);
    return raw >= static_cast<std::uint32_t>(command::transport_sync_flush) &&
        raw <= static_cast<std::uint32_t>(command::bitmap_cache);
}

} // namespace progpu::native::mil

#endif
