using System.Text;
using System.Text.RegularExpressions;

if (args.Length is < 2 or > 3)
{
    throw new ArgumentException(
        "Usage: ProGPU.NativeContractGenerator [--verify] <progpu_native.h> <output.g.cs>");
}

bool verify = args.Length == 3 && args[0] == "--verify";
if (args.Length == 3 && !verify)
{
    throw new ArgumentException("The only supported option is --verify.");
}

string headerPath = Path.GetFullPath(args[verify ? 1 : 0]);
string outputPath = Path.GetFullPath(args[verify ? 2 : 1]);
string header = File.ReadAllText(headerPath, Encoding.UTF8);
string generated = Generate(header, Path.GetFileName(headerPath));

if (verify)
{
    if (!File.Exists(outputPath) ||
        !string.Equals(
            NormalizeLineEndings(File.ReadAllText(outputPath, Encoding.UTF8)),
            NormalizeLineEndings(generated),
            StringComparison.Ordinal))
    {
        Console.Error.WriteLine(
            $"Generated native contract is stale: {outputPath}{Environment.NewLine}" +
            "Run ./eng/progpu-generate-native-contract.sh and commit the result.");
        return 1;
    }

    Console.WriteLine(
        $"Verified generated native C# contract against {headerPath}.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
Console.WriteLine($"Generated {outputPath} from {headerPath}.");
return 0;

static string Generate(string header, string sourceName)
{
    const string marker = @"/\*\s*PROGPU_CSHARP_STRUCT:\s*(?<target>[A-Za-z_][A-Za-z0-9_.]*)\s*\*/\s*typedef\s+struct\s+(?<native>[A-Za-z_][A-Za-z0-9_]*)\s*\{(?<body>.*?)\}\s*[A-Za-z_][A-Za-z0-9_]*\s*;";
    MatchCollection matches = Regex.Matches(
        header,
        marker,
        RegexOptions.Singleline | RegexOptions.CultureInvariant);
    if (matches.Count == 0)
    {
        throw new InvalidDataException(
            "The native header contains no PROGPU_CSHARP_STRUCT markers.");
    }

    var structures = new List<ContractStruct>(matches.Count);
    var targets = new HashSet<string>(StringComparer.Ordinal);
    foreach (Match match in matches)
    {
        string target = match.Groups["target"].Value;
        if (!targets.Add(target))
        {
            throw new InvalidDataException($"Duplicate generated target: {target}.");
        }

        int separator = target.LastIndexOf('.');
        if (separator <= 0 || separator == target.Length - 1)
        {
            throw new InvalidDataException(
                $"Generated struct target must name a container and type: {target}.");
        }

        var fields = new List<ContractField>();
        foreach (string statement in match.Groups["body"].Value.Split(';'))
        {
            Match typeOverride = Regex.Match(
                statement,
                @"/\*\s*PROGPU_CSHARP_TYPE:\s*(?<type>[A-Za-z_][A-Za-z0-9_.]*)\s*\*/",
                RegexOptions.CultureInvariant);
            string value = Regex.Replace(
                statement,
                @"/\*.*?\*/|//[^\r\n]*",
                string.Empty,
                RegexOptions.Singleline | RegexOptions.CultureInvariant)
                .Trim();
            if (value.Length == 0)
            {
                continue;
            }

            Match field = Regex.Match(
                value,
                @"^(?:const\s+)?(?<type>[A-Za-z_][A-Za-z0-9_]*)(?:\s*\*)?\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)$",
                RegexOptions.CultureInvariant);
            if (!field.Success)
            {
                throw new InvalidDataException(
                    $"Unsupported field declaration in {target}: {value}.");
            }

            fields.Add(new ContractField(
                typeOverride.Success
                    ? typeOverride.Groups["type"].Value
                    : MapType(field.Groups["type"].Value),
                ToPascalCase(field.Groups["name"].Value)));
        }

        if (fields.Count == 0)
        {
            throw new InvalidDataException($"Generated struct has no fields: {target}.");
        }

        structures.Add(new ContractStruct(
            target[..separator],
            target[(separator + 1)..],
            match.Groups["native"].Value,
            fields));
    }

    var builder = new StringBuilder(8 * 1024);
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine($"// Source: src/ProGPU.Native/include/{sourceName}");
    builder.AppendLine("// Regenerate with: ./eng/progpu-generate-native-contract.sh");
    builder.AppendLine();
    builder.AppendLine("using System.Runtime.InteropServices;");
    builder.AppendLine("using System.Numerics;");
    builder.AppendLine();
    builder.AppendLine("namespace ProGPU.Backend.Native;");
    builder.AppendLine();

    foreach (IGrouping<string, ContractStruct> group in structures.GroupBy(
        static value => value.Container,
        StringComparer.Ordinal))
    {
        if (string.Equals(group.Key, "Public", StringComparison.Ordinal))
        {
            foreach (ContractStruct structure in group)
            {
                builder.AppendLine(
                    $"// Native source: {structure.NativeName}.");
                builder.AppendLine("[StructLayout(LayoutKind.Sequential)]");
                builder.AppendLine($"public partial struct {structure.Name}");
                builder.AppendLine("{");
                foreach (ContractField field in structure.Fields)
                {
                    builder.AppendLine($"    public {field.Type} {field.Name};");
                }
                builder.AppendLine("}");
                builder.AppendLine();
            }
            continue;
        }
        if (!string.Equals(group.Key, "NativeMethods", StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                $"Unsupported generated C# container: {group.Key}.");
        }

        builder.AppendLine("internal static unsafe partial class NativeMethods");
        builder.AppendLine("{");
        foreach (ContractStruct structure in group)
        {
            builder.AppendLine(
                $"    // Native source: {structure.NativeName}.");
            builder.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
            builder.AppendLine($"    internal partial struct {structure.Name}");
            builder.AppendLine("    {");
            foreach (ContractField field in structure.Fields)
            {
                builder.AppendLine(
                    $"        internal {field.Type} {field.Name};");
            }
            builder.AppendLine("    }");
            builder.AppendLine();
        }
        builder.Length -= Environment.NewLine.Length;
        builder.AppendLine("}");
    }

    return NormalizeLineEndings(builder.ToString().TrimEnd() + Environment.NewLine);
}

static string MapType(string nativeType) => nativeType switch
{
    "uint32_t" => "uint",
    "uint64_t" => "ulong",
    "uint16_t" => "ushort",
        "uint8_t" => "byte",
        "int8_t" => "sbyte",
    "int32_t" => "int",
    "int16_t" => "short",
    "size_t" => "nuint",
    "uintptr_t" => "nuint",
    "float" => "float",
    "progpu_native_color" => "NativeColor",
    "progpu_native_point" => "Vector2",
    "progpu_native_point_3d" => "NativePoint3D",
    "progpu_native_float_4" => "NativeFloat4",
    "progpu_native_matrix_4x4" => "NativeMatrix4x4",
    _ => throw new InvalidDataException(
        $"Unsupported native contract field type: {nativeType}.")
};

static string ToPascalCase(string value)
{
    var builder = new StringBuilder(value.Length);
    bool upper = true;
    foreach (char character in value)
    {
        if (character == '_')
        {
            upper = true;
            continue;
        }

        builder.Append(upper
            ? char.ToUpperInvariant(character)
            : character);
        upper = false;
    }
    return builder.ToString();
}

static string NormalizeLineEndings(string value) =>
    value.Replace("\r\n", "\n", StringComparison.Ordinal)
        .Replace('\r', '\n');

internal sealed record ContractStruct(
    string Container,
    string Name,
    string NativeName,
    IReadOnlyList<ContractField> Fields);

internal sealed record ContractField(string Type, string Name);
