using System.Text;
using System.Globalization;

if (args.Length != 2 || args[0] is not ("--write" or "--verify"))
{
    throw new ArgumentException(
        "Usage: ProGPU.NativeUnicodeCategoryGenerator [--write|--verify] <output.hpp>");
}

string outputPath = Path.GetFullPath(args[1]);
string generated = Generate();
if (args[0] == "--verify")
{
    if (!File.Exists(outputPath) ||
        !string.Equals(
            Normalize(File.ReadAllText(outputPath, Encoding.UTF8)),
            Normalize(generated),
            StringComparison.Ordinal))
    {
        Console.Error.WriteLine(
            $"Generated native Unicode category table is stale: {outputPath}");
        return 1;
    }

    Console.WriteLine("Verified native Unicode categories against .NET 10.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
Console.WriteLine($"Generated {outputPath}.");
return 0;

static string Generate()
{
    var ranges = new List<(ushort Start, ushort End)>();
    int rangeStart = -1;
    for (int value = 0x0250; value <= char.MaxValue; value++)
    {
        bool letter = char.IsLetter((char)value);
        if (letter && rangeStart < 0)
        {
            rangeStart = value;
        }
        else if (!letter && rangeStart >= 0)
        {
            ranges.Add(((ushort)rangeStart, (ushort)(value - 1)));
            rangeStart = -1;
        }
    }
    if (rangeStart >= 0)
    {
        ranges.Add(((ushort)rangeStart, char.MaxValue));
    }

    var categoryRanges = new List<(uint Start, uint End, byte Category)>();
    uint categoryStart = 0;
    byte category = GetCategory(0);
    for (uint value = 1; value <= 0x10FFFF; value++)
    {
        byte current = GetCategory(value);
        if (current == category) continue;
        categoryRanges.Add((categoryStart, value - 1, category));
        categoryStart = value;
        category = current;
    }
    categoryRanges.Add((categoryStart, 0x10FFFF, category));

    var output = new StringBuilder();
    output.AppendLine("// <auto-generated />");
    output.AppendLine("// Source: ProGPU managed SfntFontFace.GetNameScore and UnicodeShapingProperties use .NET 10 Unicode categories.");
    output.AppendLine("// Regenerate with: dotnet run --project eng/ProGPU.NativeUnicodeCategoryGenerator -- --write <output>");
    output.AppendLine();
    output.AppendLine("#ifndef PROGPU_NATIVE_UNICODE_CATEGORIES_GENERATED_HPP");
    output.AppendLine("#define PROGPU_NATIVE_UNICODE_CATEGORIES_GENERATED_HPP");
    output.AppendLine();
    output.AppendLine("#include <array>");
    output.AppendLine("#include <cstdint>");
    output.AppendLine();
    output.AppendLine("namespace progpu::native::text::detail {");
    output.AppendLine();
    output.AppendLine($"inline constexpr std::array<std::uint16_t, {ranges.Count * 2}> sfnt_name_letter_ranges{{");
    for (int index = 0; index < ranges.Count; index++)
    {
        if (index % 4 == 0) output.Append("    ");
        output.Append($"0x{ranges[index].Start:X4}U, 0x{ranges[index].End:X4}U");
        output.Append(',');
        if (index % 4 == 3 || index + 1 == ranges.Count)
        {
            output.AppendLine();
        }
        else
        {
            output.Append(' ');
        }
    }
    output.AppendLine("};");
    output.AppendLine();
    output.AppendLine($"inline constexpr std::array<std::uint32_t, {categoryRanges.Count * 3}> unicode_general_category_ranges{{");
    for (int index = 0; index < categoryRanges.Count; index++)
    {
        if (index % 2 == 0) output.Append("    ");
        var range = categoryRanges[index];
        output.Append($"0x{range.Start:X}U, 0x{range.End:X}U, {range.Category}U,");
        if (index % 2 == 1 || index + 1 == categoryRanges.Count)
        {
            output.AppendLine();
        }
        else
        {
            output.Append(' ');
        }
    }
    output.AppendLine("};");
    output.AppendLine();
    output.AppendLine("} // namespace progpu::native::text::detail");
    output.AppendLine();
    output.AppendLine("#endif");
    return output.ToString();
}

static byte GetCategory(uint value)
{
    if (value is >= 0xD800 and <= 0xDFFF)
        return (byte)UnicodeCategory.OtherNotAssigned;
    return (byte)Rune.GetUnicodeCategory(new Rune(checked((int)value)));
}

static string Normalize(string value) =>
    value.Replace("\r\n", "\n", StringComparison.Ordinal);
