using System.Text;

if (args.Length != 2 || args[0] is not ("--write" or "--verify"))
{
    throw new ArgumentException(
        "Usage: ProGPU.NativeUnicodeCategoryGenerator [--write|--verify] <output.hpp>");
}

string outputPath = Path.GetFullPath(args[1]);
string generated = Generate();
if (args[0] == "--verify")
{
    if (!File.Exists(outputPath) ||
        !string.Equals(
            Normalize(File.ReadAllText(outputPath, Encoding.UTF8)),
            Normalize(generated),
            StringComparison.Ordinal))
    {
        Console.Error.WriteLine(
            $"Generated native SFNT-name letter table is stale: {outputPath}");
        return 1;
    }

    Console.WriteLine("Verified native SFNT-name letter ranges against .NET Char.IsLetter.");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(false));
Console.WriteLine($"Generated {outputPath}.");
return 0;

static string Generate()
{
    var ranges = new List<(ushort Start, ushort End)>();
    int rangeStart = -1;
    for (int value = 0x0250; value <= char.MaxValue; value++)
    {
        bool letter = char.IsLetter((char)value);
        if (letter && rangeStart < 0)
        {
            rangeStart = value;
        }
        else if (!letter && rangeStart >= 0)
        {
            ranges.Add(((ushort)rangeStart, (ushort)(value - 1)));
            rangeStart = -1;
        }
    }
    if (rangeStart >= 0)
    {
        ranges.Add(((ushort)rangeStart, char.MaxValue));
    }

    var output = new StringBuilder();
    output.AppendLine("// <auto-generated />");
    output.AppendLine("// Source: ProGPU managed SfntFontFace.GetNameScore uses .NET 10 Char.IsLetter.");
    output.AppendLine("// Regenerate with: dotnet run --project eng/ProGPU.NativeUnicodeCategoryGenerator -- --write <output>");
    output.AppendLine();
    output.AppendLine("#ifndef PROGPU_NATIVE_SFNT_NAME_LETTER_RANGES_GENERATED_HPP");
    output.AppendLine("#define PROGPU_NATIVE_SFNT_NAME_LETTER_RANGES_GENERATED_HPP");
    output.AppendLine();
    output.AppendLine("#include <array>");
    output.AppendLine("#include <cstdint>");
    output.AppendLine();
    output.AppendLine("namespace progpu::native::text::detail {");
    output.AppendLine();
    output.AppendLine($"inline constexpr std::array<std::uint16_t, {ranges.Count * 2}> sfnt_name_letter_ranges{{");
    for (int index = 0; index < ranges.Count; index++)
    {
        if (index % 4 == 0) output.Append("    ");
        output.Append($"0x{ranges[index].Start:X4}U, 0x{ranges[index].End:X4}U");
        output.Append(',');
        if (index % 4 == 3 || index + 1 == ranges.Count)
        {
            output.AppendLine();
        }
        else
        {
            output.Append(' ');
        }
    }
    output.AppendLine("};");
    output.AppendLine();
    output.AppendLine("} // namespace progpu::native::text::detail");
    output.AppendLine();
    output.AppendLine("#endif");
    return output.ToString();
}

static string Normalize(string value) =>
    value.Replace("\r\n", "\n", StringComparison.Ordinal);
