# An explicit prepared installation is the only native hinting build input.
# No ambient FreeType search, download, source patch or version-only admission.
set(PROGPU_NATIVE_FREETYPE_MANIFEST "" CACHE FILEPATH "Exact signed external FreeType producer receipt")
set(PROGPU_NATIVE_FREETYPE_RID "" CACHE STRING "Exact architecture of the prepared font dependency")
set(PROGPU_NATIVE_FONT_HINTING OFF)
if(NOT PROGPU_NATIVE_FREETYPE_MANIFEST)
    return()
endif()
if(EMSCRIPTEN OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "Prepared native font hinting requires an admitted 64-bit desktop target")
endif()
set(_font_processor "${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_CXX_COMPILER_TARGET MATCHES "^aarch64")
    set(_font_processor arm64)
elseif(CMAKE_CXX_COMPILER_TARGET MATCHES "^x86_64")
    set(_font_processor x64)
elseif(CMAKE_GENERATOR_PLATFORM)
    set(_font_processor "${CMAKE_GENERATOR_PLATFORM}")
endif()
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
    set(_font_processor "${CMAKE_OSX_ARCHITECTURES}")
endif()
string(TOLOWER "${_font_processor}" _font_processor)
if(_font_processor MATCHES "^(arm64|aarch64)$")
    set(_font_arch arm64)
elseif(_font_processor MATCHES "^(x64|x86_64|amd64)$")
    set(_font_arch x64)
else()
    message(FATAL_ERROR "Unknown or multi-architecture native font target: ${_font_processor}")
endif()
if(WIN32)
    set(_font_os win)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(_font_os osx)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_font_os linux)
else()
    message(FATAL_ERROR "Native font hinting is not admitted for ${CMAKE_SYSTEM_NAME}")
endif()
if(NOT PROGPU_NATIVE_FREETYPE_RID STREQUAL "${_font_os}-${_font_arch}")
    message(FATAL_ERROR "Prepared font RID must match the actual selected native target")
endif()
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../eng/progpu-verify-freetype.py"
    --manifest "${PROGPU_NATIVE_FREETYPE_MANIFEST}" --rid "${PROGPU_NATIVE_FREETYPE_RID}"
    RESULT_VARIABLE _font_result OUTPUT_VARIABLE _font_json ERROR_VARIABLE _font_error)
if(NOT _font_result EQUAL 0)
    message(FATAL_ERROR "Prepared font dependency rejected: ${_font_error}")
endif()
foreach(_field library include notices manifest)
    string(JSON PROGPU_NATIVE_FREETYPE_${_field} GET "${_font_json}" ${_field})
endforeach()
add_library(progpu_native_freetype STATIC IMPORTED GLOBAL)
set_target_properties(progpu_native_freetype PROPERTIES
    IMPORTED_LOCATION "${PROGPU_NATIVE_FREETYPE_library}"
    INTERFACE_INCLUDE_DIRECTORIES "${PROGPU_NATIVE_FREETYPE_include}")
if(UNIX AND NOT APPLE)
    # Exact archive symbols bind locally, including in SDK static consumers.
    set_property(TARGET progpu_native_freetype PROPERTY INTERFACE_LINK_OPTIONS
        "LINKER:--exclude-libs,libfreetype.a:libprogpu_native_freetype.a")
elseif(APPLE)
    set_property(TARGET progpu_native_freetype PROPERTY INTERFACE_LINK_OPTIONS
        "LINKER:-load_hidden,${PROGPU_NATIVE_FREETYPE_library}")
endif()
find_package(Threads REQUIRED)
execute_process(COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../eng/progpu-verify-freetype.py"
    --manifest "${PROGPU_NATIVE_FREETYPE_MANIFEST}" --rid "${PROGPU_NATIVE_FREETYPE_RID}" --metadata-only
    RESULT_VARIABLE _font_metadata_result OUTPUT_VARIABLE _font_metadata ERROR_VARIABLE _font_metadata_error)
if(NOT _font_metadata_result EQUAL 0)
    message(FATAL_ERROR "Prepared font redistribution rejected: ${_font_metadata_error}")
endif()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/progpu-native-font-dependency.json" "${_font_metadata}")
string(JSON PROGPU_NATIVE_FREETYPE_sdk_name GET "${_font_metadata}" library)
set(PROGPU_NATIVE_FONT_HINTING ON)
