# Exact optional private static dependency of the text SDK, never ambient ICU.
set(_edit_marker "${_progpu_native_library_dir}/progpu-native-edit-word-dependency.json")
set(_edit_archive "${_progpu_native_library_dir}/${_progpu_native_prefix}progpu_native_edit_icu${_progpu_native_suffix}")
set(_edit_legal "${_progpu_native_runtime_dir}/licenses/edit-word-icu/LICENSE")
if(NOT EXISTS "${_edit_marker}" AND NOT EXISTS "${_edit_archive}" AND
   NOT EXISTS "${_progpu_native_runtime_dir}/licenses/edit-word-icu")
    return()
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT EXISTS "${_edit_marker}" OR
   NOT EXISTS "${_edit_archive}" OR NOT EXISTS "${_edit_legal}")
    message(FATAL_ERROR "Incomplete or unsupported ProGPU EDIT ICU SDK dependency")
endif()
set(_edit_processor "${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_CXX_COMPILER_TARGET MATCHES "^aarch64")
    set(_edit_processor arm64)
elseif(CMAKE_CXX_COMPILER_TARGET MATCHES "^x86_64")
    set(_edit_processor x64)
elseif(CMAKE_GENERATOR_PLATFORM)
    set(_edit_processor "${CMAKE_GENERATOR_PLATFORM}")
endif()
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
    set(_edit_processor "${CMAKE_OSX_ARCHITECTURES}")
endif()
string(TOLOWER "${_edit_processor}" _edit_processor)
if(_edit_processor MATCHES "^(arm64|aarch64)$")
    set(_edit_arch arm64)
elseif(_edit_processor MATCHES "^(x64|amd64|x86_64)$")
    set(_edit_arch x64)
else()
    message(FATAL_ERROR "Unknown or multiple ProGPU EDIT ICU SDK architectures")
endif()
if(WIN32)
    set(_edit_os win)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(_edit_os osx)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_edit_os linux)
else()
    message(FATAL_ERROR "Unsupported ProGPU EDIT ICU SDK platform")
endif()
file(READ "${_edit_marker}" _edit_metadata)
file(READ "${CMAKE_CURRENT_LIST_DIR}/ProGPUNativeEditWordPin.json" _edit_reviewed_pin)
string(JSON _edit_pin GET "${_edit_metadata}" pin)
string(JSON _edit_reviewed_pin GET "${_edit_reviewed_pin}")
string(JSON _edit_schema GET "${_edit_metadata}" schemaVersion)
string(JSON _edit_rid GET "${_edit_metadata}" rid)
string(JSON _edit_name GET "${_edit_metadata}" library)
string(JSON _edit_hash GET "${_edit_metadata}" sha256)
string(JSON _edit_objects GET "${_edit_metadata}" verifiedObjects)
string(JSON _edit_private GET "${_edit_metadata}" producer privateStatic)
string(JSON _edit_suffix GET "${_edit_metadata}" producer symbolSuffix)
string(JSON _edit_expected_suffix GET "${_edit_reviewed_pin}" symbolSuffix)
get_filename_component(_edit_expected_name "${_edit_archive}" NAME)
file(SHA256 "${_edit_archive}" _edit_actual_hash)
if(NOT _edit_pin STREQUAL _edit_reviewed_pin OR NOT _edit_schema STREQUAL "1" OR
   NOT _edit_rid STREQUAL "${_edit_os}-${_edit_arch}" OR NOT _edit_name STREQUAL _edit_expected_name OR
   NOT _edit_hash STREQUAL _edit_actual_hash OR NOT _edit_objects GREATER 0 OR
   NOT _edit_private OR NOT _edit_suffix STREQUAL _edit_expected_suffix)
    message(FATAL_ERROR "ProGPU EDIT ICU SDK identity/hash/policy mismatch")
endif()
string(JSON _edit_notice_count LENGTH "${_edit_metadata}" notices)
string(JSON _edit_notice_name GET "${_edit_metadata}" notices 0 path)
string(JSON _edit_notice_hash GET "${_edit_metadata}" notices 0 sha256)
string(JSON _edit_expected_notice_hash GET "${_edit_reviewed_pin}" licenseSha256)
file(SHA256 "${_edit_legal}" _edit_actual_notice_hash)
if(NOT _edit_notice_count EQUAL 1 OR NOT _edit_notice_name STREQUAL "LICENSE" OR
   NOT _edit_notice_hash STREQUAL _edit_expected_notice_hash OR
   NOT _edit_actual_notice_hash STREQUAL _edit_expected_notice_hash)
    message(FATAL_ERROR "Missing or modified complete ICU original redistribution notices")
endif()
if(NOT TARGET ProGPU::native_edit_icu)
    add_library(ProGPU::native_edit_icu STATIC IMPORTED)
    set_target_properties(ProGPU::native_edit_icu PROPERTIES IMPORTED_LOCATION "${_edit_archive}")
    if(APPLE)
        set_property(TARGET ProGPU::native_edit_icu PROPERTY INTERFACE_LINK_OPTIONS "LINKER:-load_hidden,${_edit_archive}")
    elseif(UNIX)
        set_property(TARGET ProGPU::native_edit_icu PROPERTY INTERFACE_LINK_OPTIONS "LINKER:--exclude-libs,libprogpu_native_edit_icu.a")
    endif()
endif()
find_package(Threads REQUIRED)
set_property(TARGET ProGPU::native_text APPEND PROPERTY INTERFACE_LINK_LIBRARIES
    "ProGPU::native_edit_icu;Threads::Threads;${CMAKE_DL_LIBS}")
