# Optional exact static dependency of the text SDK; no ambient library lookup.
set(_font_marker "${_progpu_native_library_dir}/progpu-native-font-dependency.json")
set(_font_archive "${_progpu_native_library_dir}/${_progpu_native_prefix}progpu_native_freetype${_progpu_native_suffix}")
set(_font_legal "${_progpu_native_runtime_dir}/licenses/freetype")
if(NOT EXISTS "${_font_marker}" AND NOT EXISTS "${_font_archive}" AND NOT EXISTS "${_font_legal}")
    return()
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT EXISTS "${_font_marker}" OR NOT EXISTS "${_font_archive}")
    message(FATAL_ERROR "Incomplete or unsupported ProGPU native font dependency")
endif()
set(_font_processor "${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_CXX_COMPILER_TARGET MATCHES "^aarch64")
    set(_font_processor arm64)
elseif(CMAKE_CXX_COMPILER_TARGET MATCHES "^x86_64")
    set(_font_processor x64)
elseif(CMAKE_GENERATOR_PLATFORM)
    set(_font_processor "${CMAKE_GENERATOR_PLATFORM}")
endif()
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
    set(_font_processor "${CMAKE_OSX_ARCHITECTURES}")
endif()
string(TOLOWER "${_font_processor}" _font_processor)
if(_font_processor MATCHES "^(arm64|aarch64)$")
    set(_font_arch arm64)
elseif(_font_processor MATCHES "^(x64|amd64|x86_64)$")
    set(_font_arch x64)
else()
    message(FATAL_ERROR "Unknown or multiple ProGPU font SDK architectures")
endif()
if(WIN32)
    set(_font_os win)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(_font_os osx)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_font_os linux)
else()
    message(FATAL_ERROR "Unsupported ProGPU font SDK platform")
endif()
file(READ "${_font_marker}" _font_metadata)
file(READ "${CMAKE_CURRENT_LIST_DIR}/ProGPUNativeFontPin.json" _font_reviewed_pin)
string(JSON _font_pin GET "${_font_metadata}" pin)
string(JSON _font_reviewed_pin GET "${_font_reviewed_pin}")
string(JSON _font_schema GET "${_font_metadata}" schemaVersion)
string(JSON _font_rid GET "${_font_metadata}" rid)
string(JSON _font_name GET "${_font_metadata}" library)
string(JSON _font_hash GET "${_font_metadata}" sha256)
get_filename_component(_font_expected_name "${_font_archive}" NAME)
file(SHA256 "${_font_archive}" _font_actual_hash)
if(NOT _font_pin STREQUAL _font_reviewed_pin OR NOT _font_schema STREQUAL "1" OR
   NOT _font_rid STREQUAL "${_font_os}-${_font_arch}" OR NOT _font_name STREQUAL _font_expected_name OR
   NOT _font_hash STREQUAL _font_actual_hash)
    message(FATAL_ERROR "ProGPU font SDK dependency identity/hash mismatch")
endif()
set(_font_required_notices LICENSE.TXT.txt docs__FTL.TXT.txt docs__GPLv2.TXT.txt
    src__bdf__README.txt src__pcf__README.txt src__gzip__zlib.h.txt src__base__fthash.c.txt
    include__freetype__internal__fthash.h.txt src__autofit__ft-hb-ft.c.txt
    src__autofit__ft-hb-decls.h.txt src__autofit__ft-hb-types.h.txt src__autofit__hb-script-list.h.txt NOTICE.txt)
string(JSON _font_notice_count LENGTH "${_font_metadata}" notices)
list(LENGTH _font_required_notices _font_required_count)
if(NOT _font_notice_count EQUAL _font_required_count)
    message(FATAL_ERROR "Incomplete ProGPU font SDK original notices")
endif()
math(EXPR _font_last_notice "${_font_notice_count} - 1")
foreach(_font_index RANGE 0 ${_font_last_notice})
    string(JSON _font_notice_name GET "${_font_metadata}" notices ${_font_index} path)
    string(JSON _font_notice_hash GET "${_font_metadata}" notices ${_font_index} sha256)
    if(NOT _font_notice_name IN_LIST _font_required_notices OR NOT EXISTS "${_font_legal}/${_font_notice_name}")
        message(FATAL_ERROR "Missing or unexpected ProGPU font SDK notice")
    endif()
    file(SHA256 "${_font_legal}/${_font_notice_name}" _font_actual_notice_hash)
    if(NOT _font_notice_hash STREQUAL _font_actual_notice_hash)
        message(FATAL_ERROR "Modified ProGPU font SDK original notice")
    endif()
    list(REMOVE_ITEM _font_required_notices "${_font_notice_name}")
endforeach()
if(_font_required_notices)
    message(FATAL_ERROR "Duplicate ProGPU font SDK notice")
endif()
if(NOT TARGET ProGPU::native_freetype)
    add_library(ProGPU::native_freetype STATIC IMPORTED)
    set_target_properties(ProGPU::native_freetype PROPERTIES IMPORTED_LOCATION "${_font_archive}")
    if(APPLE)
        set_property(TARGET ProGPU::native_freetype PROPERTY INTERFACE_LINK_OPTIONS "LINKER:-load_hidden,${_font_archive}")
    elseif(UNIX)
        set_property(TARGET ProGPU::native_freetype PROPERTY INTERFACE_LINK_OPTIONS "LINKER:--exclude-libs,libprogpu_native_freetype.a")
    endif()
endif()
find_package(Threads REQUIRED)
set_property(TARGET ProGPU::native_text APPEND PROPERTY INTERFACE_LINK_LIBRARIES
    "ProGPU::native_freetype;Threads::Threads;${CMAKE_DL_LIBS}")
