<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" />
    <PackageReference Include="Silk.NET.WebGPU" />
    <PackageReference Include="Silk.NET.Input" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProGPU.Backend\ProGPU.Backend.csproj" />
    <ProjectReference Include="..\ProGPU.Scene\ProGPU.Scene.csproj" />
    <ProjectReference Include="..\ProGPU.Layout\ProGPU.Layout.csproj">
      <Aliases>ProGpu</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\ProGPU.WinUI\ProGPU.WinUI.csproj">
      <Aliases>ProGpu</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\ProGPU.WinRT\ProGPU.WinRT.csproj">
      <Aliases>ProGpu</Aliases>
    </ProjectReference>
  </ItemGroup>
</Project>
