// Generated by eng/progpu-generate-edit-word-symbol-profile.py; do not hand-edit.
// Own original-API observations, not vendor implementation source or a word/index lookup.
// Source head 4aab8ead3eafac60a57b6a646debad132184ef13; run 36867054042; job 110385050238.
// Receipt SHA256 ef40688691684bba820071ac712699884439da99dd456daee86b4e37878ac7c3.
// Only observed BMP So/rawID members with all-three-context AL/ID signatures.
// Unobserved/nonmatching members remain unqualified; no ordinary provider admission.
#pragma once

#include <array>
#include <cstdint>

namespace progpu::native::text::detail {

inline constexpr std::array<std::uint32_t, 138> edit_symbol_line_class_ranges{
    8986U, 8987U, 25U,
    9200U, 9203U, 25U,
    9728U, 9731U, 3U,
    9748U, 9749U, 25U,
    9752U, 9752U, 3U,
    9754U, 9755U, 3U,
    9756U, 9756U, 25U,
    9758U, 9758U, 25U,
    9759U, 9759U, 3U,
    9785U, 9787U, 25U,
    9832U, 9832U, 25U,
    9855U, 9855U, 25U,
    9917U, 9928U, 25U,
    9933U, 9933U, 25U,
    9935U, 9937U, 25U,
    9939U, 9940U, 25U,
    9944U, 9945U, 25U,
    9948U, 9948U, 25U,
    9951U, 9953U, 25U,
    9962U, 9962U, 25U,
    9969U, 9973U, 25U,
    9975U, 9976U, 25U,
    9978U, 9978U, 25U,
    9981U, 9984U, 25U,
    9985U, 9988U, 3U,
    9992U, 9993U, 3U,
    10084U, 10084U, 3U,
    11904U, 11929U, 25U,
    11931U, 12019U, 25U,
    12032U, 12245U, 25U,
    12272U, 12287U, 25U,
    12292U, 12292U, 25U,
    12306U, 12307U, 25U,
    12320U, 12320U, 25U,
    12342U, 12343U, 25U,
    12350U, 12351U, 25U,
    12688U, 12689U, 25U,
    12694U, 12703U, 25U,
    12736U, 12773U, 25U,
    12783U, 12783U, 25U,
    12842U, 12871U, 25U,
    12880U, 12880U, 25U,
    12938U, 12976U, 25U,
    12992U, 13311U, 25U,
    42128U, 42182U, 25U,
    65508U, 65508U, 25U,
};

} // namespace progpu::native::text::detail
