// Generated by eng/progpu-generate-edit-word-item-profile.py; do not hand-edit.
// Only original observed scalar/engine properties; no strings, words, positions or seam answers.
// Source head 4aab8ead3eafac60a57b6a646debad132184ef13; run 36867054042; job 110385050238.
// The declared103 held-out item inputs do not train these properties.
#pragma once

#include <array>
#include <cstdint>

namespace progpu::native::text::detail {

inline constexpr std::array<std::uint32_t, 140> edit_item_property_ranges{
    1488U, 1490U, 24U, 2U,
    1576U, 1576U, 26U, 1U,
    1578U, 1578U, 26U, 1U,
    1585U, 1585U, 26U, 1U,
    1593U, 1593U, 26U, 1U,
    1609U, 1609U, 26U, 1U,
    1633U, 1633U, 27U, 0U,
    1808U, 1808U, 30U, 1U,
    1810U, 1810U, 30U, 1U,
    2325U, 2325U, 34U, 2U,
    2359U, 2359U, 34U, 2U,
    2381U, 2381U, 34U, 2U,
    3585U, 3586U, 31U, 1U,
    3607U, 3607U, 31U, 1U,
    3616U, 3616U, 31U, 1U,
    3618U, 3618U, 31U, 1U,
    3625U, 3625U, 31U, 1U,
    3634U, 3634U, 31U, 1U,
    3652U, 3652U, 31U, 1U,
    3713U, 3714U, 56U, 1U,
    3725U, 3725U, 56U, 1U,
    3732U, 3732U, 56U, 1U,
    3738U, 3738U, 56U, 1U,
    3754U, 3754U, 56U, 1U,
    3760U, 3760U, 56U, 1U,
    3762U, 3762U, 56U, 1U,
    3765U, 3765U, 56U, 1U,
    6016U, 6017U, 58U, 6U,
    6039U, 6040U, 58U, 6U,
    6042U, 6042U, 58U, 6U,
    6047U, 6047U, 58U, 6U,
    6070U, 6070U, 58U, 6U,
    6082U, 6082U, 58U, 6U,
    6098U, 6098U, 58U, 6U,
    65167U, 65167U, 5U, 0U,
};

inline constexpr std::array<std::uint32_t, 7> edit_item_observed_script_domains{
    1634885986U,
    1937338979U,
    1751474802U,
    1684371041U,
    1952997737U,
    1818324768U,
    1802005874U,
};

} // namespace progpu::native::text::detail
