<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net10.0-macos</TargetFrameworks>
    <ApplicationId Condition="'$(TargetFramework)' == 'net10.0-macos'">org.progpu.samples.desktop</ApplicationId>
    <ApplicationTitle Condition="'$(TargetFramework)' == 'net10.0-macos'">ProGPU Samples Desktop</ApplicationTitle>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ProGpuUseWindowsBaseShim>true</ProGpuUseWindowsBaseShim>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WebGPUSharp" />
    <ProjectReference Include="..\ProGPU.Samples\ProGPU.Samples.csproj" />
    <ProjectReference Include="..\ProGPU.Backend.Dawn\ProGPU.Backend.Dawn.csproj" />
    <ProjectReference Include="..\ProGPU.Apple.Media\ProGPU.Apple.Media.csproj"
                      Condition="'$(TargetFramework)' == 'net10.0-macos'" />
    <ProjectReference Include="..\ProGPU.Windows.Media\ProGPU.Windows.Media.csproj"
                      Condition="'$(TargetFramework)' == 'net10.0'" />
    <ProjectReference Include="..\ProGPU.Linux.Media\ProGPU.Linux.Media.csproj"
                      Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>
</Project>
