namespace ProGPU.WinUI.Designer;

using System;
using System.Text;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Documents;
using ProGPU.Vector;
using ProGPU.Layout;
using Thickness = Microsoft.UI.Xaml.Thickness;
using ProGPU.Scene;

public static class DesignerSerializer
{
    private static readonly HashSet<string> Keywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const",
        "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit",
        "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in",
        "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator",
        "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte",
        "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void",
        "volatile", "while"
    };

    public static string SerializeToCSharp(Canvas canvas)
    {
        if (canvas == null) return "";

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ProGPU Visual Designer C# Script Generator");
        sb.AppendLine("// Local Time: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.UI.Xaml;");
        sb.AppendLine("using Microsoft.UI.Xaml.Controls;");
        sb.AppendLine("using Microsoft.UI.Xaml.Documents;");
        sb.AppendLine("using ProGPU.Vector;");
        sb.AppendLine("using ProGPU.Layout;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine();
        sb.AppendLine("public static class VisualTreeFactory");
        sb.AppendLine("{");
        sb.AppendLine("    public static Canvas CreateVisualTree()");
        sb.AppendLine("    {");
        sb.AppendLine("        var rootCanvas = new Canvas");
        sb.AppendLine("        {");
        
        float rootWidth = float.IsNaN(canvas.Width) ? (canvas.Size.X > 0 ? canvas.Size.X : 800f) : canvas.Width;
        float rootHeight = float.IsNaN(canvas.Height) ? (canvas.Size.Y > 0 ? canvas.Size.Y : 600f) : canvas.Height;
        sb.AppendLine($"            Width = {FormatFloat(rootWidth)}f,");
        sb.AppendLine($"            Height = {FormatFloat(rootHeight)}f");
        sb.AppendLine("        };");
        sb.AppendLine();

        int varCounter = 1;
        var declaredNames = new HashSet<string>();

        foreach (var child in canvas.Children)
        {
            if (child is FrameworkElement childFe)
            {
                var childVar = SerializeElement(childFe, ref varCounter, declaredNames, sb, 2);
                sb.AppendLine($"        rootCanvas.Children.Add({childVar});");
                sb.AppendLine();
            }
        }

        sb.AppendLine("        return rootCanvas;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string SerializeElement(FrameworkElement element, ref int varCounter, HashSet<string> declaredNames, StringBuilder sb, int indentLevel)
    {
        var typeName = element.GetType().Name;
        
        // Clean and unique variable name
        string rawName;
        if (string.IsNullOrEmpty(element.Name))
        {
            rawName = typeName.ToLower();
        }
        else
        {
            var sbClean = new StringBuilder();
            foreach (char c in element.Name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sbClean.Append(c);
                }
                else
                {
                    sbClean.Append('_');
                }
            }
            rawName = sbClean.ToString();
        }

        if (string.IsNullOrEmpty(rawName))
        {
            rawName = typeName.ToLower();
        }
        else if (char.IsDigit(rawName[0]))
        {
            rawName = "var_" + rawName;
        }

        if (Keywords.Contains(rawName))
        {
            rawName = "var_" + rawName;
        }

        string varName = rawName;
        int suffix = 1;
        while (declaredNames.Contains(varName))
        {
            varName = $"{rawName}_{suffix++}";
        }
        declaredNames.Add(varName);

        var indent = new string(' ', indentLevel * 4);
        sb.AppendLine($"{indent}var {varName} = new {typeName}");
        sb.AppendLine($"{indent}{{");

        // Write standard properties
        if (!string.IsNullOrEmpty(element.Name))
        {
            sb.AppendLine($"{indent}    Name = \"{EscapeStringLiteral(element.Name)}\",");
        }

        float width = float.IsNaN(element.Width) ? element.Size.X : element.Width;
        float height = float.IsNaN(element.Height) ? element.Size.Y : element.Height;
        if (width <= 0) width = 120f;
        if (height <= 0) height = 36f;

        sb.AppendLine($"{indent}    Width = {FormatFloat(width)}f,");
        sb.AppendLine($"{indent}    Height = {FormatFloat(height)}f,");

        if (element.Opacity != 1.0f)
        {
            sb.AppendLine($"{indent}    Opacity = {FormatFloat(element.Opacity)}f,");
        }

        if (element.Rotation != 0f)
        {
            sb.AppendLine($"{indent}    Rotation = {FormatFloat(element.Rotation)}f,");
        }

        if (element.RenderTransformOrigin != new System.Numerics.Vector2(0.5f, 0.5f))
        {
            sb.AppendLine($"{indent}    RenderTransformOrigin = new System.Numerics.Vector2({FormatFloat(element.RenderTransformOrigin.X)}f, {FormatFloat(element.RenderTransformOrigin.Y)}f),");
        }

        // Margin & Padding
        var margin = element.Margin;
        if (margin.Left != 0 || margin.Top != 0 || margin.Right != 0 || margin.Bottom != 0)
        {
            sb.AppendLine($"{indent}    Margin = new Microsoft.UI.Xaml.Thickness({FormatFloat(margin.Left)}f, {FormatFloat(margin.Top)}f, {FormatFloat(margin.Right)}f, {FormatFloat(margin.Bottom)}f),");
        }

        var padding = element.Padding;
        if (padding.Left != 0 || padding.Top != 0 || padding.Right != 0 || padding.Bottom != 0)
        {
            sb.AppendLine($"{indent}    Padding = new Microsoft.UI.Xaml.Thickness({FormatFloat(padding.Left)}f, {FormatFloat(padding.Top)}f, {FormatFloat(padding.Right)}f, {FormatFloat(padding.Bottom)}f),");
        }

        // Background / BorderBrush / CornerRadius etc. via Reflection
        var type = element.GetType();

        var cornerRadiusProp = type.GetProperty("CornerRadius");
        if (cornerRadiusProp != null)
        {
            var cr = cornerRadiusProp.GetValue(element);
            if (cr is float fcr && fcr != 0f)
            {
                sb.AppendLine($"{indent}    CornerRadius = {FormatFloat(fcr)}f,");
            }
        }

        var backgroundProp = type.GetProperty("Background");
        if (backgroundProp != null)
        {
            var bg = backgroundProp.GetValue(element);
            if (bg is ThemeResourceBrush trb)
            {
                sb.AppendLine($"{indent}    Background = new ThemeResourceBrush(\"{trb.ResourceKey}\"),");
            }
            else if (bg is SolidColorBrush scb)
            {
                var c = scb.Color;
                sb.AppendLine($"{indent}    Background = new SolidColorBrush(new Vector4({FormatFloat(c.X)}f, {FormatFloat(c.Y)}f, {FormatFloat(c.Z)}f, {FormatFloat(c.W)}f)),");
            }
        }

        var borderBrushProp = type.GetProperty("BorderBrush");
        if (borderBrushProp != null)
        {
            var bb = borderBrushProp.GetValue(element);
            if (bb is ThemeResourceBrush trb)
            {
                sb.AppendLine($"{indent}    BorderBrush = new ThemeResourceBrush(\"{trb.ResourceKey}\"),");
            }
            else if (bb is SolidColorBrush scb)
            {
                var c = scb.Color;
                sb.AppendLine($"{indent}    BorderBrush = new SolidColorBrush(new Vector4({FormatFloat(c.X)}f, {FormatFloat(c.Y)}f, {FormatFloat(c.Z)}f, {FormatFloat(c.W)}f)),");
            }
        }

        var borderThicknessProp = type.GetProperty("BorderThickness");
        if (borderThicknessProp != null)
        {
            var bt = borderThicknessProp.GetValue(element);
            if (bt is Thickness t && (t.Left != 0 || t.Top != 0 || t.Right != 0 || t.Bottom != 0))
            {
                sb.AppendLine($"{indent}    BorderThickness = new Microsoft.UI.Xaml.Thickness({FormatFloat(t.Left)}f, {FormatFloat(t.Top)}f, {FormatFloat(t.Right)}f, {FormatFloat(t.Bottom)}f),");
            }
        }

        // Horizontal and Vertical Alignment
        var horizAlignProp = type.GetProperty("HorizontalAlignment");
        if (horizAlignProp != null)
        {
            var ha = horizAlignProp.GetValue(element);
            if (ha != null)
            {
                sb.AppendLine($"{indent}    HorizontalAlignment = ProGPU.Layout.HorizontalAlignment.{ha},");
            }
        }
        
        var vertAlignProp = type.GetProperty("VerticalAlignment");
        if (vertAlignProp != null)
        {
            var va = vertAlignProp.GetValue(element);
            if (va != null)
            {
                sb.AppendLine($"{indent}    VerticalAlignment = ProGPU.Layout.VerticalAlignment.{va},");
            }
        }

        // Slider / Progress specific properties
        var valProp = type.GetProperty("Value");
        if (valProp != null && valProp.PropertyType == typeof(float))
        {
            sb.AppendLine($"{indent}    Value = {FormatFloat((float)valProp.GetValue(element))}f,");
        }

        var minProp = type.GetProperty("Minimum");
        if (minProp != null && minProp.PropertyType == typeof(float))
        {
            sb.AppendLine($"{indent}    Minimum = {FormatFloat((float)minProp.GetValue(element))}f,");
        }

        var maxProp = type.GetProperty("Maximum");
        if (maxProp != null && maxProp.PropertyType == typeof(float))
        {
            sb.AppendLine($"{indent}    Maximum = {FormatFloat((float)maxProp.GetValue(element))}f,");
        }

        var checkedProp = type.GetProperty("IsChecked");
        if (checkedProp != null && checkedProp.PropertyType == typeof(bool))
        {
            sb.AppendLine($"{indent}    IsChecked = {((bool)checkedProp.GetValue(element) ? "true" : "false")},");
        }

        var isOnProp = type.GetProperty("IsOn");
        if (isOnProp != null && isOnProp.PropertyType == typeof(bool))
        {
            sb.AppendLine($"{indent}    IsOn = {((bool)isOnProp.GetValue(element) ? "true" : "false")},");
        }

        var textProp = type.GetProperty("Text");
        if (textProp != null && textProp.PropertyType == typeof(string))
        {
            var txt = textProp.GetValue(element) as string;
            if (!string.IsNullOrEmpty(txt))
            {
                sb.AppendLine($"{indent}    Text = \"{EscapeStringLiteral(txt)}\",");
            }
        }

        var placeholderProp = type.GetProperty("PlaceholderText");
        if (placeholderProp != null && placeholderProp.PropertyType == typeof(string))
        {
            var txt = placeholderProp.GetValue(element) as string;
            if (!string.IsNullOrEmpty(txt))
            {
                sb.AppendLine($"{indent}    PlaceholderText = \"{EscapeStringLiteral(txt)}\",");
            }
        }

        var passwordProp = type.GetProperty("Password");
        if (passwordProp != null && passwordProp.PropertyType == typeof(string))
        {
            var txt = passwordProp.GetValue(element) as string;
            if (!string.IsNullOrEmpty(txt))
            {
                sb.AppendLine($"{indent}    Password = \"{EscapeStringLiteral(txt)}\",");
            }
        }

        var fontSizeProp = type.GetProperty("FontSize");
        if (fontSizeProp != null && fontSizeProp.PropertyType == typeof(float))
        {
            sb.AppendLine($"{indent}    FontSize = {FormatFloat((float)fontSizeProp.GetValue(element))}f,");
        }

        // Panel orientation
        var orientProp = type.GetProperty("Orientation");
        if (orientProp != null)
        {
            var o = orientProp.GetValue(element);
            sb.AppendLine($"{indent}    Orientation = Orientation.{o},");
        }

        // WrapPanel specific properties
        if (element is WrapPanel wrapFe)
        {
            if (!float.IsNaN(wrapFe.ItemWidth))
            {
                sb.AppendLine($"{indent}    ItemWidth = {FormatFloat(wrapFe.ItemWidth)}f,");
            }
            if (!float.IsNaN(wrapFe.ItemHeight))
            {
                sb.AppendLine($"{indent}    ItemHeight = {FormatFloat(wrapFe.ItemHeight)}f,");
            }
            if (wrapFe.HorizontalSpacing != 0f)
            {
                sb.AppendLine($"{indent}    HorizontalSpacing = {FormatFloat(wrapFe.HorizontalSpacing)}f,");
            }
            if (wrapFe.VerticalSpacing != 0f)
            {
                sb.AppendLine($"{indent}    VerticalSpacing = {FormatFloat(wrapFe.VerticalSpacing)}f,");
            }
        }

        // DockPanel specific properties
        if (element is DockPanel dockFe)
        {
            if (!dockFe.LastChildFill)
            {
                sb.AppendLine($"{indent}    LastChildFill = false,");
            }
        }

        sb.AppendLine($"{indent}}};");

        // Grid Definition Serialization
        if (element is Grid gridFe)
        {
            foreach (var colDef in gridFe.ColumnDefinitions)
            {
                if (colDef.UnitType == GridUnitType.Auto)
                    sb.AppendLine($"{indent}{varName}.ColumnDefinitions.Add(GridLength.Auto);");
                else if (colDef.UnitType == GridUnitType.Star)
                    sb.AppendLine($"{indent}{varName}.ColumnDefinitions.Add(GridLength.Star({FormatFloat(colDef.Value)}f));");
                else
                    sb.AppendLine($"{indent}{varName}.ColumnDefinitions.Add(new GridLength({FormatFloat(colDef.Value)}f, GridUnitType.Absolute));");
            }

            foreach (var rowDef in gridFe.RowDefinitions)
            {
                if (rowDef.UnitType == GridUnitType.Auto)
                    sb.AppendLine($"{indent}{varName}.RowDefinitions.Add(GridLength.Auto);");
                else if (rowDef.UnitType == GridUnitType.Star)
                    sb.AppendLine($"{indent}{varName}.RowDefinitions.Add(GridLength.Star({FormatFloat(rowDef.Value)}f));");
                else
                    sb.AppendLine($"{indent}{varName}.RowDefinitions.Add(new GridLength({FormatFloat(rowDef.Value)}f, GridUnitType.Absolute));");
            }
        }

        // Set Attached properties
        float left = Canvas.GetLeft(element);
        float top = Canvas.GetTop(element);
        if (left != 0)
        {
            sb.AppendLine($"{indent}Canvas.SetLeft({varName}, {FormatFloat(left)}f);");
        }
        if (top != 0)
        {
            sb.AppendLine($"{indent}Canvas.SetTop({varName}, {FormatFloat(top)}f);");
        }

        int row = Microsoft.UI.Xaml.Controls.Grid.GetRow(element);
        if (row != 0)
        {
            sb.AppendLine($"{indent}Grid.SetRow({varName}, {row});");
        }

        int col = Microsoft.UI.Xaml.Controls.Grid.GetColumn(element);
        if (col != 0)
        {
            sb.AppendLine($"{indent}Grid.SetColumn({varName}, {col});");
        }

        // Attached Dock properties if element's parent is DockPanel
        if (element.Parent is DockPanel)
        {
            var dock = DockPanel.GetDock(element);
            if (dock != Dock.Left)
            {
                sb.AppendLine($"{indent}DockPanel.SetDock({varName}, Dock.{dock});");
            }
        }

        // Content/Children recursion and association
        if (typeName == "SplitView")
        {
            var paneProp = type.GetProperty("Pane");
            if (paneProp != null)
            {
                var paneVal = paneProp.GetValue(element);
                if (paneVal is FrameworkElement paneFe)
                {
                    var paneVar = SerializeElement(paneFe, ref varCounter, declaredNames, sb, indentLevel);
                    sb.AppendLine($"{indent}{varName}.Pane = {paneVar};");
                }
            }
            
            var splitContentProp = type.GetProperty("Content");
            if (splitContentProp != null)
            {
                var contentVal = splitContentProp.GetValue(element);
                if (contentVal is FrameworkElement contentFe)
                {
                    var contentVar = SerializeElement(contentFe, ref varCounter, declaredNames, sb, indentLevel);
                    sb.AppendLine($"{indent}{varName}.Content = {contentVar};");
                }
            }
        }
        else
        {
            var contentProp = type.GetProperty("Content");
            if (contentProp != null)
            {
                var contentVal = contentProp.GetValue(element);
                if (contentVal is RichTextBlock rtb)
                {
                    string rtbBase = $"{varName}_content_text";
                    string rtbName = rtbBase;
                    int rtbSuffix = 1;
                    while (declaredNames.Contains(rtbName))
                    {
                        rtbName = $"{rtbBase}_{rtbSuffix++}";
                    }
                    declaredNames.Add(rtbName);

                    sb.AppendLine($"{indent}var {rtbName} = new RichTextBlock();");
                    foreach (var inline in rtb.Inlines)
                    {
                        if (inline is Run run)
                        {
                            sb.AppendLine($"{indent}{rtbName}.Inlines.Add(new Run(\"{EscapeStringLiteral(run.Text)}\"));");
                        }
                    }
                    sb.AppendLine($"{indent}{varName}.Content = {rtbName};");
                }
                else if (contentVal is FrameworkElement contentFe)
                {
                    var contentVar = SerializeElement(contentFe, ref varCounter, declaredNames, sb, indentLevel);
                    sb.AppendLine($"{indent}{varName}.Content = {contentVar};");
                }
                else if (contentVal != null)
                {
                    string s = contentVal.ToString() ?? "";
                    sb.AppendLine($"{indent}{varName}.Content = \"{EscapeStringLiteral(s)}\";");
                }
            }
        }

        // Border Child
        var childProp = type.GetProperty("Child");
        if (childProp != null)
        {
            var childVal = childProp.GetValue(element);
            if (childVal is FrameworkElement childFe)
            {
                var childVar = SerializeElement(childFe, ref varCounter, declaredNames, sb, indentLevel);
                sb.AppendLine($"{indent}{varName}.Child = {childVar};");
            }
        }

        // Panel Children
        if (element is Panel panel && panel.Children.Count > 0)
        {
            foreach (var childNode in panel.Children)
            {
                if (childNode is FrameworkElement childFe)
                {
                    var childVar = SerializeElement(childFe, ref varCounter, declaredNames, sb, indentLevel);
                    sb.AppendLine($"{indent}{varName}.Children.Add({childVar});");
                }
            }
        }

        return varName;
    }

    private static string EscapeStringLiteral(string? s)
    {
        if (s == null) return "";
        return s.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
    }

    private static string FormatFloat(float value)
    {
        return value.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
    }
}

